In [1]:
import os 
import pandas as pd
import numpy as np
import glob
pd.set_option('display.max_columns', None)

In [2]:
#ADNI dataset 
#"/project_cephfs/3022017.06/ADNI/phenotypes/Velocity files" --> may contain this. Also the surface holes = euler nr
root = "/project_cephfs/3022017.06/ADNI/freesurfer"

#aseg data
aseg_path = os.path.join(root, "aseg_stats.txt")
aseg_data = pd.read_csv(
    aseg_path,
    sep="\\s+",
    engine='python'
)

#lh data
lh_path = os.path.join(root, "lh_aparc_a2009s_stats.txt")
lh_data = pd.read_csv(
    lh_path,
    sep="\\s+",
    engine='python'
)

#rh data
rh_path = os.path.join(root, "rh_aparc_a2009s_stats.txt")
rh_data = pd.read_csv(
    rh_path,
    sep="\\s+",
    engine='python'
)

#merge left and right
lh_data = lh_data.rename(columns={"lh.aparc.a2009s.thickness" : "scan_id"})
rh_data = rh_data.rename(columns={"rh.aparc.a2009s.thickness" : "scan_id"})
lh_rh_data = pd.merge(lh_data, rh_data, on="scan_id", how="left")

#merge lh_rh and aseg
aseg_data = aseg_data.rename(columns={"Measure:volume" : "scan_id"})
adni_data = pd.merge(lh_rh_data, aseg_data, on="scan_id", how="left")
adni_data

#removing all the 'long' files 
adni_data = adni_data[~adni_data['scan_id'].str.contains('long', case=False, na=False)]

#replacing the full name with the subj nr to be able to merge with the covariates dataset
pattern = r'\d{3}_S_\d{4}'

adni_data["id"] = adni_data["scan_id"]
adni_data["participant_id"] = adni_data["scan_id"].str.extract(f'({pattern})')
adni_data["Acq Date"] = adni_data["scan_id"].str.extract(r'(\d{8})')
adni_data["scan_id"] = adni_data["scan_id"].str.replace(r'^.*?(?=I\d+$)', '', regex=True)

adni_data["Acq Date"] = pd.to_datetime(adni_data["Acq Date"], format='%Y%m%d').dt.strftime('%m/%d/%Y')
adni_data["Acq Date dt"] = pd.to_datetime(adni_data["Acq Date"], format='%m/%d/%Y')
adni_data = adni_data.sort_values(by=["participant_id", "Acq Date dt"])


cols_to_move = ['scan_id', 'participant_id','Acq Date', 'Acq Date dt','id']
new_columns = cols_to_move + [col for col in adni_data.columns if col not in cols_to_move]
adni_data = adni_data[new_columns]

first_occurrences = adni_data.drop_duplicates(subset="participant_id", keep="first")

first_occurrences = first_occurrences.reset_index(drop=True)

#zoek baseline data

,scan_id,participant_id,Acq Date,Acq Date dt,id,lh_G_and_S_frontomargin_thickness,lh_G_and_S_occipital_inf_thickness,lh_G_and_S_paracentral_thickness,lh_G_and_S_subcentral_thickness,lh_G_and_S_transv_frontopol_thickness,lh_G_and_S_cingul-Ant_thickness,lh_G_and_S_cingul-Mid-Ant_thickness,lh_G_and_S_cingul-Mid-Post_thickness,lh_G_cingul-Post-dorsal_thickness,lh_G_cingul-Post-ventral_thickness,lh_G_cuneus_thickness,lh_G_front_inf-Opercular_thickness,lh_G_front_inf-Orbital_thickness,lh_G_front_inf-Triangul_thickness,lh_G_front_middle_thickness,lh_G_front_sup_thickness,lh_G_Ins_lg_and_S_cent_ins_thickness,lh_G_insular_short_thickness,lh_G_occipital_middle_thickness,lh_G_occipital_sup_thickness,lh_G_oc-temp_lat-fusifor_thickness,lh_G_oc-temp_med-Lingual_thickness,lh_G_oc-temp_med-Parahip_thickness,lh_G_orbital_thickness,lh_G_pariet_inf-Angular_thickness,lh_G_pariet_inf-Supramar_thickness,lh_G_parietal_sup_thickness,lh_G_postcentral_thickness,lh_G_precentral_thickness,lh_G_precuneus_thickness,lh_G_rectus_thickness,lh_G_subcallosal_thickness,lh_G_temp_sup-G_T_transv_thickness,lh_G_temp_sup-Lateral_thickness,lh_G_temp_sup-Plan_polar_thickness,lh_G_temp_sup-Plan_tempo_thickness,lh_G_temporal_inf_thickness,lh_G_temporal_middle_thickness,lh_Lat_Fis-ant-Horizont_thickness,lh_Lat_Fis-ant-Vertical_thickness,lh_Lat_Fis-post_thickness,lh_Pole_occipital_thickness,lh_Pole_temporal_thickness,lh_S_calcarine_thickness,lh_S_central_thickness,lh_S_cingul-Marginalis_thickness,lh_S_circular_insula_ant_thickness,lh_S_circular_insula_inf_thickness,lh_S_circular_insula_sup_thickness,lh_S_collat_transv_ant_thickness,lh_S_collat_transv_post_thickness,lh_S_front_inf_thickness,lh_S_front_middle_thickness,lh_S_front_sup_thickness,lh_S_interm_prim-Jensen_thickness,lh_S_intrapariet_and_P_trans_thickness,lh_S_oc_middle_and_Lunatus_thickness,lh_S_oc_sup_and_transversal_thickness,lh_S_occipital_ant_thickness,lh_S_oc-temp_lat_thickness,lh_S_oc-temp_med_and_Lingual_thickness,lh_S_orbital_lateral_thickness,lh_S_orbital_med-olfact_thickness,lh_S_orbital-H_Shaped_thickness,lh_S_parieto_occipital_thickness,lh_S_pericallosal_thickness,lh_S_postcentral_thickness,lh_S_precentral-inf-part_thickness,lh_S_precentral-sup-part_thickness,lh_S_suborbital_thickness,lh_S_subparietal_thickness,lh_S_temporal_inf_thickness,lh_S_temporal_sup_thickness,lh_S_temporal_transverse_thickness,lh_MeanThickness_thickness,BrainSegVolNotVent_x,eTIV_x,rh_G_and_S_frontomargin_thickness,rh_G_and_S_occipital_inf_thickness,rh_G_and_S_paracentral_thickness,rh_G_and_S_subcentral_thickness,rh_G_and_S_transv_frontopol_thickness,rh_G_and_S_cingul-Ant_thickness,rh_G_and_S_cingul-Mid-Ant_thickness,rh_G_and_S_cingul-Mid-Post_thickness,rh_G_cingul-Post-dorsal_thickness,rh_G_cingul-Post-ventral_thickness,rh_G_cuneus_thickness,rh_G_front_inf-Opercular_thickness,rh_G_front_inf-Orbital_thickness,rh_G_front_inf-Triangul_thickness,rh_G_front_middle_thickness,rh_G_front_sup_thickness,rh_G_Ins_lg_and_S_cent_ins_thickness,rh_G_insular_short_thickness,rh_G_occipital_middle_thickness,rh_G_occipital_sup_thickness,rh_G_oc-temp_lat-fusifor_thickness,rh_G_oc-temp_med-Lingual_thickness,rh_G_oc-temp_med-Parahip_thickness,rh_G_orbital_thickness,rh_G_pariet_inf-Angular_thickness,rh_G_pariet_inf-Supramar_thickness,rh_G_parietal_sup_thickness,rh_G_postcentral_thickness,rh_G_precentral_thickness,rh_G_precuneus_thickness,rh_G_rectus_thickness,rh_G_subcallosal_thickness,rh_G_temp_sup-G_T_transv_thickness,rh_G_temp_sup-Lateral_thickness,rh_G_temp_sup-Plan_polar_thickness,rh_G_temp_sup-Plan_tempo_thickness,rh_G_temporal_inf_thickness,rh_G_temporal_middle_thickness,rh_Lat_Fis-ant-Horizont_thickness,rh_Lat_Fis-ant-Vertical_thickness,rh_Lat_Fis-post_thickness,rh_Pole_occipital_thickness,rh_Pole_temporal_thickness,rh_S_calcarine_thickness,rh_S_central_thickness,rh_S_cingul-Marginalis_thickness,rh_S_circular_insula_ant_thickness,rh_S_circular_insula_inf_thickness,rh_S_circular_insula_sup_thickness,rh_S_collat_transv_ant_thickness,rh_S_collat_transv_post_thickness,rh_S_front_inf_thickness,rh_S_front_middle_thickness,rh_S_front_sup_thickness,rh_S_interm_prim-Jensen_thickness,rh_S_intrapariet_and_P_trans_thickness,rh_S_oc_middle_and_Lunatus_thickness,rh_S_oc_sup_and_transversal_thickness,rh_S_occipital_ant_thickness,rh_S_oc-temp_lat_thickness,rh_S_oc-temp_med_and_Lingual_thickness,rh_S_orbital_lateral_thickness,rh_S_orbital_med-olfact_thickness,rh_S_orbital-H_Shaped_thickness,rh_S_parieto_occipital_thickness,rh_S_pericallosal_thickness,rh_S_postcentral_thickness,rh_S_precentral-inf-part_thickness,rh_S_precentral-sup-part_thickness,rh_S_suborbital_thickness,rh_S_subparietal_thickness,rh_S_temporal_inf_thickness,rh_S_temporal_sup_thickness,rh_S_temporal_transverse_thickness,rh_MeanThickness_thickness,BrainSegVolNotVent_y,eTIV_y,Left-Lateral-Ventricle,Left-Inf-Lat-Vent,Left-Cerebellum-White-Matter,Left-Cerebellum-Cortex,Left-Thalamus,Left-Caudate,Left-Putamen,Left-Pallidum,3rd-Ventricle,4th-Ventricle,Brain-Stem,Left-Hippocampus,Left-Amygdala,CSF,Left-Accumbens-area,Left-VentralDC,Left-vessel,Left-choroid-plexus,Right-Lateral-Ventricle,Right-Inf-Lat-Vent,Right-Cerebellum-White-Matter,Right-Cerebellum-Cortex,Right-Thalamus,Right-Caudate,Right-Putamen,Right-Pallidum,Right-Hippocampus,Right-Amygdala,Right-Accumbens-area,Right-VentralDC,Right-vessel,Right-choroid-plexus,5th-Ventricle,WM-hypointensities,Left-WM-hypointensities,Right-WM-hypointensities,non-WM-hypointensities,Left-non-WM-hypointensities,Right-non-WM-hypointensities,Optic-Chiasm,CC_Posterior,CC_Mid_Posterior,CC_Central,CC_Mid_Anterior,CC_Anterior,BrainSegVol,BrainSegVolNotVent,lhCortexVol,rhCortexVol,CortexVol,lhCerebralWhiteMatterVol,rhCerebralWhiteMatterVol,CerebralWhiteMatterVol,SubCortGrayVol,TotalGrayVol,SupraTentorialVol,SupraTentorialVolNotVent,MaskVol,BrainSegVol-to-eTIV,MaskVol-to-eTIV,lhSurfaceHoles,rhSurfaceHoles,SurfaceHoles,EstimatedTotalIntraCranialVol
0,I238627,002_S_0295,06/02/2011,2011-06-02,002_S_0295_20110602075636_I238627,2.054,2.332,2.523,2.686,2.681,2.387,2.332,2.426,2.444,2.456,1.951,2.657,3.014,2.753,2.599,2.589,3.057,3.325,2.594,2.350,3.019,1.960,2.903,2.608,2.563,2.656,2.536,2.257,2.890,2.578,2.246,2.166,2.500,2.779,2.943,2.497,2.693,2.929,2.518,2.543,2.218,1.961,3.263,1.930,2.076,2.337,2.794,2.462,2.392,2.380,2.065,2.324,2.049,2.341,2.802,2.182,1.995,2.380,2.334,2.416,2.209,1.997,2.100,2.429,2.192,1.718,2.239,2.279,2.340,1.897,2.284,2.313,2.420,2.132,2.43338,1068760.0,1.687191e+06,2.080,2.619,2.443,2.717,2.296,2.415,2.609,2.582,2.795,2.575,1.861,2.653,2.669,2.684,2.537,2.655,2.824,2.967,2.536,2.436,2.730,2.072,2.952,2.548,2.442,2.615,2.486,2.088,2.841,2.564,2.231,2.177,2.308,3.022,2.943,2.639,2.604,2.839,2.215,2.393,2.276,1.987,3.159,1.997,1.968,2.400,2.498,2.332,2.381,2.534,2.254,2.183,1.851,2.214,2.008,2.147,1.941,2.005,2.319,2.307,2.264,1.691,1.951,2.443,2.250,1.672,2.141,2.416,2.153,1.979,2.264,2.166,2.329,2.102,2.37691,1068760.0,1.687191e+06,27360.1,1178.9,12982.8,56458.0,7607.5,3370.6,4515.8,2023.3,2248.8,1882.0,21885.3,3635.0,1456.5,1615.8,358.0,3965.3,58.0,1060.0,20002.7,1400.6,12186.5,53978.2,6801.5,3561.6,5156.6,2070.8,3849.7,1876.9,397.0,4242.1,62.0,735.3,0.0,3688.8,0.0,0.0,0.0,0.0,0.0,195.0,1015.8,675.3,428.8,382.5,779.7,1126213.0,1068760.0,220764.309707,218008.267247,438772.576954,219806.5,220113.5,439920.0,56727.0,605997.576954,991851.0,934398.0,1630660.0,0.667508,0.966494,10.0,8.0,18.0,1.687191e+06
1,I30118,002_S_0413,11/15/2006,2006-11-15,002_S_0413_20061115141346_I30118,2.039,2.397,2.301,2.447,2.429,2.443,2.495,2.447,2.580,2.271,1.849,2.682,2.644,2.477,2.447,2.572,3.087,3.573,2.501,2.105,2.671,2.006,3.150,2.530,2.532,2.594,2.240,1.980,2.894,2.527,2.168,1.719,2.515,2.898,2.760,2.641,2.829,2.826,1.950,2.186,2.420,2.073,3.186,1.695,1.865,2.191,2.739,2.515,2.463,2.435,2.376,2.131,2.081,2.093,1.945,2.082,2.057,2.098,2.144,2.496,2.325,2.066,2.294,2.424,2.224,1.484,2.072,2.401,2.485,2.028,2.234,2.237,2.322,2.467,2.35354,1026466.0,1.258181e+06,2.165,2.155,2.312,2.585,2.170,2.584,2.533,2.370,2.797,2.693,1.830,2.752,2.591,2.326,2.382,2.682,3.127,3.267,2.471,2.120,2.805,1.890,3.150,2.675,2.386,2.444,2.124,1.985,2.721,2.473,2.082,1.835,2.636,2.811,2.749,2.519,2.813,2.786,2.121,1.935,2.308,1.953,3.107,1.885,1.852,2.169,2.575,2.612,2.440,2.456,2.115,2.097,2.077,2.209,2.371,1.980,1.852,2.157,1.999,2.399,2.272,2.105,2.090,2.522,2.230,1.670,1.946,2.245,2.244,2.062,2.166,2.173,2.375,2.104,2.33749,1026466.0,1.258181e+06,14558.7,1099.5,11647.2,45477.7,5892.4,3481.4,3657.4,1698.2,2387.1,1295.8,18692.0,3504.9,1798.2,1294.7,376.3,3295.5,26.3,750.5,16290.6,870.6,11603.2,43211.1,5825.0,3463.0,3915.1,1615.9,3564.4,2099.9,512.8,3313.6,17.8,686.6,0.0,3338.5,0.0,0.0,0.0,0.0,0.0,115.1,900.2,347.3,397.7,397.6,813.6,1065429.0,1026466.0,221586.592272,222805.532434,444392.124706,213541.5,210605.5,424147.0,48806.0,581127.124706,955222.0,916259.0,1555808.0,0.846801,1.236554,19.0,10.0,29.0,1.258181e+06
2,I32917,002_S_0559,12/12/2006,2006-12-12,002_S_0559_20061212094451_I32917,2.136,2.265,2.115,2.496,2.160,2.342,2.250,2.351,2.789,2.896,1.658,2.386,2.565,2.371,2.283,2.308,3.194,3.651,2.337,1.971,2.932,1.927,2.756,2.337,2.299,2.413,2.064,1.961,2.449,2.211,2.248,2.387,2.408,2.613,2.635,2.451,2.631,2.766,2.042,2.018,2.046,1.847,2.884,1.741,1.909,1.906,2.509,2.605,2.176,2.446,2.013,2.079,2.083,2.163,2.414,2.029,1.733,2.088,2.143,2.378,2.197,1.957,1.999,2.452,2.049,1.545,1.955,2.097,2.068,1.706,2.313,2.345,2.273,2.576,2.24001,1094955.0,1.653836e+06,2.446,2.118,2.154,2.432,2.347,2.553,2.482,2.390,2.986,3.037,1.726,2.498,2.348,2.294,2.459,2.524,3.153,3.389,2.247,1.942,2.691,1.982,2.816,2.374,2.468,2.390,2.039,1.960,2.435,2.225,2.174,2.491,2.413,2.649,2.604,2.169,2.693,2.826,2.000,2.297,2.037,1.852,2.895,1.644,1.924,1.979,2.209,2.537,2.372,2.634,1.948,1.999,2.088,2.139,1.927,1.936,1.755,2.039,2.063,2.323,2.082,2.037,2.206,2.493,2.052,1.605,1.831,2.113,2.128,2.020,2.098,2.281,2.264,2.070,2.24741,1094955.0,1.653836e+06,17154.4,1449.3,13793.1,48930.5,6880.7,3216.6,4888.5,1784.2,2703.8,3248.5,24107.6,3834.5,2119.1,1220.0,645.0,4310.6,65.6,1379.0,17225.0,1332.3,14272.8,49841.2,6877.5,3476.8,4892.5,1741.3,3759.5,2182.6,673.5,4374.6,84.6,1267.8,0.0,3781.3,0.0,0.0,0.0,0.0,0.0,239.1,1064.1,440.9,427.4,467.2,981.8,1141382.0,1094955.0,223461.708807,223551.153366,447012.862172,234941.0,231666.0,466607.0,57364.0,602896.862172,1016460.0,970033.0,1665330.0,0.690142,1.006950,15.0,27.0,42.0,1.653836e+06
3,I243898,002_S_0685,07/08/2011,2011-07-08,002_S_0685_20110708070427_I243898,2.257,2.206,2.252,2.674,2.345,2.560,2.445,2.253,2.824,2.377,1.801,2.726,2.683,2.665,2.534,2.821,2.873,3.448,2.372,1.998,2.633,1.958,3.002,2.446,2.318,2.620,2.249,2.133,2.631,2.399,2.364,2.041,2.335,2.798,3.197,2.291,2.940,2.695,2.068,2.134,2.013,1.881,3.280,1.624,1.827,2.053,2.809,2.400,2.293,2.209,1.811,2.132,1.971,2.217,2.463,1.981,1.717,1.854,2.017,2.248,2.292,1.989,2.070,2.527,2.061,1.687,2.059,2.253,2.223,2.067,2.256,2.223,2.335,2.309,2.31815,971146.0,1.529247e+06,2.448,2.189,2.048,2.676,2.666,2.550,2.348,2.403,2.831,2.867,1.815,2.772,2.556,2.423,2.564,2.718,3.339,2.935,2.479,2.148,2.860,2.202,3.050,2.489,2.414,2.538,2.309,2.045,2.712,2.286,2.393,1.982,2.388,2.861,2.887,2.163,2.545,3.000,2.067,2.438,2.015,1.792,3.328,1.677,1.740,2.018,2.424,2.051,2.251,2.511,1.850,2.188,2.243,2.347,2.222,2.091,1.667,1.903,2.158,2.600,2.284,2.083,1.845,2.587,1.956,1.516,1.948,2.291,2.165,2.060,2.397,2.293,2.404,2.238,2.32661,971146.0,1.529247e+06,21146.6,810.6,16337.0,48130.8,6495.4,3652.2,4515.6,2174.3,3458.0,1784.3,19327.9,3712.0,1514.2,1387.3,202.2,4061.9,44.8,1188.7,19915.3,1349.1,15265.4,48578.6,6290.3,3584.7,4386.3,1919.7,3618.1,1558.0,306.6,4306.5,46.6,1050.0,0.0,28059.3,0.0,0.0,0.0,0.0,0.0,232.6,999.3,395.9,426.1,447.1,1053.7,1023086.0,971146.0,194476.488107,197524.513221,392001.001328,199412.0,199001.0,398413.0,53921.0,543644.001328,895554.0,843614.0,1483210.0,0.669013,0.969896,21.0,27.0,48.0,1.529247e+06
4,I20087,002_S_0729,08/02/2006,2006-08-02,002_S_0729_20060802064745_I20087,2.082,2.161,2.377,2.332,2.323,2.386,2.566,2.271,2.719,2.773,1.866,2.487,2.916,2.477,2.355,2.597,2.818,2.925,2.309,2.024,2.938,2.118,2.365,2.568,2.227,2.375,2.171,2.037,2.694,2.252,2.258,2.026,2.353,2.811,2.562,2.460,2.826,2.867,2.662,1.990,2.078,2.066,3.180,1.723,1.876,2.052,2.870,2.323,2.389,2.708,1.760,2.081,1.964,2.246,1.790,1.816,1.649,1.860,2.016,2.242,2.380,1.774,2.293,2.589,2.046,2.033,1.987,2.269,2.159,2.269,2.104,2.305,2.309,2.357,2.30455,867482.0,1.233198e+06,2.225,2.310,2.142,2.369,2.186,2.810,2.496,2.504,2.642,2.714,1.813,2.515,2.279,2.428,2.421,2.653,2.986,2.850,2.233,1.940,2.610,2.204,2.813,2.464,2.290,2.508,2.155,1.957,2.621,2.090,2.189,2.287,2.363,2.647,2.998,2.179,2.570,2.728,2.354,2.056,2.150,1.965,3.182,1.761,1.758,1.994,2.463,2.288,2.368,2.387,1.716,2.102,2.055,2.356,2.265,1.998,1.997,1.837,2.051,2.296,2.541,1.981,2.469,2.588,2.044,2.259,1.898,2.333,2.244,1.969,2.211,2.278,2.259,2.276,2.30884,867482.0,1.233198e+06,9179.7,450.1,10207.5,44542.4,5672.4,3131.0,4306.8,1746.0,1092.2,1894.9,17589.6,3098.6,1216.3,1042.3,413.3,3188.2,34.6,526.5,8244.5,650.3,10287.7,43681.4,5599.9,3269.4,4397.7,1674.8,3074.2,1280.8,459.6,2950.9,13.1,645.2,0.0,3264.7,0.0,0.0,0.0,0.0,0.0,130.9,983.5,501.0,402.8,492.4,777.2,890656.0,867482.0,177531.325728,181201.045099,358732.370827,174681.0,180828.0,355509.0,47011.0,493467.370827,783437.0,760263.0,1238517.0,0.722233,1.004313,11.0,10.0,21.0,1.233198e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1227,I294080,941_S_4420,03/28/2012,2012-03-28,941_S_4420_20120328160909_I294080,2.332,2.229,2.345,2.451,2.531,2.302,2.190,2.265,2.692,2.569,1.761,2.582,2.723,2.369,2.286,2.469,2.797,3.038,2.151,2.070,2.577,1.828,3.011,2.436,2.325,2.412,2.207,2.101,2.485,2.413,2.438,1.915,2.256,2.670,3.225,2.394,2.580,2.618,2.185,2.022,2.170,1.980,2.879,1.915,2.106,2.187,2.769,2.361,2.266,2.232,2.093,2.019,1.969,2.186,2.027,2.075,1.906,1.973,2.081,2.332,2.225,1.816,2.235,2.269,2.081,1.699,1.947,2.084,2.201,2.037,2.175,2.410,2.268,2.113,2.28337,1100576.0,1.648887e+06,2.434,2.350,2.365,2.237,2.611,2.323,2.312,2.464,2.892,2.323,1.860,2.403,2.478,2.565,2.524,2.550,2.675,3.090,2.377,2.181,2.582,1.838,2.901,2.842,2.237,2.449,2.179,1.959,2.449,2.368,2.366,2.215,1.980,2.597,2.839,2.506,2.685,2.549,2.321,2.194,2.207,1.950,3.019,1.834,1.912,2.263,2.225,2.536,2.255,2.485,1.622,2.035,2.125,2.150,1.996,2.101,2.143,2.022,1.920,2.496,2.214,1.933,2.026,2.249,2.059,1.711,1.921,2.213,2.151,1.963,2.286,2.358,2.192,1.953,2.28994,1100576.0,1.648887e+06,24503.3,1336.9,13205.3,45606.3,6462.9,3282.8,5460.2,2210.1,1233.9,1644.7,19837.5,4001.6,1578.5,1404.5,479.3,3465.2,43.4,895.4,18998.0,1198.9,11779.5,49655.3,6514.8,3264.4,5283.6,2143.3,3840.6,1754.2,454.6,4015.8,11.0,853.0,0.0,4082.3,0.0,0.0,0.0,0.0,0.0,220.4,1052.9,455.3,458.2,472.6,823.0,1152910.0,1100576.0,223514.607970,221264.415778,444779.023748,241302.5,240529.5,481832.0,55605.0,595822.023748,1033263.0,980929.0,1684850.0,0.699205,1.021811,42.0,23.0,65.0,1.648887e+06
1228,I307653,941_S_4764,06/01/2012,2012-06-01,941_S_4764_20120601125133_I307653,2.390,2.273,2.346,2.420,2.560,2.423,2.193,2.340,2.620,2.284,1.867,2.409,2.473,2.353,2.470,2.494,2.886,3.318,2.540,1.928,2.819,2.018,2.900,2.443,2.403,2.395,2.057,2.039,2.633,2.328,2.364,1.978,2.267,2.685,2.939,2.230,2.713,2.751,1.664,2.091,2.081,2.010,3.126,1.696,1.996,2.088,2.728,2.426,2.282,2.168,1.991,1.962,2.003,2.242,1.893,1.934,1.774,1.985,2.226,2.244,2.270,1.843,2.192,2.334,2.008,1.596,1.984,2.116,2.324,2.198,2.001,2.259,2.210,2.497,2.26628,911773.0,1.501232e+06,2.523,2.611,2.383,2.121,2.648,2.524,2.543,2.352,2.707,2.605,1.906,2.493,2.940,2.733,2.658,2.586,2.491,3.134,2.412,2.011,2.711,2.277,2.860,2.944,2.414,2.517,2.241,1.938,2.685,2.283,2.629,1.989,2.206,2.622,2.719,2.370,2.750,2.748,2.105,2.356,2.176,1.983,3.210,1.803,1.923,2.001,2.975,2.294,2.519,2.252,2.116,2.091,2.121,2.311,1.936,1.960,1.893,2.018,2.140,2.266,2.302,2.245,2.279,2.623,2.064,1.939,2.046,2.154,2.174,2.739,2.230,2.161,2.207,2.146,2.34057,911773.0,1.501232e+06,23552.1,1472.5,13205.7,52898.2,6019.8,2553.3,3522.6,1633.9,3309.5,2767.2,20808.8,3386.3,1414.1,1622.3,386.9,3859.5,65.1,900.1,32670.7,1682.8,13771.9,54908.0,6127.5,2597.7,3331.7,1801.1,3293.6,1649.8,319.5,3550.1,7.0,757.9,0.0,8845.7,0.0,0.0,0.0,0.0,0.0,181.0,874.4,292.2,299.1,267.4,654.6,980431.0,911773.0,195101.782272,201573.914802,396675.697074,166665.5,169401.5,336067.0,46648.0,551220.697074,847073.0,778415.0,1509139.0,0.653084,1.005267,25.0,31.0,56.0,1.501232e+06
1229,I366196,941_S_5124,04/09/2013,2013-04-09,941_S_5124_20130409152906_I366196,2.377,2.142,2.325,2.660,2.447,2.544,2.191,1.712,1.542,1.576,1.980,2.737,2.718,2.496,2.609,2.689,3.148,3.627,2.531,2.169,2.891,1.984,2.395,2.565,2.690,2.784,2.558,2.463,2.762,2.263,2.660,1.644,2.902,2.896,3.558,2.525,2.861,2.816,2.538,2.195,2.298,1.909,3.185,1.781,1.998,2.280,2.492,2.832,2.515,3.162,2.055,2.334,2.302,2.459,2.595,2.324,2.053,2.270,2.312,2.287,2.426,2.074,2.178,2.649,2.173,1.246,2.227,2.546,2.497,2.160,2.209,2.261,2.414,2.413,2.33439,933149.0,1.520806e+06,2.385,2.277,2.337,2.504,2.561,2.457,2.025,1.188,1.013,2.096,1.871,2.571,2.478,2.561,2.686,2.577,2.959,3.643,2.476,2.117,2.560,2.443,2.600,2.658,2.672,2.542,2.251,2.310,2.581,2.064,2.556,2.175,2.616,2.840,2.930,2.431,2.667,2.688,2.048,2.582,2.360,2.218,3.419,1.859,1.802,1.662,3.108,2.695,2.512,2.856,2.600,2.129,2.146,2.441,2.216,2.281,2.231,2.121,2.210,2.218,2.612,2.016,2.447,2.655,1.776,1.600,2.151,2.241,2.278,1.978,1.189,2.437,2.467,2.317,2.31796,933149.0,1.520806e+06,15774.6,835.7,14415.6,41087.8,3160.2,2126.6,2959.6,1256.1,1059.2,1072.4,15940.5,1928.6,1216.1,224.7,160.6,1696.5,11.0,117.5,11582.5,1373.1,12932.4,42162.7,3042.4,2089.6,3344.5,1496.6,1974.6,1302.7,232.0,2320.1,17.7,88.4,0.0,4685.5,0.0,0.0,0.0,0.0,0.0,44.8,70.0,62.8,287.2,486.0,580.0,965281.0,933149.0,214017.595793,207683.916890,421701.512683,194013.5,181019.5,375033.0,31013.0,535903.512683,855049.0,822917.0,1450459.0,0.634717,0.953743,17.0,33.0,50.0,1.520806e+06

In [4]:
#age/sex/site data
root = "/project_cephfs/3022017.06/ADNI/phenotypes"
asl_path = os.path.join(root, "Velocity_4_04_2025.csv")
asl_data = pd.read_csv(
    asl_path,
    sep=",",
    engine='python'
)

#age/sex/site data
root = "/project_cephfs/3022017.06/ADNI/phenotypes"
asl_path2 = os.path.join(root, "Velocity_MP-RAGE_4_04_2025.csv")
asl_data2 = pd.read_csv(
    asl_path2,
    sep=",",
    engine='python'
)

#removed Age here as an experiment to see whether the correct age still shows up later when we merge in the cells that creates the final dataset
asl_data = asl_data[['Image Data ID', 'Subject','Group', 'Sex', 'Acq Date']]
asl_data2 = asl_data2[['Image Data ID', 'Subject','Group', 'Sex', 'Acq Date']]

cov_data = pd.concat([asl_data, asl_data2], axis=0)
cov_data = cov_data.rename(columns={"Image Data ID" : "scan_id"})
cov_data = cov_data.rename(columns={"Subject" : "participant_id"})
cov_data['Acq Date'] = pd.to_datetime(cov_data['Acq Date']).dt.strftime('%m/%d/%Y')



merged_data = cov_data.merge(first_occurrences, on=["participant_id","Acq Date","scan_id"], how="right")
# merged_data = merged_data.rename(columns={'participant_id_x':'participant_id'})

# merged_data
#cov_data = cov_data[cov_data['participant_id'] == "002_S_0295"]
merged_data = merged_data.drop(columns=['Acq Date', 'id'])
merged_data = merged_data.rename(columns={"Acq Date dt": "Acq Date"})
merged_data

,scan_id,participant_id,Group,Sex,Acq Date,lh_G_and_S_frontomargin_thickness,lh_G_and_S_occipital_inf_thickness,lh_G_and_S_paracentral_thickness,lh_G_and_S_subcentral_thickness,lh_G_and_S_transv_frontopol_thickness,lh_G_and_S_cingul-Ant_thickness,lh_G_and_S_cingul-Mid-Ant_thickness,lh_G_and_S_cingul-Mid-Post_thickness,lh_G_cingul-Post-dorsal_thickness,lh_G_cingul-Post-ventral_thickness,lh_G_cuneus_thickness,lh_G_front_inf-Opercular_thickness,lh_G_front_inf-Orbital_thickness,lh_G_front_inf-Triangul_thickness,lh_G_front_middle_thickness,lh_G_front_sup_thickness,lh_G_Ins_lg_and_S_cent_ins_thickness,lh_G_insular_short_thickness,lh_G_occipital_middle_thickness,lh_G_occipital_sup_thickness,lh_G_oc-temp_lat-fusifor_thickness,lh_G_oc-temp_med-Lingual_thickness,lh_G_oc-temp_med-Parahip_thickness,lh_G_orbital_thickness,lh_G_pariet_inf-Angular_thickness,lh_G_pariet_inf-Supramar_thickness,lh_G_parietal_sup_thickness,lh_G_postcentral_thickness,lh_G_precentral_thickness,lh_G_precuneus_thickness,lh_G_rectus_thickness,lh_G_subcallosal_thickness,lh_G_temp_sup-G_T_transv_thickness,lh_G_temp_sup-Lateral_thickness,lh_G_temp_sup-Plan_polar_thickness,lh_G_temp_sup-Plan_tempo_thickness,lh_G_temporal_inf_thickness,lh_G_temporal_middle_thickness,lh_Lat_Fis-ant-Horizont_thickness,lh_Lat_Fis-ant-Vertical_thickness,lh_Lat_Fis-post_thickness,lh_Pole_occipital_thickness,lh_Pole_temporal_thickness,lh_S_calcarine_thickness,lh_S_central_thickness,lh_S_cingul-Marginalis_thickness,lh_S_circular_insula_ant_thickness,lh_S_circular_insula_inf_thickness,lh_S_circular_insula_sup_thickness,lh_S_collat_transv_ant_thickness,lh_S_collat_transv_post_thickness,lh_S_front_inf_thickness,lh_S_front_middle_thickness,lh_S_front_sup_thickness,lh_S_interm_prim-Jensen_thickness,lh_S_intrapariet_and_P_trans_thickness,lh_S_oc_middle_and_Lunatus_thickness,lh_S_oc_sup_and_transversal_thickness,lh_S_occipital_ant_thickness,lh_S_oc-temp_lat_thickness,lh_S_oc-temp_med_and_Lingual_thickness,lh_S_orbital_lateral_thickness,lh_S_orbital_med-olfact_thickness,lh_S_orbital-H_Shaped_thickness,lh_S_parieto_occipital_thickness,lh_S_pericallosal_thickness,lh_S_postcentral_thickness,lh_S_precentral-inf-part_thickness,lh_S_precentral-sup-part_thickness,lh_S_suborbital_thickness,lh_S_subparietal_thickness,lh_S_temporal_inf_thickness,lh_S_temporal_sup_thickness,lh_S_temporal_transverse_thickness,lh_MeanThickness_thickness,BrainSegVolNotVent_x,eTIV_x,rh_G_and_S_frontomargin_thickness,rh_G_and_S_occipital_inf_thickness,rh_G_and_S_paracentral_thickness,rh_G_and_S_subcentral_thickness,rh_G_and_S_transv_frontopol_thickness,rh_G_and_S_cingul-Ant_thickness,rh_G_and_S_cingul-Mid-Ant_thickness,rh_G_and_S_cingul-Mid-Post_thickness,rh_G_cingul-Post-dorsal_thickness,rh_G_cingul-Post-ventral_thickness,rh_G_cuneus_thickness,rh_G_front_inf-Opercular_thickness,rh_G_front_inf-Orbital_thickness,rh_G_front_inf-Triangul_thickness,rh_G_front_middle_thickness,rh_G_front_sup_thickness,rh_G_Ins_lg_and_S_cent_ins_thickness,rh_G_insular_short_thickness,rh_G_occipital_middle_thickness,rh_G_occipital_sup_thickness,rh_G_oc-temp_lat-fusifor_thickness,rh_G_oc-temp_med-Lingual_thickness,rh_G_oc-temp_med-Parahip_thickness,rh_G_orbital_thickness,rh_G_pariet_inf-Angular_thickness,rh_G_pariet_inf-Supramar_thickness,rh_G_parietal_sup_thickness,rh_G_postcentral_thickness,rh_G_precentral_thickness,rh_G_precuneus_thickness,rh_G_rectus_thickness,rh_G_subcallosal_thickness,rh_G_temp_sup-G_T_transv_thickness,rh_G_temp_sup-Lateral_thickness,rh_G_temp_sup-Plan_polar_thickness,rh_G_temp_sup-Plan_tempo_thickness,rh_G_temporal_inf_thickness,rh_G_temporal_middle_thickness,rh_Lat_Fis-ant-Horizont_thickness,rh_Lat_Fis-ant-Vertical_thickness,rh_Lat_Fis-post_thickness,rh_Pole_occipital_thickness,rh_Pole_temporal_thickness,rh_S_calcarine_thickness,rh_S_central_thickness,rh_S_cingul-Marginalis_thickness,rh_S_circular_insula_ant_thickness,rh_S_circular_insula_inf_thickness,rh_S_circular_insula_sup_thickness,rh_S_collat_transv_ant_thickness,rh_S_collat_transv_post_thickness,rh_S_front_inf_thickness,rh_S_front_middle_thickness,rh_S_front_sup_thickness,rh_S_interm_prim-Jensen_thickness,rh_S_intrapariet_and_P_trans_thickness,rh_S_oc_middle_and_Lunatus_thickness,rh_S_oc_sup_and_transversal_thickness,rh_S_occipital_ant_thickness,rh_S_oc-temp_lat_thickness,rh_S_oc-temp_med_and_Lingual_thickness,rh_S_orbital_lateral_thickness,rh_S_orbital_med-olfact_thickness,rh_S_orbital-H_Shaped_thickness,rh_S_parieto_occipital_thickness,rh_S_pericallosal_thickness,rh_S_postcentral_thickness,rh_S_precentral-inf-part_thickness,rh_S_precentral-sup-part_thickness,rh_S_suborbital_thickness,rh_S_subparietal_thickness,rh_S_temporal_inf_thickness,rh_S_temporal_sup_thickness,rh_S_temporal_transverse_thickness,rh_MeanThickness_thickness,BrainSegVolNotVent_y,eTIV_y,Left-Lateral-Ventricle,Left-Inf-Lat-Vent,Left-Cerebellum-White-Matter,Left-Cerebellum-Cortex,Left-Thalamus,Left-Caudate,Left-Putamen,Left-Pallidum,3rd-Ventricle,4th-Ventricle,Brain-Stem,Left-Hippocampus,Left-Amygdala,CSF,Left-Accumbens-area,Left-VentralDC,Left-vessel,Left-choroid-plexus,Right-Lateral-Ventricle,Right-Inf-Lat-Vent,Right-Cerebellum-White-Matter,Right-Cerebellum-Cortex,Right-Thalamus,Right-Caudate,Right-Putamen,Right-Pallidum,Right-Hippocampus,Right-Amygdala,Right-Accumbens-area,Right-VentralDC,Right-vessel,Right-choroid-plexus,5th-Ventricle,WM-hypointensities,Left-WM-hypointensities,Right-WM-hypointensities,non-WM-hypointensities,Left-non-WM-hypointensities,Right-non-WM-hypointensities,Optic-Chiasm,CC_Posterior,CC_Mid_Posterior,CC_Central,CC_Mid_Anterior,CC_Anterior,BrainSegVol,BrainSegVolNotVent,lhCortexVol,rhCortexVol,CortexVol,lhCerebralWhiteMatterVol,rhCerebralWhiteMatterVol,CerebralWhiteMatterVol,SubCortGrayVol,TotalGrayVol,SupraTentorialVol,SupraTentorialVolNotVent,MaskVol,BrainSegVol-to-eTIV,MaskVol-to-eTIV,lhSurfaceHoles,rhSurfaceHoles,SurfaceHoles,EstimatedTotalIntraCranialVol
0,I238627,002_S_0295,CN,M,2011-06-02,2.054,2.332,2.523,2.686,2.681,2.387,2.332,2.426,2.444,2.456,1.951,2.657,3.014,2.753,2.599,2.589,3.057,3.325,2.594,2.350,3.019,1.960,2.903,2.608,2.563,2.656,2.536,2.257,2.890,2.578,2.246,2.166,2.500,2.779,2.943,2.497,2.693,2.929,2.518,2.543,2.218,1.961,3.263,1.930,2.076,2.337,2.794,2.462,2.392,2.380,2.065,2.324,2.049,2.341,2.802,2.182,1.995,2.380,2.334,2.416,2.209,1.997,2.100,2.429,2.192,1.718,2.239,2.279,2.340,1.897,2.284,2.313,2.420,2.132,2.43338,1068760.0,1.687191e+06,2.080,2.619,2.443,2.717,2.296,2.415,2.609,2.582,2.795,2.575,1.861,2.653,2.669,2.684,2.537,2.655,2.824,2.967,2.536,2.436,2.730,2.072,2.952,2.548,2.442,2.615,2.486,2.088,2.841,2.564,2.231,2.177,2.308,3.022,2.943,2.639,2.604,2.839,2.215,2.393,2.276,1.987,3.159,1.997,1.968,2.400,2.498,2.332,2.381,2.534,2.254,2.183,1.851,2.214,2.008,2.147,1.941,2.005,2.319,2.307,2.264,1.691,1.951,2.443,2.250,1.672,2.141,2.416,2.153,1.979,2.264,2.166,2.329,2.102,2.37691,1068760.0,1.687191e+06,27360.1,1178.9,12982.8,56458.0,7607.5,3370.6,4515.8,2023.3,2248.8,1882.0,21885.3,3635.0,1456.5,1615.8,358.0,3965.3,58.0,1060.0,20002.7,1400.6,12186.5,53978.2,6801.5,3561.6,5156.6,2070.8,3849.7,1876.9,397.0,4242.1,62.0,735.3,0.0,3688.8,0.0,0.0,0.0,0.0,0.0,195.0,1015.8,675.3,428.8,382.5,779.7,1126213.0,1068760.0,220764.309707,218008.267247,438772.576954,219806.5,220113.5,439920.0,56727.0,605997.576954,991851.0,934398.0,1630660.0,0.667508,0.966494,10.0,8.0,18.0,1.687191e+06
1,I30118,002_S_0413,CN,F,2006-11-15,2.039,2.397,2.301,2.447,2.429,2.443,2.495,2.447,2.580,2.271,1.849,2.682,2.644,2.477,2.447,2.572,3.087,3.573,2.501,2.105,2.671,2.006,3.150,2.530,2.532,2.594,2.240,1.980,2.894,2.527,2.168,1.719,2.515,2.898,2.760,2.641,2.829,2.826,1.950,2.186,2.420,2.073,3.186,1.695,1.865,2.191,2.739,2.515,2.463,2.435,2.376,2.131,2.081,2.093,1.945,2.082,2.057,2.098,2.144,2.496,2.325,2.066,2.294,2.424,2.224,1.484,2.072,2.401,2.485,2.028,2.234,2.237,2.322,2.467,2.35354,1026466.0,1.258181e+06,2.165,2.155,2.312,2.585,2.170,2.584,2.533,2.370,2.797,2.693,1.830,2.752,2.591,2.326,2.382,2.682,3.127,3.267,2.471,2.120,2.805,1.890,3.150,2.675,2.386,2.444,2.124,1.985,2.721,2.473,2.082,1.835,2.636,2.811,2.749,2.519,2.813,2.786,2.121,1.935,2.308,1.953,3.107,1.885,1.852,2.169,2.575,2.612,2.440,2.456,2.115,2.097,2.077,2.209,2.371,1.980,1.852,2.157,1.999,2.399,2.272,2.105,2.090,2.522,2.230,1.670,1.946,2.245,2.244,2.062,2.166,2.173,2.375,2.104,2.33749,1026466.0,1.258181e+06,14558.7,1099.5,11647.2,45477.7,5892.4,3481.4,3657.4,1698.2,2387.1,1295.8,18692.0,3504.9,1798.2,1294.7,376.3,3295.5,26.3,750.5,16290.6,870.6,11603.2,43211.1,5825.0,3463.0,3915.1,1615.9,3564.4,2099.9,512.8,3313.6,17.8,686.6,0.0,3338.5,0.0,0.0,0.0,0.0,0.0,115.1,900.2,347.3,397.7,397.6,813.6,1065429.0,1026466.0,221586.592272,222805.532434,444392.124706,213541.5,210605.5,424147.0,48806.0,581127.124706,955222.0,916259.0,1555808.0,0.846801,1.236554,19.0,10.0,29.0,1.258181e+06
2,I32917,002_S_0559,CN,M,2006-12-12,2.136,2.265,2.115,2.496,2.160,2.342,2.250,2.351,2.789,2.896,1.658,2.386,2.565,2.371,2.283,2.308,3.194,3.651,2.337,1.971,2.932,1.927,2.756,2.337,2.299,2.413,2.064,1.961,2.449,2.211,2.248,2.387,2.408,2.613,2.635,2.451,2.631,2.766,2.042,2.018,2.046,1.847,2.884,1.741,1.909,1.906,2.509,2.605,2.176,2.446,2.013,2.079,2.083,2.163,2.414,2.029,1.733,2.088,2.143,2.378,2.197,1.957,1.999,2.452,2.049,1.545,1.955,2.097,2.068,1.706,2.313,2.345,2.273,2.576,2.24001,1094955.0,1.653836e+06,2.446,2.118,2.154,2.432,2.347,2.553,2.482,2.390,2.986,3.037,1.726,2.498,2.348,2.294,2.459,2.524,3.153,3.389,2.247,1.942,2.691,1.982,2.816,2.374,2.468,2.390,2.039,1.960,2.435,2.225,2.174,2.491,2.413,2.649,2.604,2.169,2.693,2.826,2.000,2.297,2.037,1.852,2.895,1.644,1.924,1.979,2.209,2.537,2.372,2.634,1.948,1.999,2.088,2.139,1.927,1.936,1.755,2.039,2.063,2.323,2.082,2.037,2.206,2.493,2.052,1.605,1.831,2.113,2.128,2.020,2.098,2.281,2.264,2.070,2.24741,1094955.0,1.653836e+06,17154.4,1449.3,13793.1,48930.5,6880.7,3216.6,4888.5,1784.2,2703.8,3248.5,24107.6,3834.5,2119.1,1220.0,645.0,4310.6,65.6,1379.0,17225.0,1332.3,14272.8,49841.2,6877.5,3476.8,4892.5,1741.3,3759.5,2182.6,673.5,4374.6,84.6,1267.8,0.0,3781.3,0.0,0.0,0.0,0.0,0.0,239.1,1064.1,440.9,427.4,467.2,981.8,1141382.0,1094955.0,223461.708807,223551.153366,447012.862172,234941.0,231666.0,466607.0,57364.0,602896.862172,1016460.0,970033.0,1665330.0,0.690142,1.006950,15.0,27.0,42.0,1.653836e+06
3,I243898,002_S_0685,CN,F,2011-07-08,2.257,2.206,2.252,2.674,2.345,2.560,2.445,2.253,2.824,2.377,1.801,2.726,2.683,2.665,2.534,2.821,2.873,3.448,2.372,1.998,2.633,1.958,3.002,2.446,2.318,2.620,2.249,2.133,2.631,2.399,2.364,2.041,2.335,2.798,3.197,2.291,2.940,2.695,2.068,2.134,2.013,1.881,3.280,1.624,1.827,2.053,2.809,2.400,2.293,2.209,1.811,2.132,1.971,2.217,2.463,1.981,1.717,1.854,2.017,2.248,2.292,1.989,2.070,2.527,2.061,1.687,2.059,2.253,2.223,2.067,2.256,2.223,2.335,2.309,2.31815,971146.0,1.529247e+06,2.448,2.189,2.048,2.676,2.666,2.550,2.348,2.403,2.831,2.867,1.815,2.772,2.556,2.423,2.564,2.718,3.339,2.935,2.479,2.148,2.860,2.202,3.050,2.489,2.414,2.538,2.309,2.045,2.712,2.286,2.393,1.982,2.388,2.861,2.887,2.163,2.545,3.000,2.067,2.438,2.015,1.792,3.328,1.677,1.740,2.018,2.424,2.051,2.251,2.511,1.850,2.188,2.243,2.347,2.222,2.091,1.667,1.903,2.158,2.600,2.284,2.083,1.845,2.587,1.956,1.516,1.948,2.291,2.165,2.060,2.397,2.293,2.404,2.238,2.32661,971146.0,1.529247e+06,21146.6,810.6,16337.0,48130.8,6495.4,3652.2,4515.6,2174.3,3458.0,1784.3,19327.9,3712.0,1514.2,1387.3,202.2,4061.9,44.8,1188.7,19915.3,1349.1,15265.4,48578.6,6290.3,3584.7,4386.3,1919.7,3618.1,1558.0,306.6,4306.5,46.6,1050.0,0.0,28059.3,0.0,0.0,0.0,0.0,0.0,232.6,999.3,395.9,426.1,447.1,1053.7,1023086.0,971146.0,194476.488107,197524.513221,392001.001328,199412.0,199001.0,398413.0,53921.0,543644.001328,895554.0,843614.0,1483210.0,0.669013,0.969896,21.0,27.0,48.0,1.529247e+06
4,I20087,002_S_0729,MCI,F,2006-08-02,2.082,2.161,2.377,2.332,2.323,2.386,2.566,2.271,2.719,2.773,1.866,2.487,2.916,2.477,2.355,2.597,2.818,2.925,2.309,2.024,2.938,2.118,2.365,2.568,2.227,2.375,2.171,2.037,2.694,2.252,2.258,2.026,2.353,2.811,2.562,2.460,2.826,2.867,2.662,1.990,2.078,2.066,3.180,1.723,1.876,2.052,2.870,2.323,2.389,2.708,1.760,2.081,1.964,2.246,1.790,1.816,1.649,1.860,2.016,2.242,2.380,1.774,2.293,2.589,2.046,2.033,1.987,2.269,2.159,2.269,2.104,2.305,2.309,2.357,2.30455,867482.0,1.233198e+06,2.225,2.310,2.142,2.369,2.186,2.810,2.496,2.504,2.642,2.714,1.813,2.515,2.279,2.428,2.421,2.653,2.986,2.850,2.233,1.940,2.610,2.204,2.813,2.464,2.290,2.508,2.155,1.957,2.621,2.090,2.189,2.287,2.363,2.647,2.998,2.179,2.570,2.728,2.354,2.056,2.150,1.965,3.182,1.761,1.758,1.994,2.463,2.288,2.368,2.387,1.716,2.102,2.055,2.356,2.265,1.998,1.997,1.837,2.051,2.296,2.541,1.981,2.469,2.588,2.044,2.259,1.898,2.333,2.244,1.969,2.211,2.278,2.259,2.276,2.30884,867482.0,1.233198e+06,9179.7,450.1,10207.5,44542.4,5672.4,3131.0,4306.8,1746.0,1092.2,1894.9,17589.6,3098.6,1216.3,1042.3,413.3,3188.2,34.6,526.5,8244.5,650.3,10287.7,43681.4,5599.9,3269.4,4397.7,1674.8,3074.2,1280.8,459.6,2950.9,13.1,645.2,0.0,3264.7,0.0,0.0,0.0,0.0,0.0,130.9,983.5,501.0,402.8,492.4,777.2,890656.0,867482.0,177531.325728,181201.045099,358732.370827,174681.0,180828.0,355509.0,47011.0,493467.370827,783437.0,760263.0,1238517.0,0.722233,1.004313,11.0,10.0,21.0,1.233198e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1227,I294080,941_S_4420,EMCI,M,2012-03-28,2.332,2.229,2.345,2.451,2.531,2.302,2.190,2.265,2.692,2.569,1.761,2.582,2.723,2.369,2.286,2.469,2.797,3.038,2.151,2.070,2.577,1.828,3.011,2.436,2.325,2.412,2.207,2.101,2.485,2.413,2.438,1.915,2.256,2.670,3.225,2.394,2.580,2.618,2.185,2.022,2.170,1.980,2.879,1.915,2.106,2.187,2.769,2.361,2.266,2.232,2.093,2.019,1.969,2.186,2.027,2.075,1.906,1.973,2.081,2.332,2.225,1.816,2.235,2.269,2.081,1.699,1.947,2.084,2.201,2.037,2.175,2.410,2.268,2.113,2.28337,1100576.0,1.648887e+06,2.434,2.350,2.365,2.237,2.611,2.323,2.312,2.464,2.892,2.323,1.860,2.403,2.478,2.565,2.524,2.550,2.675,3.090,2.377,2.181,2.582,1.838,2.901,2.842,2.237,2.449,2.179,1.959,2.449,2.368,2.366,2.215,1.980,2.597,2.839,2.506,2.685,2.549,2.321,2.194,2.207,1.950,3.019,1.834,1.912,2.263,2.225,2.536,2.255,2.485,1.622,2.035,2.125,2.150,1.996,2.101,2.143,2.022,1.920,2.496,2.214,1.933,2.026,2.249,2.059,1.711,1.921,2.213,2.151,1.963,2.286,2.358,2.192,1.953,2.28994,1100576.0,1.648887e+06,24503.3,1336.9,13205.3,45606.3,6462.9,3282.8,5460.2,2210.1,1233.9,1644.7,19837.5,4001.6,1578.5,1404.5,479.3,3465.2,43.4,895.4,18998.0,1198.9,11779.5,49655.3,6514.8,3264.4,5283.6,2143.3,3840.6,1754.2,454.6,4015.8,11.0,853.0,0.0,4082.3,0.0,0.0,0.0,0.0,0.0,220.4,1052.9,455.3,458.2,472.6,823.0,1152910.0,1100576.0,223514.607970,221264.415778,444779.023748,241302.5,240529.5,481832.0,55605.0,595822.023748,1033263.0,980929.0,1684850.0,0.699205,1.021811,42.0,23.0,65.0,1.648887e+06
1228,I307653,941_S_4764,EMCI,F,2012-06-01,2.390,2.273,2.346,2.420,2.560,2.423,2.193,2.340,2.620,2.284,1.867,2.409,2.473,2.353,2.470,2.494,2.886,3.318,2.540,1.928,2.819,2.018,2.900,2.443,2.403,2.395,2.057,2.039,2.633,2.328,2.364,1.978,2.267,2.685,2.939,2.230,2.713,2.751,1.664,2.091,2.081,2.010,3.126,1.696,1.996,2.088,2.728,2.426,2.282,2.168,1.991,1.962,2.003,2.242,1.893,1.934,1.774,1.985,2.226,2.244,2.270,1.843,2.192,2.334,2.008,1.596,1.984,2.116,2.324,2.198,2.001,2.259,2.210,2.497,2.26628,911773.0,1.501232e+06,2.523,2.611,2.383,2.121,2.648,2.524,2.543,2.352,2.707,2.605,1.906,2.493,2.940,2.733,2.658,2.586,2.491,3.134,2.412,2.011,2.711,2.277,2.860,2.944,2.414,2.517,2.241,1.938,2.685,2.283,2.629,1.989,2.206,2.622,2.719,2.370,2.750,2.748,2.105,2.356,2.176,1.983,3.210,1.803,1.923,2.001,2.975,2.294,2.519,2.252,2.116,2.091,2.121,2.311,1.936,1.960,1.893,2.018,2.140,2.266,2.302,2.245,2.279,2.623,2.064,1.939,2.046,2.154,2.174,2.739,2.230,2.161,2.207,2.146,2.34057,911773.0,1.501232e+06,23552.1,1472.5,13205.7,52898.2,6019.8,2553.3,3522.6,1633.9,3309.5,2767.2,20808.8,3386.3,1414.1,1622.3,386.9,3859.5,65.1,900.1,32670.7,1682.8,13771.9,54908.0,6127.5,2597.7,3331.7,1801.1,3293.6,1649.8,319.5,3550.1,7.0,757.9,0.0,8845.7,0.0,0.0,0.0,0.0,0.0,181.0,874.4,292.2,299.1,267.4,654.6,980431.0,911773.0,195101.782272,201573.914802,396675.697074,166665.5,169401.5,336067.0,46648.0,551220.697074,847073.0,778415.0,1509139.0,0.653084,1.005267,25.0,31.0,56.0,1.501232e+06
1229,I366196,941_S_5124,SMC,F,2013-04-09,2.377,2.142,2.325,2.660,2.447,2.544,2.191,1.712,1.542,1.576,1.980,2.737,2.718,2.496,2.609,2.689,3.148,3.627,2.531,2.169,2.891,1.984,2.395,2.565,2.690,2.784,2.558,2.463,2.762,2.263,2.660,1.644,2.902,2.896,3.558,2.525,2.861,2.816,2.538,2.195,2.298,1.909,3.185,1.781,1.998,2.280,2.492,2.832,2.515,3.162,2.055,2.334,2.302,2.459,2.595,2.324,2.053,2.270,2.312,2.287,2.426,2.074,2.178,2.649,2.173,1.246,2.227,2.546,2.497,2.160,2.209,2.261,2.414,2.413,2.33439,933149.0,1.520806e+06,2.385,2.277,2.337,2.504,2.561,2.457,2.025,1.188,1.013,2.096,1.871,2.571,2.478,2.561,2.686,2.577,2.959,3.643,2.476,2.117,2.560,2.443,2.600,2.658,2.672,2.542,2.251,2.310,2.581,2.064,2.556,2.175,2.616,2.840,2.930,2.431,2.667,2.688,2.048,2.582,2.360,2.218,3.419,1.859,1.802,1.662,3.108,2.695,2.512,2.856,2.600,2.129,2.146,2.441,2.216,2.281,2.231,2.121,2.210,2.218,2.612,2.016,2.447,2.655,1.776,1.600,2.151,2.241,2.278,1.978,1.189,2.437,2.467,2.317,2.31796,933149.0,1.520806e+06,15774.6,835.7,14415.6,41087.8,3160.2,2126.6,2959.6,1256.1,1059.2,1072.4,15940.5,1928.6,1216.1,224.7,160.6,1696.5,11.0,117.5,11582.5,1373.1,12932.4,42162.7,3042.4,2089.6,3344.5,1496.6,1974.6,1302.7,232.0,2320.1,17.7,88.4,0.0,4685.5,0.0,0.0,0.0,0.0,0.0,44.8,70.0,62.8,287.2,486.0,580.0,965281.0,933149.0,214017.595793,207683.916890,421701.512683,194013.5,181019.5,375033.0,31013.0,535903.512683,855049.0,822917.0,1450459.0,0.634717,0.953743,17.0,33.0,50.0,1.520806e+06
1230,I374433,941_S_5193,SMC,F,2013-05-29,2.233,2.372,2.277,2.437,2.440,2.537,2.444,2.293,2.596,2.273,1.737,2.545,2.637,2.539,2.561,2.562,2.702,2.664,2.462,2.089,2.605,1.852,3.074,2.465,2.385,2.498,2.267,2.186,2.740,2.396,2.288,2.117,2.395,2.894,3.345,2.396,2.635,2.690,1.981,2.146,2.066,2.054,3.163,1.706,1.840,2.064,2.458,2.330,2.306,2.421,1.830,2.184,2.224,2.339,2.102,1.976,2.049,1.946,2.340,2.012,2.240,2.203,2.051,2.622,2.016,1.487,2.129,2.369,2.503,2.085,2.191,2.356,2.375,2.208,2.32227,1017137.0,1.367454e+06,2.299,2.199,2.264,2.449,2.700,2.305,2.391,2.279,2.382,2.301,1.755,2.351,2.461,2.555,2.844,2.626,2.937,2.563,2.578,2.026,2.671,1.886,3.210,2.646,2.525,2.531,2.225,1.877,2.454,2.401,2.323,2.447,2.086,2.917,2.730,2.305,2.629,2.798,2.167,2.087,2.234,1.838,3.088,1.787,1.784,2.284,2.232,2.263,2.369,2.275,1.679,2.171,2.526,2.411,2.140,2.052,2.003,1.997,2.240,2.454,2.333,2.220,2.043,2.476,2.226,1.536,2.099,2.156,2.381,1.807,2.392,2.408,2.351,2.178,2.33072,1017137.0,1.367454e+06,12788.8,388.4,12548.6,47130.1,5894.3,3109.8,4425.3,1931.6,1306.7,1252.7,19755.9,3663.3,1568.4,962.6,480.0,3804.3,23.5,791.0,11274.6,420.8,11568.4,50026.7,5740.0,3233.2,4155.6,1796.1,3586.4,1764.7,477.1,3671.2,15.1,768.3,0.0,2362.3,0.0,0.0,0.0,0.0,0.0,174.5,1041.9,479.0,515.1,498.5,1124.3,1046666.0,1017137.0,207175.025399,205344.094770,412519.120168,217404.5,218285.5,435690.0,50541.0,560301.120168,926001.0,896472.0,1494506.0,0.765412,1.092912,17.0,20.0,37.0,1.367454e+06

In [7]:
adni_merge_df = pd.read_csv('/project_cephfs/3022017.06/ADNI/phenotypes/ADNIMERGE_02May2025.csv')
adni_merge_df = adni_merge_df.rename(columns={"PTID":"participant_id", "EXAMDATE":"Acq Date","SITE":"Site","AGE":"Age", "PTGENDER":"Sex"})
adni_merge_df = adni_merge_df.replace({'Female': 'F', 'Male': 'M'})
adni_merge_df = adni_merge_df[["participant_id","Site","Age"]]


asl_adni_merge = adni_merge_df.merge(merged_data, on=['participant_id'], how='right')
asl_adni_merge = asl_adni_merge.drop_duplicates(subset="participant_id", keep="first")
asl_adni_merge = asl_adni_merge.reset_index(drop=True)
asl_adni_merge = asl_adni_merge.dropna()
asl_adni_merge = asl_adni_merge.drop(columns=['scan_id','Acq Date'])
asl_adni_merge = asl_adni_merge.rename(columns={"Site_x":"Site"})
asl_adni_merge

/scratch/quirom/slurm_job_51477071/ipykernel_2924982/2047546291.py:1: DtypeWarning: Columns (19,20,21,50,51,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  adni_merge_df = pd.read_csv('/project_cephfs/3022017.06/ADNI/phenotypes/ADNIMERGE_02May2025.csv')

,participant_id,Site,Age,Group,Sex,lh_G_and_S_frontomargin_thickness,lh_G_and_S_occipital_inf_thickness,lh_G_and_S_paracentral_thickness,lh_G_and_S_subcentral_thickness,lh_G_and_S_transv_frontopol_thickness,lh_G_and_S_cingul-Ant_thickness,lh_G_and_S_cingul-Mid-Ant_thickness,lh_G_and_S_cingul-Mid-Post_thickness,lh_G_cingul-Post-dorsal_thickness,lh_G_cingul-Post-ventral_thickness,lh_G_cuneus_thickness,lh_G_front_inf-Opercular_thickness,lh_G_front_inf-Orbital_thickness,lh_G_front_inf-Triangul_thickness,lh_G_front_middle_thickness,lh_G_front_sup_thickness,lh_G_Ins_lg_and_S_cent_ins_thickness,lh_G_insular_short_thickness,lh_G_occipital_middle_thickness,lh_G_occipital_sup_thickness,lh_G_oc-temp_lat-fusifor_thickness,lh_G_oc-temp_med-Lingual_thickness,lh_G_oc-temp_med-Parahip_thickness,lh_G_orbital_thickness,lh_G_pariet_inf-Angular_thickness,lh_G_pariet_inf-Supramar_thickness,lh_G_parietal_sup_thickness,lh_G_postcentral_thickness,lh_G_precentral_thickness,lh_G_precuneus_thickness,lh_G_rectus_thickness,lh_G_subcallosal_thickness,lh_G_temp_sup-G_T_transv_thickness,lh_G_temp_sup-Lateral_thickness,lh_G_temp_sup-Plan_polar_thickness,lh_G_temp_sup-Plan_tempo_thickness,lh_G_temporal_inf_thickness,lh_G_temporal_middle_thickness,lh_Lat_Fis-ant-Horizont_thickness,lh_Lat_Fis-ant-Vertical_thickness,lh_Lat_Fis-post_thickness,lh_Pole_occipital_thickness,lh_Pole_temporal_thickness,lh_S_calcarine_thickness,lh_S_central_thickness,lh_S_cingul-Marginalis_thickness,lh_S_circular_insula_ant_thickness,lh_S_circular_insula_inf_thickness,lh_S_circular_insula_sup_thickness,lh_S_collat_transv_ant_thickness,lh_S_collat_transv_post_thickness,lh_S_front_inf_thickness,lh_S_front_middle_thickness,lh_S_front_sup_thickness,lh_S_interm_prim-Jensen_thickness,lh_S_intrapariet_and_P_trans_thickness,lh_S_oc_middle_and_Lunatus_thickness,lh_S_oc_sup_and_transversal_thickness,lh_S_occipital_ant_thickness,lh_S_oc-temp_lat_thickness,lh_S_oc-temp_med_and_Lingual_thickness,lh_S_orbital_lateral_thickness,lh_S_orbital_med-olfact_thickness,lh_S_orbital-H_Shaped_thickness,lh_S_parieto_occipital_thickness,lh_S_pericallosal_thickness,lh_S_postcentral_thickness,lh_S_precentral-inf-part_thickness,lh_S_precentral-sup-part_thickness,lh_S_suborbital_thickness,lh_S_subparietal_thickness,lh_S_temporal_inf_thickness,lh_S_temporal_sup_thickness,lh_S_temporal_transverse_thickness,lh_MeanThickness_thickness,BrainSegVolNotVent_x,eTIV_x,rh_G_and_S_frontomargin_thickness,rh_G_and_S_occipital_inf_thickness,rh_G_and_S_paracentral_thickness,rh_G_and_S_subcentral_thickness,rh_G_and_S_transv_frontopol_thickness,rh_G_and_S_cingul-Ant_thickness,rh_G_and_S_cingul-Mid-Ant_thickness,rh_G_and_S_cingul-Mid-Post_thickness,rh_G_cingul-Post-dorsal_thickness,rh_G_cingul-Post-ventral_thickness,rh_G_cuneus_thickness,rh_G_front_inf-Opercular_thickness,rh_G_front_inf-Orbital_thickness,rh_G_front_inf-Triangul_thickness,rh_G_front_middle_thickness,rh_G_front_sup_thickness,rh_G_Ins_lg_and_S_cent_ins_thickness,rh_G_insular_short_thickness,rh_G_occipital_middle_thickness,rh_G_occipital_sup_thickness,rh_G_oc-temp_lat-fusifor_thickness,rh_G_oc-temp_med-Lingual_thickness,rh_G_oc-temp_med-Parahip_thickness,rh_G_orbital_thickness,rh_G_pariet_inf-Angular_thickness,rh_G_pariet_inf-Supramar_thickness,rh_G_parietal_sup_thickness,rh_G_postcentral_thickness,rh_G_precentral_thickness,rh_G_precuneus_thickness,rh_G_rectus_thickness,rh_G_subcallosal_thickness,rh_G_temp_sup-G_T_transv_thickness,rh_G_temp_sup-Lateral_thickness,rh_G_temp_sup-Plan_polar_thickness,rh_G_temp_sup-Plan_tempo_thickness,rh_G_temporal_inf_thickness,rh_G_temporal_middle_thickness,rh_Lat_Fis-ant-Horizont_thickness,rh_Lat_Fis-ant-Vertical_thickness,rh_Lat_Fis-post_thickness,rh_Pole_occipital_thickness,rh_Pole_temporal_thickness,rh_S_calcarine_thickness,rh_S_central_thickness,rh_S_cingul-Marginalis_thickness,rh_S_circular_insula_ant_thickness,rh_S_circular_insula_inf_thickness,rh_S_circular_insula_sup_thickness,rh_S_collat_transv_ant_thickness,rh_S_collat_transv_post_thickness,rh_S_front_inf_thickness,rh_S_front_middle_thickness,rh_S_front_sup_thickness,rh_S_interm_prim-Jensen_thickness,rh_S_intrapariet_and_P_trans_thickness,rh_S_oc_middle_and_Lunatus_thickness,rh_S_oc_sup_and_transversal_thickness,rh_S_occipital_ant_thickness,rh_S_oc-temp_lat_thickness,rh_S_oc-temp_med_and_Lingual_thickness,rh_S_orbital_lateral_thickness,rh_S_orbital_med-olfact_thickness,rh_S_orbital-H_Shaped_thickness,rh_S_parieto_occipital_thickness,rh_S_pericallosal_thickness,rh_S_postcentral_thickness,rh_S_precentral-inf-part_thickness,rh_S_precentral-sup-part_thickness,rh_S_suborbital_thickness,rh_S_subparietal_thickness,rh_S_temporal_inf_thickness,rh_S_temporal_sup_thickness,rh_S_temporal_transverse_thickness,rh_MeanThickness_thickness,BrainSegVolNotVent_y,eTIV_y,Left-Lateral-Ventricle,Left-Inf-Lat-Vent,Left-Cerebellum-White-Matter,Left-Cerebellum-Cortex,Left-Thalamus,Left-Caudate,Left-Putamen,Left-Pallidum,3rd-Ventricle,4th-Ventricle,Brain-Stem,Left-Hippocampus,Left-Amygdala,CSF,Left-Accumbens-area,Left-VentralDC,Left-vessel,Left-choroid-plexus,Right-Lateral-Ventricle,Right-Inf-Lat-Vent,Right-Cerebellum-White-Matter,Right-Cerebellum-Cortex,Right-Thalamus,Right-Caudate,Right-Putamen,Right-Pallidum,Right-Hippocampus,Right-Amygdala,Right-Accumbens-area,Right-VentralDC,Right-vessel,Right-choroid-plexus,5th-Ventricle,WM-hypointensities,Left-WM-hypointensities,Right-WM-hypointensities,non-WM-hypointensities,Left-non-WM-hypointensities,Right-non-WM-hypointensities,Optic-Chiasm,CC_Posterior,CC_Mid_Posterior,CC_Central,CC_Mid_Anterior,CC_Anterior,BrainSegVol,BrainSegVolNotVent,lhCortexVol,rhCortexVol,CortexVol,lhCerebralWhiteMatterVol,rhCerebralWhiteMatterVol,CerebralWhiteMatterVol,SubCortGrayVol,TotalGrayVol,SupraTentorialVol,SupraTentorialVolNotVent,MaskVol,BrainSegVol-to-eTIV,MaskVol-to-eTIV,lhSurfaceHoles,rhSurfaceHoles,SurfaceHoles,EstimatedTotalIntraCranialVol
0,002_S_0295,2.0,84.8,CN,M,2.054,2.332,2.523,2.686,2.681,2.387,2.332,2.426,2.444,2.456,1.951,2.657,3.014,2.753,2.599,2.589,3.057,3.325,2.594,2.350,3.019,1.960,2.903,2.608,2.563,2.656,2.536,2.257,2.890,2.578,2.246,2.166,2.500,2.779,2.943,2.497,2.693,2.929,2.518,2.543,2.218,1.961,3.263,1.930,2.076,2.337,2.794,2.462,2.392,2.380,2.065,2.324,2.049,2.341,2.802,2.182,1.995,2.380,2.334,2.416,2.209,1.997,2.100,2.429,2.192,1.718,2.239,2.279,2.340,1.897,2.284,2.313,2.420,2.132,2.43338,1068760.0,1.687191e+06,2.080,2.619,2.443,2.717,2.296,2.415,2.609,2.582,2.795,2.575,1.861,2.653,2.669,2.684,2.537,2.655,2.824,2.967,2.536,2.436,2.730,2.072,2.952,2.548,2.442,2.615,2.486,2.088,2.841,2.564,2.231,2.177,2.308,3.022,2.943,2.639,2.604,2.839,2.215,2.393,2.276,1.987,3.159,1.997,1.968,2.400,2.498,2.332,2.381,2.534,2.254,2.183,1.851,2.214,2.008,2.147,1.941,2.005,2.319,2.307,2.264,1.691,1.951,2.443,2.250,1.672,2.141,2.416,2.153,1.979,2.264,2.166,2.329,2.102,2.37691,1068760.0,1.687191e+06,27360.1,1178.9,12982.8,56458.0,7607.5,3370.6,4515.8,2023.3,2248.8,1882.0,21885.3,3635.0,1456.5,1615.8,358.0,3965.3,58.0,1060.0,20002.7,1400.6,12186.5,53978.2,6801.5,3561.6,5156.6,2070.8,3849.7,1876.9,397.0,4242.1,62.0,735.3,0.0,3688.8,0.0,0.0,0.0,0.0,0.0,195.0,1015.8,675.3,428.8,382.5,779.7,1126213.0,1068760.0,220764.309707,218008.267247,438772.576954,219806.5,220113.5,439920.0,56727.0,605997.576954,991851.0,934398.0,1630660.0,0.667508,0.966494,10.0,8.0,18.0,1.687191e+06
1,002_S_0413,2.0,76.3,CN,F,2.039,2.397,2.301,2.447,2.429,2.443,2.495,2.447,2.580,2.271,1.849,2.682,2.644,2.477,2.447,2.572,3.087,3.573,2.501,2.105,2.671,2.006,3.150,2.530,2.532,2.594,2.240,1.980,2.894,2.527,2.168,1.719,2.515,2.898,2.760,2.641,2.829,2.826,1.950,2.186,2.420,2.073,3.186,1.695,1.865,2.191,2.739,2.515,2.463,2.435,2.376,2.131,2.081,2.093,1.945,2.082,2.057,2.098,2.144,2.496,2.325,2.066,2.294,2.424,2.224,1.484,2.072,2.401,2.485,2.028,2.234,2.237,2.322,2.467,2.35354,1026466.0,1.258181e+06,2.165,2.155,2.312,2.585,2.170,2.584,2.533,2.370,2.797,2.693,1.830,2.752,2.591,2.326,2.382,2.682,3.127,3.267,2.471,2.120,2.805,1.890,3.150,2.675,2.386,2.444,2.124,1.985,2.721,2.473,2.082,1.835,2.636,2.811,2.749,2.519,2.813,2.786,2.121,1.935,2.308,1.953,3.107,1.885,1.852,2.169,2.575,2.612,2.440,2.456,2.115,2.097,2.077,2.209,2.371,1.980,1.852,2.157,1.999,2.399,2.272,2.105,2.090,2.522,2.230,1.670,1.946,2.245,2.244,2.062,2.166,2.173,2.375,2.104,2.33749,1026466.0,1.258181e+06,14558.7,1099.5,11647.2,45477.7,5892.4,3481.4,3657.4,1698.2,2387.1,1295.8,18692.0,3504.9,1798.2,1294.7,376.3,3295.5,26.3,750.5,16290.6,870.6,11603.2,43211.1,5825.0,3463.0,3915.1,1615.9,3564.4,2099.9,512.8,3313.6,17.8,686.6,0.0,3338.5,0.0,0.0,0.0,0.0,0.0,115.1,900.2,347.3,397.7,397.6,813.6,1065429.0,1026466.0,221586.592272,222805.532434,444392.124706,213541.5,210605.5,424147.0,48806.0,581127.124706,955222.0,916259.0,1555808.0,0.846801,1.236554,19.0,10.0,29.0,1.258181e+06
2,002_S_0559,2.0,79.3,CN,M,2.136,2.265,2.115,2.496,2.160,2.342,2.250,2.351,2.789,2.896,1.658,2.386,2.565,2.371,2.283,2.308,3.194,3.651,2.337,1.971,2.932,1.927,2.756,2.337,2.299,2.413,2.064,1.961,2.449,2.211,2.248,2.387,2.408,2.613,2.635,2.451,2.631,2.766,2.042,2.018,2.046,1.847,2.884,1.741,1.909,1.906,2.509,2.605,2.176,2.446,2.013,2.079,2.083,2.163,2.414,2.029,1.733,2.088,2.143,2.378,2.197,1.957,1.999,2.452,2.049,1.545,1.955,2.097,2.068,1.706,2.313,2.345,2.273,2.576,2.24001,1094955.0,1.653836e+06,2.446,2.118,2.154,2.432,2.347,2.553,2.482,2.390,2.986,3.037,1.726,2.498,2.348,2.294,2.459,2.524,3.153,3.389,2.247,1.942,2.691,1.982,2.816,2.374,2.468,2.390,2.039,1.960,2.435,2.225,2.174,2.491,2.413,2.649,2.604,2.169,2.693,2.826,2.000,2.297,2.037,1.852,2.895,1.644,1.924,1.979,2.209,2.537,2.372,2.634,1.948,1.999,2.088,2.139,1.927,1.936,1.755,2.039,2.063,2.323,2.082,2.037,2.206,2.493,2.052,1.605,1.831,2.113,2.128,2.020,2.098,2.281,2.264,2.070,2.24741,1094955.0,1.653836e+06,17154.4,1449.3,13793.1,48930.5,6880.7,3216.6,4888.5,1784.2,2703.8,3248.5,24107.6,3834.5,2119.1,1220.0,645.0,4310.6,65.6,1379.0,17225.0,1332.3,14272.8,49841.2,6877.5,3476.8,4892.5,1741.3,3759.5,2182.6,673.5,4374.6,84.6,1267.8,0.0,3781.3,0.0,0.0,0.0,0.0,0.0,239.1,1064.1,440.9,427.4,467.2,981.8,1141382.0,1094955.0,223461.708807,223551.153366,447012.862172,234941.0,231666.0,466607.0,57364.0,602896.862172,1016460.0,970033.0,1665330.0,0.690142,1.006950,15.0,27.0,42.0,1.653836e+06
3,002_S_0685,2.0,89.6,CN,F,2.257,2.206,2.252,2.674,2.345,2.560,2.445,2.253,2.824,2.377,1.801,2.726,2.683,2.665,2.534,2.821,2.873,3.448,2.372,1.998,2.633,1.958,3.002,2.446,2.318,2.620,2.249,2.133,2.631,2.399,2.364,2.041,2.335,2.798,3.197,2.291,2.940,2.695,2.068,2.134,2.013,1.881,3.280,1.624,1.827,2.053,2.809,2.400,2.293,2.209,1.811,2.132,1.971,2.217,2.463,1.981,1.717,1.854,2.017,2.248,2.292,1.989,2.070,2.527,2.061,1.687,2.059,2.253,2.223,2.067,2.256,2.223,2.335,2.309,2.31815,971146.0,1.529247e+06,2.448,2.189,2.048,2.676,2.666,2.550,2.348,2.403,2.831,2.867,1.815,2.772,2.556,2.423,2.564,2.718,3.339,2.935,2.479,2.148,2.860,2.202,3.050,2.489,2.414,2.538,2.309,2.045,2.712,2.286,2.393,1.982,2.388,2.861,2.887,2.163,2.545,3.000,2.067,2.438,2.015,1.792,3.328,1.677,1.740,2.018,2.424,2.051,2.251,2.511,1.850,2.188,2.243,2.347,2.222,2.091,1.667,1.903,2.158,2.600,2.284,2.083,1.845,2.587,1.956,1.516,1.948,2.291,2.165,2.060,2.397,2.293,2.404,2.238,2.32661,971146.0,1.529247e+06,21146.6,810.6,16337.0,48130.8,6495.4,3652.2,4515.6,2174.3,3458.0,1784.3,19327.9,3712.0,1514.2,1387.3,202.2,4061.9,44.8,1188.7,19915.3,1349.1,15265.4,48578.6,6290.3,3584.7,4386.3,1919.7,3618.1,1558.0,306.6,4306.5,46.6,1050.0,0.0,28059.3,0.0,0.0,0.0,0.0,0.0,232.6,999.3,395.9,426.1,447.1,1053.7,1023086.0,971146.0,194476.488107,197524.513221,392001.001328,199412.0,199001.0,398413.0,53921.0,543644.001328,895554.0,843614.0,1483210.0,0.669013,0.969896,21.0,27.0,48.0,1.529247e+06
4,002_S_0729,2.0,65.1,MCI,F,2.082,2.161,2.377,2.332,2.323,2.386,2.566,2.271,2.719,2.773,1.866,2.487,2.916,2.477,2.355,2.597,2.818,2.925,2.309,2.024,2.938,2.118,2.365,2.568,2.227,2.375,2.171,2.037,2.694,2.252,2.258,2.026,2.353,2.811,2.562,2.460,2.826,2.867,2.662,1.990,2.078,2.066,3.180,1.723,1.876,2.052,2.870,2.323,2.389,2.708,1.760,2.081,1.964,2.246,1.790,1.816,1.649,1.860,2.016,2.242,2.380,1.774,2.293,2.589,2.046,2.033,1.987,2.269,2.159,2.269,2.104,2.305,2.309,2.357,2.30455,867482.0,1.233198e+06,2.225,2.310,2.142,2.369,2.186,2.810,2.496,2.504,2.642,2.714,1.813,2.515,2.279,2.428,2.421,2.653,2.986,2.850,2.233,1.940,2.610,2.204,2.813,2.464,2.290,2.508,2.155,1.957,2.621,2.090,2.189,2.287,2.363,2.647,2.998,2.179,2.570,2.728,2.354,2.056,2.150,1.965,3.182,1.761,1.758,1.994,2.463,2.288,2.368,2.387,1.716,2.102,2.055,2.356,2.265,1.998,1.997,1.837,2.051,2.296,2.541,1.981,2.469,2.588,2.044,2.259,1.898,2.333,2.244,1.969,2.211,2.278,2.259,2.276,2.30884,867482.0,1.233198e+06,9179.7,450.1,10207.5,44542.4,5672.4,3131.0,4306.8,1746.0,1092.2,1894.9,17589.6,3098.6,1216.3,1042.3,413.3,3188.2,34.6,526.5,8244.5,650.3,10287.7,43681.4,5599.9,3269.4,4397.7,1674.8,3074.2,1280.8,459.6,2950.9,13.1,645.2,0.0,3264.7,0.0,0.0,0.0,0.0,0.0,130.9,983.5,501.0,402.8,492.4,777.2,890656.0,867482.0,177531.325728,181201.045099,358732.370827,174681.0,180828.0,355509.0,47011.0,493467.370827,783437.0,760263.0,1238517.0,0.722233,1.004313,11.0,10.0,21.0,1.233198e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1226,941_S_4377,941.0,69.3,LMCI,F,2.537,2.745,2.414,2.543,2.610,2.844,2.546,2.443,2.901,3.052,2.025,2.691,2.768,2.832,2.807,3.000,3.537,3.518,2.734,2.049,2.731,2.241,3.243,2.889,2.614,2.653,2.433,2.244,2.677,2.558,2.669,2.080,2.197,2.782,2.910,2.693,3.305,2.949,2.426,2.266,2.426,2.178,3.525,1.933,2.054,2.157,2.705,2.658,2.341,3.628,2.022,2.365,2.337,2.466,2.166,2.082,2.162,2.200,2.353,2.537,2.440,2.097,2.417,2.695,2.240,1.805,2.226,2.625,2.310,2.955,2.338,2.478,2.329,2.386,2.52556,834957.0,1.291679e+06,2.621,2.636,2.417,2.602,2.780,2.899,2.744,2.635,3.198,2.793,2.075,2.720,2.400,2.834,2.769,2.889,3.439,3.445,2.556,2.255,3.096,2.313,3.042,3.077,2.740,2.870,2.391,2.313,2.881,2.568,2.650,2.134,2.729,2.926,2.797,2.654,3.190,3.141,2.190,2.591,2.351,2.393,3.789,2.077,1.946,2.077,2.648,2.496,2.488,3.442,2.226,2.572,2.424,2.402,2.195,2.269,2.208,2.085,2.516,2.831,2.556,2.478,2.013,2.527,2.317,1.679,2.182,2.523,2.356,2.381,2.510,2.478,2.382,2.704,2.56470,834957.0,1.291679e+06,10021.8,317.1,13011.2,40022.8,5746.7,2828.5,4048.0,1590.6,1098.7,1111.7,16757.7,3212.8,1216.0,1154.2,433.0,3200.8,65.7,824.6,10517.1,458.2,12013.7,40383.2,5597.2,2959.6,4222.3,1430.1,3274.8,1492.8,429.5,3294.6,29.6,726.9,0.0,1235.5,0.0,0.0,0.0,0.0,0.0,154.0,897.3,572.5,398.8,371.1,725.2,860753.0,834957.0,189883.357691,191949.828129,381833.185820,154123.0,148832.0,302955.0,46280.0,508937.185820,755832.0,730036.0,1305889.0,0.666383,1.011001,33.0,50.0,83.0,1.291679e+06
1227,941_S_4420,941.0,81.4,EMCI,M,2.332,2.229,2.345,2.451,2.531,2.302,2.190,2.265,2.692,2.569,1.761,2.582,2.723,2.369,2.286,2.469,2.797,3.038,2.151,2.070,2.577,1.828,3.011,2.436,2.325,2.412,2.207,2.101,2.485,2.413,2.438,1.915,2.256,2.670,3.225,2.394,2.580,2.618,2.185,2.022,2.170,1.980,2.879,1.915,2.106,2.187,2.769,2.361,2.266,2.232,2.093,2.019,1.969,2.186,2.027,2.075,1.906,1.973,2.081,2.332,2.225,1.816,2.235,2.269,2.081,1.699,1.947,2.084,2.201,2.037,2.175,2.410,2.268,2.113,2.28337,1100576.0,1.648887e+06,2.434,2.350,2.365,2.237,2.611,2.323,2.312,2.464,2.892,2.323,1.860,2.403,2.478,2.565,2.524,2.550,2.675,3.090,2.377,2.181,2.582,1.838,2.901,2.842,2.237,2.449,2.179,1.959,2.449,2.368,2.366,2.215,1.980,2.597,2.839,2.506,2.685,2.549,2.321,2.194,2.207,1.950,3.019,1.834,1.912,2.263,2.225,2.536,2.255,2.485,1.622,2.035,2.125,2.150,1.996,2.101,2.143,2.022,1.920,2.496,2.214,1.933,2.026,2.249,2.059,1.711,1.921,2.213,2.151,1.963,2.286,2.358,2.192,1.953,2.28994,1100576.0,1.648887e+06,24503.3,1336.9,13205.3,45606.3,6462.9,3282.8,5460.2,2210.1,1233.9,1644.7,19837.5,4001.6,1578.5,1404.5,479.3,3465.2,43.4,895.4,18998.0,1198.9,11779.5,49655.3,6514.8,3264.4,5283.6,2143.3,3840.6,1754.2,454.6,4015.8,11.0,853.0,0.0,4082.3,0.0,0.0,0.0,0.0,0.0,220.4,1052.9,455.3,458.2,472.6,823.0,1152910.0,1100576.0,223514.607970,221264.415778,444779.023748,241302.5,240529.5,481832.0,55605.0,595822.023748,1033263.0,980929.0,1684850.0,0.699205,1.021811,42.0,23.0,65.0,1.648887e+06
1228,941_S_4764,941.0,82.7,EMCI,F,2.390,2.273,2.346,2.420,2.560,2.423,2.193,2.340,2.620,2.284,1.867,2.409,2.473,2.353,2.470,2.494,2.886,3.318,2.540,1.928,2.819,2.018,2.900,2.443,2.403,2.395,2.057,2.039,2.633,2.328,2.364,1.978,2.267,2.685,2.939,2.230,2.713,2.751,1.664,2.091,2.081,2.010,3.126,1.696,1.996,2.088,2.728,2.426,2.282,2.168,1.991,1.962,2.003,2.242,1.893,1.934,1.774,1.985,2.226,2.244,2.270,1.843,2.192,2.334,2.008,1.596,1.984,2.116,2.324,2.198,2.001,2.259,2.210,2.497,2.26628,911773.0,1.501232e+06,2.523,2.611,2.383,2.121,2.648,2.524,2.543,2.352,2.707,2.605,1.906,2.493,2.940,2.733,2.658,2.586,2.491,3.134,2.412,2.011,2.711,2.277,2.860,2.944,2.414,2.517,2.241,1.938,2.685,2.283,2.629,1.989,2.206,2.622,2.719,2.370,2.750,2.748,2.105,2.356,2.176,1.983,3.210,1.803,1.923,2.001,2.975,2.294,2.519,2.252,2.116,2.091,2.121,2.311,1.936,1.960,1.893,2.018,2.140,2.266,2.302,2.245,2.279,2.623,2.064,1.939,2.046,2.154,2.174,2.739,2.230,2.161,2.207,2.146,2.34057,911773.0,1.501232e+06,23552.1,1472.5,13205.7,52898.2,6019.8,2553.3,3522.6,1633.9,3309.5,2767.2,20808.8,3386.3,1414.1,1622.3,386.9,3859.5,65.1,900.1,32670.7,1682.8,13771.9,54908.0,6127.5,2597.7,3331.7,1801.1,3293.6,1649.8,319.5,3550.1,7.0,757.9,0.0,8845.7,0.0,0.0,0.0,0.0,0.0,181.0,874.4,292.2,299.1,267.4,654.6,980431.0,911773.0,195101.782272,201573.914802,396675.697074,166665.5,169401.5,336067.0,46648.0,551220.697074,847073.0,778415.0,1509139.0,0.653084,1.005267,25.0,31.0,56.0,1.501232e+06
1229,941_S_5124,941.0,76.7,SMC,F,2.377,2.142,2.325,2.660,2.447,2.544,2.191,1.712,1.542,1.576,1.980,2.737,2.718,2.496,2.609,2.689,3.148,3.627,2.531,2.169,2.891,1.984,2.395,2.565,2.690,2.784,2.558,2.463,2.762,2.263,2.660,1.644,2.902,2.896,3.558,2.525,2.861,2.816,2.538,2.195,2.298,1.909,3.185,1.781,1.998,2.280,2.492,2.832,2.515,3.162,2.055,2.334,2.302,2.459,2.595,2.324,2.053,2.270,2.312,2.287,2.426,2.074,2.178,2.649,2.173,1.246,2.227,2.546,2.497,2.160,2.209,2.261,2.414,2.413,2.33439,933149.0,1.520806e+06,2.385,2.277,2.337,2.504,2.561,2.457,2.025,1.188,1.013,2.096,1.871,2.571,2.478,2.561,2.686,2.577,2.959,3.643,2.476,2.117,2.560,2.443,2.600,2.658,2.672,2.542,2.251,2.310,2.581,2.064,2.556,2.175,2.616,2.840,2.930,2.431,2.667,2.688,2.048,2.582,2.360,2.218,3.419,1.859,1.802,1.662,3.108,2.695,2.512,2.856,2.600,2.129,2.146,2.441,2.216,2.281,2.231,2.121,2.210,2.218,2.612,2.016,2.447,2.655,1.776,1.600,2.151,2.241,2.278,1.978,1.189,2.437,2.467,2.317,2.31796,933149.0,1.520806e+06,15774.6,835.7,14415.6,41087.8,3160.2,2126.6,2959.6,1256.1,1059.2,1072.4,15940.5,1928.6,1216.1,224.7,160.6,1696.5,11.0,117.5,11582.5,1373.1,12932.4,42162.7,3042.4,2089.6,3344.5,1496.6,1974.6,1302.7,232.0,2320.1,17.7,88.4,0.0,4685.5,0.0,0.0,0.0,0.0,0.0,44.8,70.0,62.8,287.2,486.0,580.0,965281.0,933149.0,214017.595793,207683.916890,421701.512683,194013.5,181019.5,375033.0,31013.0,535903.512683,855049.0,822917.0,1450459.0,0.634717,0.953743,17.0,33.0,50.0,1.520806e+06

In [8]:
asl_adni_merge.to_csv("ADNI_data.csv")

In [16]:
ADNI_dxsum = pd.read_csv('/project_cephfs/3022017.06/ADNI/phenotypes/All_Subjects_DXSUM_02May2025.csv')
# ADNI_dxsum = ADNI_dxsum[["PTID", "VISCODE", "VISCODE2", "DIAGNOSIS", "EXAMDATE"]]
ADNI_dxsum = ADNI_dxsum.rename(columns={'PTID': 'Subject', 'EXAMDATE':'Acq Date'})

ADNI_dxsum['Acq Date'] = pd.to_datetime(ADNI_dxsum['Acq Date']).dt.strftime('%m/%d/%Y')

ADNI_dxsum

,PHASE,Subject,RID,VISCODE,VISCODE2,Acq Date,DIAGNOSIS,DXNORM,DXNODEP,DXMCI,DXMDES,DXMPTR1,DXMPTR2,DXMPTR3,DXMPTR4,DXMPTR5,DXMPTR6,DXMDUE,DXMOTHET,DXDSEV,DXDDUE,DXAD,DXAPP,DXAPROB,DXAPOSS,DXPARK,DXPDES,DXPCOG,DXPATYP,DXDEP,DXOTHDEM,DXODES,DXCONFID,ID,SITEID,USERDATE,USERDATE2,DD_CRF_VERSION_LABEL,LANGUAGE_CODE,HAS_QC_ERROR,update_stamp
0,ADNI1,011_S_0002,2,bl,bl,09/29/2005,1.0,1.0,-4.0,-4.0,-4,-4.0,-4.0,-4.0,-4.0,-4.0,-4.0,-4.0,-4,-4.0,NaN,-4.0,-4.0,-4,-4,-4.0,-4.0,-4.0,-4.0,NaN,-4.0,-4.0,4.0,2,107,2005-10-01,NaN,NaN,NaN,NaN,2005-10-01 00:00:00.0
1,ADNI1,011_S_0003,3,bl,bl,09/30/2005,3.0,-4.0,-4.0,-4.0,-4,-4.0,-4.0,-4.0,-4.0,-4.0,-4.0,-4.0,-4,2.0,NaN,1.0,1.0,1,-4,-4.0,-4.0,-4.0,-4.0,NaN,-4.0,-4.0,3.0,4,107,2005-10-01,NaN,NaN,NaN,NaN,2005-10-01 00:00:00.0
2,ADNI1,011_S_0005,5,bl,bl,09/30/2005,1.0,1.0,-4.0,-4.0,-4,-4.0,-4.0,-4.0,-4.0,-4.0,-4.0,-4.0,-4,-4.0,NaN,-4.0,-4.0,-4,-4,-4.0,-4.0,-4.0,-4.0,NaN,-4.0,-4.0,4.0,6,107,2005-10-01,NaN,NaN,NaN,NaN,2005-10-01 00:00:00.0
3,ADNI1,011_S_0008,8,bl,bl,09/30/2005,1.0,1.0,-4.0,-4.0,-4,-4.0,-4.0,-4.0,-4.0,-4.0,-4.0,-4.0,-4,-4.0,NaN,-4.0,-4.0,-4,-4,-4.0,-4.0,-4.0,-4.0,NaN,-4.0,-4.0,3.0,8,107,2005-10-01,NaN,NaN,NaN,NaN,2005-10-01 00:00:00.0
4,ADNI1,022_S_0007,7,bl,bl,10/06/2005,3.0,-4.0,-4.0,-4.0,-4,-4.0,-4.0,-4.0,-4.0,-4.0,-4.0,-4.0,-4,1.0,NaN,1.0,1.0,3,-4,-4.0,-4.0,-4.0,-4.0,NaN,-4.0,-4.0,4.0,10,10,2005-10-06,NaN,NaN,NaN,NaN,2005-10-06 00:00:00.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15079,ADNI4,027_S_10719,10719,4_sc,sc,04/30/2025,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,88250,27,2025-04-30,2025-04-30,v1,e,0.0,2025-05-01 01:46:35.0
15080,ADNI4,123_S_10726,10726,4_sc,sc,04/30/2025,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,88256,123,2025-04-30,2025-04-30,v1,e,0.0,2025-05-01 01:46:35.0
15081,ADNI4,014_S_6920,6920,4_m12,m48,04/29/2025,2.0,NaN,NaN,NaN,1,1.0,0.0,2.0,0.0,0.0,1.0,2.0,9,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,88299,14,2025-04-30,2025-04-30,v1,e,0.0,2025-05-01 01:46:35.0
15082,ADNI4,141_S_10451,10451,4_bl,bl,04/30/2025,2.0,NaN,NaN,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,88327,141,2025-04-30,2025-04-30,v1,e,0.0,2025-05-01 01:46:35.0
15083,ADNI4,003_S_4441,4441,4_m12,m156,04/24/2025,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,88356,3,2025-04-30,2025-04-30,v1,e,0.0,2025-05-01 01:46:35.0

In [17]:
ADNI_demo1 = pd.read_csv('/project_cephfs/3022017.06/ADNI/phenotypes/Velocity_4_04_2025.csv')
ADNI_demo2 = pd.read_csv('/project_cephfs/3022017.06/ADNI/phenotypes/Velocity_MP-RAGE_4_04_2025.csv')
ADNI_demo = pd.concat([ADNI_demo1, ADNI_demo2], axis = 0)
ADNI_demo.rename(columns={"Image Data ID": "IID", "Visit":"VISCODE"}, inplace ="True")
ADNI_demo

,IID,Subject,Group,Sex,Age,VISCODE,Modality,Description,Type,Acq Date,Format,Downloaded
0,I386070,941_S_5193,SMC,F,73,v04,MRI,MPRAGE,Original,8/19/2013,DCM,2/03/2025
1,I673862,941_S_5193,SMC,F,74,v21,MRI,MPRAGE,Original,4/02/2015,DCM,2/03/2025
2,I374433,941_S_5193,SMC,F,73,v02,MRI,MPRAGE,Original,5/29/2013,DCM,2/03/2025
3,I379869,941_S_5124,SMC,F,77,v04,MRI,MPRAGE,Original,7/11/2013,DCM,2/03/2025
4,I366196,941_S_5124,SMC,F,77,v02,MRI,MPRAGE,Original,4/09/2013,DCM,2/03/2025
...,...,...,...,...,...,...,...,...,...,...,...,...
2032,I173732,002_S_0295,CN,M,89,m48,MRI,MP-RAGE,Original,5/13/2010,DCM,3/11/2025
2033,I28561,002_S_0295,CN,M,85,m06,MRI,MP-RAGE,Original,11/02/2006,DCM,3/11/2025
2034,I144447,002_S_0295,CN,M,88,m36,MRI,MP-RAGE,Original,5/22/2009,DCM,3/11/2025
2035,I13722,002_S_0295,CN,M,85,sc,MRI,MP-RAGE,Original,4/18/2006,DCM,3/11/2025
2036,I55275,002_S_0295,CN,M,86,m12,MRI,MP-RAGE,Original,5/25/2007,DCM,3/11/2025

In [18]:
MRI_info_1 = pd.read_csv('/project_cephfs/3022017.06/ADNI/phenotypes/MRI3META_19May2025.csv')
MRI_info_1= MRI_info_1[["PTID", "VISCODE", "VISCODE2"]]
MRI_info_2 = pd.read_csv('/project_cephfs/3022017.06/ADNI/phenotypes/MRIMETA_19May2025.csv')
MRI_info_2= MRI_info_2[["PTID", "VISCODE", "VISCODE2"]]

MRI_info = pd.concat([MRI_info_1, MRI_info_2], axis =0)
MRI_info.rename(columns={"PTID": "Subject"}, inplace=True) 

ADNI_demo = ADNI_demo.merge(MRI_info, on=['Subject', 'VISCODE'], how ="left")
ADNI_demo_full = ADNI_demo.merge(ADNI_dxsum[["Subject", "VISCODE2","DIAGNOSIS"]],
                                 on=['Subject', 'VISCODE2'], 
                                 how='left')

,IID,Subject,Group,Sex,Age,VISCODE,Modality,Description,Type,Acq Date,Format,Downloaded,VISCODE2,DIAGNOSIS
0,I386070,941_S_5193,SMC,F,73,v04,MRI,MPRAGE,Original,8/19/2013,DCM,2/03/2025,m03,NaN
1,I673862,941_S_5193,SMC,F,74,v21,MRI,MPRAGE,Original,4/02/2015,DCM,2/03/2025,m24,1.0
2,I374433,941_S_5193,SMC,F,73,v02,MRI,MPRAGE,Original,5/29/2013,DCM,2/03/2025,scmri,NaN
3,I379869,941_S_5124,SMC,F,77,v04,MRI,MPRAGE,Original,7/11/2013,DCM,2/03/2025,m03,NaN
4,I366196,941_S_5124,SMC,F,77,v02,MRI,MPRAGE,Original,4/09/2013,DCM,2/03/2025,scmri,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8871,I28561,002_S_0295,CN,M,85,m06,MRI,MP-RAGE,Original,11/02/2006,DCM,3/11/2025,m06,1.0
8872,I144447,002_S_0295,CN,M,88,m36,MRI,MP-RAGE,Original,5/22/2009,DCM,3/11/2025,m36,1.0
8873,I144447,002_S_0295,CN,M,88,m36,MRI,MP-RAGE,Original,5/22/2009,DCM,3/11/2025,m36,1.0
8874,I13722,002_S_0295,CN,M,85,sc,MRI,MP-RAGE,Original,4/18/2006,DCM,3/11/2025,sc,NaN
8875,I55275,002_S_0295,CN,M,86,m12,MRI,MP-RAGE,Original,5/25/2007,DCM,3/11/2025,m12,1.0

In [19]:
ADNI_demo_full = ADNI_demo_full.dropna()
ADNI_demo_full

,IID,Subject,Group,Sex,Age,VISCODE,Modality,Description,Type,Acq Date,Format,Downloaded,VISCODE2,DIAGNOSIS
1,I673862,941_S_5193,SMC,F,74,v21,MRI,MPRAGE,Original,4/02/2015,DCM,2/03/2025,m24,1.0
5,I420755,941_S_5124,SMC,F,78,v11,MRI,MPRAGE,Original,4/21/2014,DCM,2/03/2025,m12,1.0
6,I673841,941_S_5124,SMC,F,79,v21,MRI,MPRAGE,Original,4/08/2015,DCM,2/03/2025,m24,1.0
7,I376064,941_S_4764,EMCI,F,84,v11,MRI,MPRAGE,Original,6/10/2013,DCM,2/03/2025,m12,2.0
10,I431036,941_S_4764,EMCI,F,85,v21,MRI,MPRAGE,Original,6/16/2014,DCM,2/03/2025,m24,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8870,I173732,002_S_0295,CN,M,89,m48,MRI,MP-RAGE,Original,5/13/2010,DCM,3/11/2025,m48,1.0
8871,I28561,002_S_0295,CN,M,85,m06,MRI,MP-RAGE,Original,11/02/2006,DCM,3/11/2025,m06,1.0
8872,I144447,002_S_0295,CN,M,88,m36,MRI,MP-RAGE,Original,5/22/2009,DCM,3/11/2025,m36,1.0
8873,I144447,002_S_0295,CN,M,88,m36,MRI,MP-RAGE,Original,5/22/2009,DCM,3/11/2025,m36,1.0
8875,I55275,002_S_0295,CN,M,86,m12,MRI,MP-RAGE,Original,5/25/2007,DCM,3/11/2025,m12,1.0

In [94]:

#ADNI
ADNI_aseg = pd.read_csv("/project_cephfs/3022017.06/ADNI/freesurfer/aseg_stats.txt", sep = "\t")
ADNI_lh_DES = pd.read_csv("/project_cephfs/3022017.06/ADNI/freesurfer/lh_aparc_a2009s_stats.txt", sep = "\t")
ADNI_rh_DES = pd.read_csv("/project_cephfs/3022017.06/ADNI/freesurfer/rh_aparc_a2009s_stats.txt", sep = "\t")

ADNI_lh_DK = pd.read_csv("/project_cephfs/3022017.06/ADNI/freesurfer/lh_aparc_stats.txt", sep = "\t")
ADNI_rh_DK = pd.read_csv("/project_cephfs/3022017.06/ADNI/freesurfer/rh_aparc_stats.txt", sep = "\t")

ADNI_lh_DK = ADNI_lh_DK.rename(columns={"lh.aparc.thickness": "ID"})
ADNI_rh_DK = ADNI_rh_DK.rename(columns={"rh.aparc.thickness": "ID"})

ADNI_DK = ADNI_lh_DK.merge(ADNI_rh_DK, on="ID")

ADNI_lh_DES = ADNI_lh_DES.rename(columns={"lh.aparc.a2009s.thickness": "ID"})
ADNI_rh_DES = ADNI_rh_DES.rename(columns={"rh.aparc.a2009s.thickness": "ID"})

ADNI_DES = ADNI_lh_DES.merge(ADNI_rh_DES, on="ID")

ADNI_DES = ADNI_DES.loc[:, ~ADNI_DES.columns.str.contains("eTIV")]
ADNI_DES = ADNI_DES.loc[:, ~ADNI_DES.columns.str.contains("BrainSegVolNotVent")]

ADNI_DK = ADNI_DK.loc[:, ~ADNI_DK.columns.str.contains("eTIV")]
ADNI_DK = ADNI_DK.loc[:, ~ADNI_DK.columns.str.contains("BrainSegVolNotVent")]

ADNI_aseg = ADNI_aseg.rename(columns={"Measure:volume": "ID"})
# we need all variables that were NOT processed using longitudian freesurfer
ADNI_aseg_long = ADNI_aseg[~ADNI_aseg["ID"].str.contains(r"\.long\.", regex=True)].copy()
ADNI_DES_long = ADNI_DES[~ADNI_DES["ID"].str.contains(r"\.long\.", regex=True)].copy()
ADNI_DK_long = ADNI_DK[~ADNI_DK["ID"].str.contains(r"\.long\.", regex=True)]


pattern = r'_I[^_]*'

ADNI_aseg_long["IID"] = ADNI_aseg_long["ID"].str.extract(r'_((I[^.]*))').iloc[:, 0]
ADNI_DES_long["IID"] = ADNI_DES_long["ID"].str.extract(r'_((I[^.]*))').iloc[:, 0]
ADNI_DK_long["IID"] = ADNI_DK_long["ID"].str.extract(r'_((I[^.]*))').iloc[:, 0]

ADNI_DES_long = ADNI_DES_long[~ADNI_DES_long['ID'].str.contains("real", na=False)]
ADNI_DK_long = ADNI_DK_long[~ADNI_DK_long['ID'].str.contains("real", na=False)]
ADNI_aseg_long = ADNI_aseg_long[~ADNI_aseg_long["IID"].str.contains("real", na=False)]

ADNI_aseg_long["IID"] = ADNI_aseg_long["IID"].astype(str)
#%%
ADNIMERGE = pd.read_csv('/project_cephfs/3022017.06/ADNI/phenotypes/ADNIMERGE_02May2025.csv')
ADNIMERGE = ADNIMERGE.rename(columns={'PTID': 'Subject', 'VISCODE': 'VISCODE2'})

ADNI_conversion_info = pd.read_csv('/project_cephfs/3022017.06/ADNI/phenotypes/All_Subjects_DXSUM_02May2025.csv')
ADNI_conversion_info = ADNI_conversion_info[["PTID", "VISCODE", "VISCODE2", "DIAGNOSIS"]]
ADNI_conversion_info = ADNI_conversion_info.rename(columns={'PTID': 'Subject'})

ADNI_demo1 = pd.read_csv('/project_cephfs/3022017.06/ADNI/phenotypes/Velocity_4_04_2025.csv')
ADNI_demo2 = pd.read_csv('/project_cephfs/3022017.06/ADNI/phenotypes/Velocity_MP-RAGE_4_04_2025.csv')
ADNI_demo = pd.concat([ADNI_demo1, ADNI_demo2], axis = 0)
ADNI_demo.rename(columns={"Image Data ID": "IID", "Visit":"VISCODE"}, inplace ="True")
ADNI_demo["Sex"] = ADNI_demo["Sex"].replace({"M": 1, "F": 0})


MRI_info_1 = pd.read_csv('/project_cephfs/3022017.06/ADNI/phenotypes/MRI3META_19May2025.csv')
MRI_info_1= MRI_info_1[["PTID", "VISCODE", "VISCODE2"]]
MRI_info_2 = pd.read_csv('/project_cephfs/3022017.06/ADNI/phenotypes/MRIMETA_19May2025.csv')
MRI_info_2= MRI_info_2[["PTID", "VISCODE", "VISCODE2"]]

MRI_info = pd.concat([MRI_info_1, MRI_info_2], axis =0)
MRI_info.rename(columns={"PTID": "Subject"}, inplace=True) 

ADNI_demo = ADNI_demo.merge(MRI_info, on=['Subject', 'VISCODE'], how ="left")
#%%
ADNI_demo_full = ADNI_demo.merge( ADNI_conversion_info[["Subject", "VISCODE2","DIAGNOSIS"]],
                                 on=['Subject', 'VISCODE2'], 
                                 how='left')
#remove werid ID
ADNI_demo_full["VISCODE"].value_counts()

/scratch/quirom/slurm_job_51311023/ipykernel_593906/2640606819.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ADNI_DK_long["IID"] = ADNI_DK_long["ID"].str.extract(r'_((I[^.]*))').iloc[:, 0]
/scratch/quirom/slurm_job_51311023/ipykernel_593906/2640606819.py:44: DtypeWarning: Columns (19,20,21,50,51,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  ADNIMERGE = pd.read_csv('/project_cephfs/3022017.06/ADNI/phenotypes/ADNIMERGE_02May2025.csv')

VISCODE
m06      1285
m12      1075
m24       853
sc        823
v02       633
v11       614
m36       537
v04       494
v21       476
v05       459
m18       458
m48       216
v41       213
v06       208
bl        175
v31       105
scmri     103
m03        84
m60        39
v51        15
nv          8
tau         2
uns1        1
Name: count, dtype: int64