In [1]:
import pandas as pd 
import numpy as np
import os 
import glob

# previous work

In [ ]:
root_dir = "/project_cephfs/3022017.06/UKB/freesurfer/"

#make loop here for all subj
subj_dir = os.path.join(root_dir, "1533138")
aseg_path = os.path.join(subj_dir, "stats/aseg.stats")
metrics = ["NVoxels", "Volume_mm3", "normMean", "normStdDev", "normMin", "normMax", "normRange"]

#read in data
aseg_data = pd.read_csv(
    aseg_path,
    sep='\s+',
    comment="#"
)

#drop the first 3 columns (as these contain no relevant info)
aseg_data = aseg_data.drop(columns = aseg_data.iloc[:, range(2)])
aseg_data.columns = [
    "NVoxels", "Volume_mm3", "StructName",
    "normMean", "normStdDev", "normMin", "normMax", "normRange"
]

#the columns are now:
#NVoxels Volume_mm3 StructName normMean normStdDev normMin normMax normRange 

#pivot data with the structname
pivoted_data = aseg_data.pivot_table(
    index= "StructName",
    values= metrics
)

#transpose data
pivoted_data = pivoted_data.T

#add subject id 
subject_id = os.path.basename(os.path.normpath(subj_dir))
pivoted_data.columns = pd.MultiIndex.from_product([[subject_id], pivoted_data.columns])

print(pivoted_data)
print(pivoted_data.shape)

In [8]:
#code to extract the #measure metrics for one participant
#should probably include this in the rh_ code but can also extract is separately and then merge the panda's dataframes
#now works but need to loop over all subjects for it to actually work
import pandas as pd
import re

root_dir = "/project_cephfs/3022017.06/UKB/freesurfer/"

#make loop here for all subj
subj_dir = os.path.join(root_dir, "1533138")
aseg_path = os.path.join(subj_dir, "stats/aseg.stats")


target_metrics = [
    "BrainSegVol",
    "BrainSegVolNotVent",
    "BrainSegVolNotVentSurf",
    "VentricleChoroidVol",
    "lhCortexVol", 
    "rhCortexVol",
    "CortexVol",
    "lhCerebralWhiteMatterVol",
    "rhCerebralWhiteMatterVol",
    "CerebralWhiteMatterVol", 
    "SubCortGrayVol", 
    "TotalGrayVol",
    "SupraTentorialVol",
    "SupraTentorialVolNotVent",
    "SupraTentorialVolNotVentVox",
    "MaskVol", 
    "BrainSegVol-to-eTIV", 
    "MaskVol-to-eTIV",
    "lhSurfaceHoles",
    "rhSurfaceHoles", 
    "SurfaceHoles", 
    "eTIV"#, 
    #"avg_thickness"
]

metrics_dict = {}
with open(aseg_path, "r") as file:
    for line in file:
        if line.startswith("# Measure"):
            match = re.match(r"# Measure (\w+), ([\w\-\.]+), .*?, (\d+\.\d+|\d+),", line)
            #match = re.match(r"# Measure (\w+), ([\w\-\.]+), .*?, (\d+\.\d+|\d+|\.d+),", line)
           
            if match:
                metric_name = match.group(2)
                metric_value = match.group(3)
                if metric_name in target_metrics:
                    metrics_dict[metric_name] = metric_value

metrics_df = pd.DataFrame([metrics_dict])

subject_id = subj_dir.split("/")[-1]  
metrics_df["SubjectID"] = subject_id

metrics_df = metrics_df[["SubjectID"] + [m for m in target_metrics if m in metrics_dict]]
metrics_df = metrics_df.set_index("SubjectID")
print(metrics_df)
print(metrics_df.shape)

              BrainSegVol BrainSegVolNotVent BrainSegVolNotVentSurf  \
SubjectID
1533138    1109928.000000     1091828.000000         1091560.264705

          VentricleChoroidVol    lhCortexVol    rhCortexVol      CortexVol  \
SubjectID
1533138          14644.000000  239995.398460  230734.026454  470729.424915

          lhCerebralWhiteMatterVol rhCerebralWhiteMatterVol  \
SubjectID
1533138              216804.832342            214283.007449

          CerebralWhiteMatterVol SubCortGrayVol   TotalGrayVol  \
SubjectID
1533138            431087.839791   51003.000000  632310.424915

          SupraTentorialVol SupraTentorialVolNotVent  \
SubjectID
1533138       972366.264705            957722.264705

          SupraTentorialVolNotVentVox         MaskVol lhSurfaceHoles  \
SubjectID
1533138                 952960.000000  1461693.000000             36

          rhSurfaceHoles SurfaceHoles            eTIV
SubjectID
1533138               32           68  1467243.030772
(1, 20)

In [10]:
#code to extract the # Measure from aseg.stats and put into a dataframe
import os
import re
import pandas as pd

root_dir = "/project_cephfs/3022017.06/UKB/freesurfer/"
all_subject_dirs = [
    d for d in os.listdir(root_dir)
    if os.path.isdir(os.path.join(root_dir, d)) and re.match(r"^[A-Za-z0-9_\-]+$", d)
]

all_metrics = pd.DataFrame()

target_metrics = [
        "BrainSegVol",
        "BrainSegVolNotVent",
        "BrainSegVolNotVentSurf",
        "VentricleChoroidVol",
        "lhCortexVol", 
        "rhCortexVol",
        "CortexVol",
        "lhCerebralWhiteMatterVol",
        "rhCerebralWhiteMatterVol",
        "CerebralWhiteMatterVol", 
        "SubCortGrayVol", 
        "TotalGrayVol",
        "SupraTentorialVol",
        "SupraTentorialVolNotVent",
        "SupraTentorialVolNotVentVox",
        "MaskVol", 
        "BrainSegVol-to-eTIV", 
        "MaskVol-to-eTIV",
        "lhSurfaceHoles",
        "rhSurfaceHoles", 
        "SurfaceHoles", 
        "eTIV"#, 
        #"avg_thickness"
        ]

for subj in all_subject_dirs:
    subj_dir = os.path.join(root_dir, subj)
    aseg_path = os.path.join(subj_dir, "stats", "aseg.stats")

    if os.path.exists(aseg_path):
        metrics_dict = {}
        with open(aseg_path, "r") as file:
            for line in file:
                if line.startswith("# Measure"):
                    match = re.match(r"# Measure (\w+), ([\w\-\.]+), .*?, (\d+\.\d+|\d+),", line)
        
                    if match:
                        metric_name = match.group(2)
                        metric_value = match.group(3)
                        if metric_name in target_metrics:
                            metrics_dict[metric_name] = metric_value
        
        metrics_df = pd.DataFrame([metrics_dict])
        
        subject_id = subj_dir.split("/")[-1]  
        metrics_df["SubjectID"] = subject_id
        
        metrics_df = metrics_df[["SubjectID"] + [m for m in target_metrics if m in metrics_dict]]
        all_metrics = pd.concat([all_metrics, metrics_df], ignore_index=True)

final_df = all_metrics.set_index("SubjectID")

print("\nFinal combined DataFrame:")
print(final_df.tail())
#final_df.to_csv("measures_aseg_stats.csv")

Final combined DataFrame:
              BrainSegVol BrainSegVolNotVent BrainSegVolNotVentSurf  \
SubjectID
3463731    1087763.000000     1074155.000000         1074044.590841
3814047    1381218.000000     1361802.000000         1361118.069372
4851516    1171168.000000     1126991.000000         1126172.653085
3626816    1312016.000000     1296802.000000         1296479.157079
2420905    1212468.000000     1131306.000000         1129281.415336

          VentricleChoroidVol    lhCortexVol    rhCortexVol      CortexVol  \
SubjectID
3463731          10821.000000  223084.305442  223427.153869  446511.459311
3814047          15852.000000  267234.026324  268869.745404  536103.771728
4851516          39066.000000  234958.938990  243924.327341  478883.266331
3626816          13016.000000  284966.233468  281963.022961  566929.256429
2420905          72823.000000  261277.132148  239849.410671  501126.542819

          lhCerebralWhiteMatterVol rhCerebralWhiteMatterVol  \
SubjectID
3463731              225035.478761            225461.652769
3814047              288432.969038            289045.328607
4851516              214183.841702            215887.545052
3626816              259029.816272            257758.084378
2420905              212701.770700            212510.101818

          CerebralWhiteMatterVol SubCortGrayVol   TotalGrayVol  \
SubjectID
3463731            450497.131530   52658.000000  596528.459311
3814047            577478.297645   66154.000000  748468.771728
4851516            430071.386754   56675.000000  666915.266331
3626816            516787.900650   64298.000000  748824.256429
2420905            425211.872518   54294.000000  677536.542819

          SupraTentorialVol SupraTentorialVolNotVent  \
SubjectID
3463731       963199.590841            952378.590841
3814047      1199607.069372           1183755.069372
4851516      1008102.653085            969036.653085
3626816      1166519.157079           1153503.157079
2420905      1056870.415336            984047.415336

          SupraTentorialVolNotVentVox         MaskVol lhSurfaceHoles  \
SubjectID
3463731                 949650.000000  1428892.000000              7
3814047                1180281.000000  1836467.000000             12
4851516                 966270.000000  1627084.000000             25
3626816                1148436.000000  1651536.000000             19
2420905                 982411.000000  1645815.000000             13

          rhSurfaceHoles SurfaceHoles            eTIV
SubjectID
3463731                6           13  1408013.143875
3814047               11           23  1743858.210319
4851516               23           48  1538819.423413
3626816               16           35  1555233.211399
2420905               32           45  1572427.025482

In [14]:
print("\nFinal combined DataFrame:")
print(final_df.head())
print(final_df.shape)

Final combined DataFrame:
              BrainSegVol BrainSegVolNotVent BrainSegVolNotVentSurf  \
SubjectID
1533138    1109928.000000     1091828.000000         1091560.264705
1875529    1127087.000000     1079149.000000         1078238.559246
4758824    1140990.000000     1109558.000000         1109367.068707
5304207    1119328.000000     1102891.000000         1102308.359285
2747983    1177154.000000     1157188.000000         1157129.506938

          VentricleChoroidVol    lhCortexVol    rhCortexVol      CortexVol  \
SubjectID
1533138          14644.000000  239995.398460  230734.026454  470729.424915
1875529          41059.000000  238784.863444  214459.362318  453244.225762
4758824          27856.000000  229865.245490  244370.530076  474235.775566
5304207          13353.000000  222587.937796  228103.351494  450691.289290
2747983          16931.000000  254398.375719  264476.696131  518875.071850

          lhCerebralWhiteMatterVol rhCerebralWhiteMatterVol  \
SubjectID
1533138              216804.832342            214283.007449
1875529              213360.488638            213108.844846
4758824              227567.531865            229887.761277
5304207              228899.534424            227247.535571
2747983              219037.385558            222428.049530

          CerebralWhiteMatterVol SubCortGrayVol   TotalGrayVol  \
SubjectID
1533138            431087.839791   51003.000000  632310.424915
1875529            426469.333485   58117.000000  624720.225762
4758824            457455.293142   50395.000000  626505.775566
5304207            456147.069995   52877.000000  617207.289290
2747983            441465.435088   55218.000000  685933.071850

          SupraTentorialVol SupraTentorialVolNotVent  \
SubjectID
1533138       972366.264705            957722.264705
1875529       981219.559246            940160.559246
4758824      1014397.068707            986541.068707
5304207       975514.359285            962161.359285
2747983      1036817.506938           1019886.506938

          SupraTentorialVolNotVentVox         MaskVol lhSurfaceHoles  \
SubjectID
1533138                 952960.000000  1461693.000000             36
1875529                 938534.000000  1551777.000000             13
4758824                 982208.000000  1502220.000000             10
5304207                 960250.000000  1477321.000000             12
2747983                1015594.000000  1559711.000000             11

          rhSurfaceHoles SurfaceHoles            eTIV
SubjectID
1533138               32           68  1467243.030772
1875529               18           31  1553387.362546
4758824               16           26  1439587.220879
5304207               15           27  1400207.759887
2747983                9           20  1537970.624262
(37950, 20)

In [4]:
#aseg code to extract the columns of dataframe [already used and extracted]
import os
import re
import pandas as pd

root_dir = "/project_cephfs/3022017.06/UKB/freesurfer/"
all_subject_dirs = [
    d for d in os.listdir(root_dir)
    if os.path.isdir(os.path.join(root_dir, d)) and re.match(r"^[A-Za-z0-9_\-]+$", d)
]

all_data = []

for subj in all_subject_dirs:
    subj_dir = os.path.join(root_dir, subj)
    aseg_path = os.path.join(subj_dir, "stats", "aseg.stats")

    if os.path.exists(aseg_path):        
        aseg_data = pd.read_csv(aseg_path, sep=r"\s+", comment="#", header=None)
        aseg_data = aseg_data.drop(aseg_data.columns[:2], axis=1)

        aseg_data.columns = [
            "NVoxels", "Volume_mm3", "StructName",
            "normMean", "normStdDev", "normMin", "normMax", "normRange"
        ]

        pivoted_data = aseg_data.pivot_table(
            index=None,
            columns="StructName",
            values= ["normMean", "normStdDev"] #, "normMin", "normMax", "normRange"] 
        )

        pivoted_data["SubjectID"] = subj
        pivoted_data = pivoted_data.set_index("SubjectID")

        all_data.append(pivoted_data)

final_df = pd.concat(all_data, axis=0)

print("\nFinal combined DataFrame:")
print(final_df.head())

#final_df.to_csv("combined_aseg_stats.csv")

Final combined DataFrame:
StructName  3rd-Ventricle  4th-Ventricle  5th-Ventricle  Brain-Stem  \
SubjectID
1533138           36.8674        31.3818            0.0     81.5837
1533138           11.0437         9.4151            0.0      9.5555
1875529           31.3638        30.1527            0.0     83.1511
1875529            9.4712        10.0800            0.0      9.6401
4758824           35.0732        36.2819            0.0     84.1654

StructName  CC_Anterior  CC_Central  CC_Mid_Anterior  CC_Mid_Posterior  \
SubjectID
1533138        100.2311     94.2112          93.9213           89.7624
1533138         17.1138     17.2545          18.2093           18.9696
1875529         95.3329     89.9717          90.3416           85.7553
1875529         16.4144     17.5802          17.7160           19.0117
4758824         99.6201     95.3489          95.4416           93.4878

StructName  CC_Posterior      CSF  ...  Right-Thalamus-Proper  \
SubjectID                          ...
1533138         101.8197  50.2793  ...                85.2027
1533138          17.3595  11.0398  ...                 9.5500
1875529         100.0998  47.6822  ...                86.7084
1875529          18.9186  12.6358  ...                 9.9171
4758824         101.0905  48.8590  ...                84.6246

StructName  Right-VentralDC  Right-WM-hypointensities  Right-choroid-plexus  \
SubjectID
1533138             88.3665                       0.0               52.4355
1533138             11.5594                       0.0               10.9509
1875529             90.9502                       0.0               52.0951
1875529             11.8542                       0.0               10.3819
4758824             90.8455                       0.0               49.6715

StructName  Right-non-WM-hypointensities  Right-vessel  WM-hypointensities  \
SubjectID
1533138                              0.0       60.0000             72.3171
1533138                              0.0        2.9848             10.4501
1875529                              0.0       60.4118             70.6537
1875529                              0.0        4.4589             11.6983
4758824                              0.0       52.0556             70.2288

StructName  non-WM-hypointensities  Left-Thalamus  Right-Thalamus
SubjectID
1533138                        0.0            NaN             NaN
1533138                        0.0            NaN             NaN
1875529                        0.0            NaN             NaN
1875529                        0.0            NaN             NaN
4758824                        0.0            NaN             NaN

[5 rows x 47 columns]

In [6]:
print(final_df.shape)

(75900, 47)

final_df.to_csv("combined_aseg_stats.csv")

# Now let's create the dataset for the right and left hand side:


/project_cephfs/3022017.06/UKB/freesurfer/1533138/stats/lh.aparc.a2009s.stats
/project_cephfs/3022017.06/UKB/freesurfer/1533138/stats/rh.aparc.a2009s.stats



ColHeaders StructName NumVert SurfArea GrayVol ThickAvg ThickStd MeanCurv GausCurv FoldInd CurvInd
G&S_frontomargin                          964    697   2432  2.884 0.737     0.165     0.052       16     2.5

In [25]:
#LH_ file for 1 subject
root_dir = "/project_cephfs/3022017.06/UKB/freesurfer/"

#make loop here for all subj
subj_dir = os.path.join(root_dir, "1533138")
lh_path = os.path.join(subj_dir, "stats","lh.aparc.a2009s.stats")
metrics = ["ColHeaders", "StructName", "NumVert", "SurfArea", "GrayVol", "ThickAvg", "ThickStd", "MeanCurv", "GausCurv", "FoldInd", "CurvInd"]

#read in data
lh_data = pd.read_csv(
    lh_path,
    sep='\s+',
    comment="#"
)

lh_data.columns = [
    "StructName", "NumVert", "SurfArea", "GrayVol", "ThickAvg", "ThickStd", "MeanCurv", "GausCurv", "FoldInd", "CurvInd"
]

#pivot data with the structname
pivoted_data = lh_data.pivot_table(
    index= "StructName",
    values= ["ThickAvg"] #,"ThickStd"]
)

#transpose data
pivoted_data = pivoted_data.T
pivoted_data = pivoted_data.add_prefix("lh_")
pivoted_data = pivoted_data.add_suffix("_thickness")

#add subject id 
subject_id = os.path.basename(os.path.normpath(subj_dir))
pivoted_data.columns = pd.MultiIndex.from_product([[subject_id], pivoted_data.columns])
pivoted_data["SubjectID"] = subject_id

pivoted_data = pivoted_data.set_index("SubjectID")
print(pivoted_data)

                               1533138                                  \
StructName lh_G&S_cingul-Ant_thickness lh_G&S_cingul-Mid-Ant_thickness
SubjectID
1533138                          3.217                           3.067

                                                                            \
StructName lh_G&S_cingul-Mid-Post_thickness lh_G&S_occipital_inf_thickness
SubjectID
1533138                               2.777                           2.89

                                                                     \
StructName lh_G&S_paracentral_thickness lh_G&S_subcentral_thickness
SubjectID
1533138                            2.41                       2.989

                                                                               \
StructName lh_G&S_transv_frontopol_thickness lh_G_Ins_lg&S_cent_ins_thickness
SubjectID
1533138                                3.028                            3.858

                                              \
StructName lh_G_cingul-Post-dorsal_thickness
SubjectID
1533138                                3.085

                                               ...  \
StructName lh_G_cingul-Post-ventral_thickness  ...
SubjectID                                      ...
1533138                                 2.873  ...

                                                                         \
StructName lh_S_parieto_occipital_thickness lh_S_pericallosal_thickness
SubjectID
1533138                               2.429                       2.288

                                                                          \
StructName lh_S_postcentral_thickness lh_S_precentral-inf-part_thickness
SubjectID
1533138                         2.521                              2.617

                                                                         \
StructName lh_S_precentral-sup-part_thickness lh_S_suborbital_thickness
SubjectID
1533138                                 2.518                     3.285

                                                                   \
StructName lh_S_subparietal_thickness lh_S_temporal_inf_thickness
SubjectID
1533138                         2.469                       2.518


StructName lh_S_temporal_sup_thickness lh_S_temporal_transverse_thickness
SubjectID
1533138                          2.803                              2.706

[1 rows x 73 columns]

<>:12: SyntaxWarning: invalid escape sequence '\s'
<>:12: SyntaxWarning: invalid escape sequence '\s'
/scratch/quirom/slurm_job_49464438/ipykernel_3333150/868605765.py:12: SyntaxWarning: invalid escape sequence '\s'
  sep='\s+',

In [ ]:
#for rh for 1 subj
root_dir = "/project_cephfs/3022017.06/UKB/freesurfer/"

#make loop here for all subj
subj_dir = os.path.join(root_dir, "1533138")
rh_path = os.path.join(subj_dir, "stats","rh.aparc.a2009s.stats")
metrics = ["ColHeaders", "StructName", "NumVert", "SurfArea", "GrayVol", "ThickAvg", "ThickStd", "MeanCurv", "GausCurv", "FoldInd", "CurvInd"]

#read in data
rh_data = pd.read_csv(
    rh_path,
    sep='\s+',
    comment="#"
)

rh_data.columns = [
    "StructName", "NumVert", "SurfArea", "GrayVol", "ThickAvg", "ThickStd", "MeanCurv", "GausCurv", "FoldInd", "CurvInd"
]

#pivot data with the structname
pivoted_data = rh_data.pivot_table(
    index= "StructName",
    values= ["ThickAvg","ThickStd"]
)

#transpose data
pivoted_data = pivoted_data.T
pivoted_data = pivoted_data.add_prefix("rh_")
pivoted_data = pivoted_data.add_suffix("_thickness")


#add subject id 
subject_id = os.path.basename(os.path.normpath(subj_dir))
pivoted_data.columns = pd.MultiIndex.from_product([[subject_id], pivoted_data.columns])

print(pivoted_data)
print(pivoted_data.shape)

In [26]:
#loop over all LH files and create CSV file
import os
import re
import pandas as pd
root_dir = "/project_cephfs/3022017.06/UKB/freesurfer/"

all_subject_dirs = [
    d for d in os.listdir(root_dir)
    if os.path.isdir(os.path.join(root_dir, d)) and re.match(r"^[A-Za-z0-9_\-]+$", d)
]

all_data = pd.DataFrame()

for subj in all_subject_dirs:
    subj_dir = os.path.join(root_dir, subj)
    lh_path = os.path.join(subj_dir, "stats", "lh.aparc.a2009s.stats")

    if os.path.exists(lh_path):        
        lh_data = pd.read_csv(lh_path, sep=r"\s+", comment="#", header=None)
        lh_data.columns = ["StructName", "NumVert", "SurfArea", "GrayVol", "ThickAvg", "ThickStd", "MeanCurv", "GausCurv", "FoldInd", "CurvInd"]

        pivoted_data = lh_data.pivot_table(
            index="StructName",
            columns=None,
            values= ["ThickAvg"] #,"ThickStd"]
        )

        #transpose data
        pivoted_data = pivoted_data.T
        pivoted_data = pivoted_data.add_prefix("lh_")
        pivoted_data = pivoted_data.add_suffix("_thickness")

        #set subj as index
        pivoted_data["SubjectID"] = subj
        pivoted_data = pivoted_data.set_index("SubjectID")

        #add to dataframes
        all_data = pd.concat([all_data, pivoted_data])


print("\nFinal combined DataFrame:")
print(all_data.head())
print(all_data.shape)

#all_data.to_csv("lh_stats.csv")

Final combined DataFrame:
StructName  lh_G&S_cingul-Ant_thickness  lh_G&S_cingul-Mid-Ant_thickness  \
SubjectID
1533138                           3.217                            3.067
1875529                           3.205                            3.207
4758824                           2.734                            1.964
5304207                           3.070                            2.655
2747983                           3.072                            3.018

StructName  lh_G&S_cingul-Mid-Post_thickness  lh_G&S_frontomargin_thickness  \
SubjectID
1533138                                2.777                          2.884
1875529                                2.756                          2.896
4758824                                2.683                          2.311
5304207                                2.868                          2.464
2747983                                2.905                          2.701

StructName  lh_G&S_occipital_inf_thickness  lh_G&S_paracentral_thickness  \
SubjectID
1533138                              2.890                         2.410
1875529                              2.691                         2.655
4758824                              2.251                         2.450
5304207                              2.248                         2.269
2747983                              2.845                         2.633

StructName  lh_G&S_subcentral_thickness  lh_G&S_transv_frontopol_thickness  \
SubjectID
1533138                           2.989                              3.028
1875529                           2.932                              3.042
4758824                           3.050                              2.577
5304207                           3.053                              2.357
2747983                           3.201                              2.783

StructName  lh_G_Ins_lg&S_cent_ins_thickness  \
SubjectID
1533138                                3.858
1875529                                3.079
4758824                                3.165
5304207                                2.930
2747983                                3.259

StructName  lh_G_cingul-Post-dorsal_thickness  ...  \
SubjectID                                      ...
1533138                                 3.085  ...
1875529                                 3.103  ...
4758824                                 3.038  ...
5304207                                 3.075  ...
2747983                                 3.165  ...

StructName  lh_G_and_S_cingul-Mid-Post_thickness  \
SubjectID
1533138                                      NaN
1875529                                      NaN
4758824                                      NaN
5304207                                      NaN
2747983                                      NaN

StructName  lh_G_and_S_frontomargin_thickness  \
SubjectID
1533138                                   NaN
1875529                                   NaN
4758824                                   NaN
5304207                                   NaN
2747983                                   NaN

StructName  lh_G_and_S_occipital_inf_thickness  \
SubjectID
1533138                                    NaN
1875529                                    NaN
4758824                                    NaN
5304207                                    NaN
2747983                                    NaN

StructName  lh_G_and_S_paracentral_thickness  lh_G_and_S_subcentral_thickness  \
SubjectID
1533138                                  NaN                              NaN
1875529                                  NaN                              NaN
4758824                                  NaN                              NaN
5304207                                  NaN                              NaN
2747983                                  NaN                              NaN

StructName  lh_G_and_S_transv_frontopol_thickness  \
SubjectID
1533138                                       NaN
1875529                                       NaN
4758824                                       NaN
5304207                                       NaN
2747983                                       NaN

StructName  lh_S_intrapariet_and_P_trans_thickness  \
SubjectID
1533138                                        NaN
1875529                                        NaN
4758824                                        NaN
5304207                                        NaN
2747983                                        NaN

StructName  lh_S_oc-temp_med_and_Lingual_thickness  \
SubjectID
1533138                                        NaN
1875529                                        NaN
4758824                                        NaN
5304207                                        NaN
2747983                                        NaN

StructName  lh_S_oc_middle_and_Lunatus_thickness  \
SubjectID
1533138                                      NaN
1875529                                      NaN
4758824                                      NaN
5304207                                      NaN
2747983                                      NaN

StructName  lh_S_oc_sup_and_transversal_thickness
SubjectID
1533138                                       NaN
1875529                                       NaN
4758824                                       NaN
5304207                                       NaN
2747983                                       NaN

[5 rows x 87 columns]
(37956, 87)

In [27]:
all_data.to_csv("lh_stats.csv")

In [28]:
#loop over RH files and create csv file
import os
import re
import pandas as pd
root_dir = "/project_cephfs/3022017.06/UKB/freesurfer/"

all_subject_dirs = [
    d for d in os.listdir(root_dir)
    if os.path.isdir(os.path.join(root_dir, d)) and re.match(r"^[A-Za-z0-9_\-]+$", d)
]

all_data = pd.DataFrame()

for subj in all_subject_dirs:
    subj_dir = os.path.join(root_dir, subj)
    rh_path = os.path.join(subj_dir, "stats", "rh.aparc.a2009s.stats")

    if os.path.exists(rh_path):        
        rh_data = pd.read_csv(rh_path, sep=r"\s+", comment="#", header=None)
        rh_data.columns = ["StructName", "NumVert", "SurfArea", "GrayVol", "ThickAvg", "ThickStd", "MeanCurv", "GausCurv", "FoldInd", "CurvInd"]

        pivoted_data = rh_data.pivot_table(
            index="StructName",
            columns=None,
            values= ["ThickAvg"] #,"ThickStd"]
        )

        #transpose data
        pivoted_data = pivoted_data.T
        pivoted_data = pivoted_data.add_prefix("rh_")
        pivoted_data = pivoted_data.add_suffix("_thickness")

        #set subj as index
        pivoted_data["SubjectID"] = subj
        pivoted_data = pivoted_data.set_index("SubjectID")

        #add to dataframes
        all_data = pd.concat([all_data, pivoted_data])


print("\nFinal combined DataFrame:")
print(all_data.head())
print(all_data.shape)

#all_data.to_csv("rh_stats.csv")

Final combined DataFrame:
StructName  rh_G&S_cingul-Ant_thickness  rh_G&S_cingul-Mid-Ant_thickness  \
SubjectID
1533138                           2.888                            2.826
1875529                           2.835                            2.424
4758824                           2.991                            3.015
5304207                           2.932                            2.715
2747983                           3.033                            3.070

StructName  rh_G&S_cingul-Mid-Post_thickness  rh_G&S_frontomargin_thickness  \
SubjectID
1533138                                2.626                          2.797
1875529                                2.782                          2.287
4758824                                2.864                          2.668
5304207                                2.700                          2.585
2747983                                3.138                          2.632

StructName  rh_G&S_occipital_inf_thickness  rh_G&S_paracentral_thickness  \
SubjectID
1533138                              2.840                         2.139
1875529                              2.733                         2.134
4758824                              2.824                         2.594
5304207                              2.695                         2.447
2747983                              3.078                         2.788

StructName  rh_G&S_subcentral_thickness  rh_G&S_transv_frontopol_thickness  \
SubjectID
1533138                           2.603                              2.955
1875529                           2.905                              2.610
4758824                           2.858                              2.972
5304207                           3.123                              2.598
2747983                           2.994                              2.743

StructName  rh_G_Ins_lg&S_cent_ins_thickness  \
SubjectID
1533138                                3.004
1875529                                2.840
4758824                                3.541
5304207                                2.853
2747983                                3.674

StructName  rh_G_cingul-Post-dorsal_thickness  ...  \
SubjectID                                      ...
1533138                                 3.095  ...
1875529                                 3.221  ...
4758824                                 3.368  ...
5304207                                 3.144  ...
2747983                                 3.488  ...

StructName  rh_G_and_S_cingul-Mid-Post_thickness  \
SubjectID
1533138                                      NaN
1875529                                      NaN
4758824                                      NaN
5304207                                      NaN
2747983                                      NaN

StructName  rh_G_and_S_frontomargin_thickness  \
SubjectID
1533138                                   NaN
1875529                                   NaN
4758824                                   NaN
5304207                                   NaN
2747983                                   NaN

StructName  rh_G_and_S_occipital_inf_thickness  \
SubjectID
1533138                                    NaN
1875529                                    NaN
4758824                                    NaN
5304207                                    NaN
2747983                                    NaN

StructName  rh_G_and_S_paracentral_thickness  rh_G_and_S_subcentral_thickness  \
SubjectID
1533138                                  NaN                              NaN
1875529                                  NaN                              NaN
4758824                                  NaN                              NaN
5304207                                  NaN                              NaN
2747983                                  NaN                              NaN

StructName  rh_G_and_S_transv_frontopol_thickness  \
SubjectID
1533138                                       NaN
1875529                                       NaN
4758824                                       NaN
5304207                                       NaN
2747983                                       NaN

StructName  rh_S_intrapariet_and_P_trans_thickness  \
SubjectID
1533138                                        NaN
1875529                                        NaN
4758824                                        NaN
5304207                                        NaN
2747983                                        NaN

StructName  rh_S_oc-temp_med_and_Lingual_thickness  \
SubjectID
1533138                                        NaN
1875529                                        NaN
4758824                                        NaN
5304207                                        NaN
2747983                                        NaN

StructName  rh_S_oc_middle_and_Lunatus_thickness  \
SubjectID
1533138                                      NaN
1875529                                      NaN
4758824                                      NaN
5304207                                      NaN
2747983                                      NaN

StructName  rh_S_oc_sup_and_transversal_thickness
SubjectID
1533138                                       NaN
1875529                                       NaN
4758824                                       NaN
5304207                                       NaN
2747983                                       NaN

[5 rows x 87 columns]
(37956, 87)

all_data.to_csv("rh_stats.csv")

# Now we have the CSV files for LH, RH, Aseg.stats and Aseg measures

What i now need to do is:
1. drop the columns that do not contain any numbers (drop nan or something)
2. merge the dataframes with the "SubjectID" as a key --> google how to do this
4. merge this large datatable with the basic_demographics.csv
5. find site location in the data and add this to the large dataframe (with the SubjectID as a key)
6. compute euler (do more research and study the code given to you)
7. concat everything and you have the datatable

In [52]:
#54 is assessment centre
#53 is date of attending
# df_misc = pd.read_csv("/project_cephfs/3022017.05/phenotypes/current/99_miscellaneous.csv", nrows = 10000)
# cols = list(df_misc.columns)
# df_misc = df_misc.drop(columns = df_misc.iloc[:, range(13, len(cols))])
# df_misc = df_misc.drop(columns = df_misc.iloc[:, range(1,6)])
# print(df_misc)

filepath = "/project_cephfs/3022017.05/phenotypes/current/99_miscellaneous.csv"
chunksize = 10000
df_first = pd.read_csv(filepath, nrows=chunksize)

#strip irrelevant cols
cols = list(df_first.columns)
df_first = df_first.drop(columns=df_first.iloc[:, range(13, len(cols))])
df_first = df_first.drop(columns=df_first.iloc[:, range(1, 6)])
keep_cols = df_first.columns.tolist()

dfs = []
for chunk in pd.read_csv(filepath, chunksize=10000):
    df_clean = chunk[keep_cols]
    dfs.append(df_clean)
df_full = pd.concat(dfs, ignore_index=True)

In [53]:
df_full = df_full.rename(columns={"eid" : "SubjectID",
                                  "53-0.0" : "Year_scan_initial",
                                  "53-1.0" : "Year_scan_1_repeat",
                                  "53-2.0" : "Year_scan_imaging_visit",
                                  "54-0.0" : "Assessment_centre_initial",
                                  "54-2.0" : "Assessment_centre_1_repeat",
                                  "55-0.0" : "Month_scan_initial",
                                  "55-1.0" : "Month_scan_1_repeat",
                                 })

df_full = df_full.set_index("SubjectID")
#df_full.to_csv("Yr_mnth_site_scan.csv")

In [54]:
df_full.head()

,Year_scan_initial,Year_scan_1_repeat,Year_scan_imaging_visit,Assessment_centre_initial,Assessment_centre_1_repeat,Month_scan_initial,Month_scan_1_repeat
SubjectID,,,,,,,
1000012,2009.528767,NaN,NaN,11016.0,NaN,7.0,NaN
1000029,2009.857534,2013.032877,NaN,11014.0,NaN,11.0,1.0
1000031,2009.495890,NaN,NaN,11012.0,NaN,7.0,NaN
1000047,2008.229508,NaN,NaN,11005.0,NaN,3.0,NaN
1000050,2009.939726,NaN,2015.723288,11016.0,11025.0,12.0,NaN

In [58]:
#basic demographics 
#31 : sex (0: female, 1 : male)
#34 : birth year 

df_basic_demo = pd.read_csv("/project_cephfs/3022017.05/phenotypes/current/01_basic_demographics.csv")
df_basic_demo = df_basic_demo.drop(columns = df_basic_demo.iloc[:, range(3,4)])
df_basic_demo = df_basic_demo.rename(columns={"eid" : "SubjectID",
                                              "31-0.0" : "Sex",
                                              "34-0.0" : "Birthyear"
                                             })
df_basic_demo = df_basic_demo.set_index("SubjectID")
df_basic_demo
#df_basic_demo.to_csv("Sex_birthyear.csv")

           Sex  Birthyear
SubjectID
1000012    1.0     1946.0
1000029    0.0     1943.0
1000031    1.0     1958.0
1000047    1.0     1956.0
1000050    0.0     1944.0
...        ...        ...
6025263    1.0     1942.0
6025278    1.0     1955.0
6025280    1.0     1947.0
6025291    0.0     1963.0
6025306    1.0     1965.0

[502366 rows x 2 columns]

In [66]:
#check if specific participant is in the dataset
df_basic_demo.query('SubjectID == 1533138')

           Sex  Birthyear
SubjectID
1533138    0.0     1950.0

# Now we have the csv files that we need to calculate the age on the scan
What i now need to do is:
1. calculate the age of each participant during the scan
2. turn the year of scan into an integer
3. do year_scan - birthyear = age
How should i deal with the ages of the columns of the second scan? im not sure

In [1]:
import pandas as pd 
import os
import glob
import numpy as np
import re

In [5]:
#lets make the age column at first scan
csv_path = "/home/preclineu/quirom/Desktop/internship/Normative-Models-and-VAE/logs/csv_files/"
yr_mth_scan = os.path.join(csv_path, "Yr_mnth_site_scan.csv")
sex_birth = os.path.join(csv_path, "Sex_birthyear.csv")


df_yr_mnth = pd.read_csv(yr_mth_scan).set_index("SubjectID")
df_demo = pd.read_csv(sex_birth).set_index("SubjectID")

In [3]:
#turn to integer values
df_yr_mnth = df_yr_mnth.fillna(-1)
df_yr_mnth = df_yr_mnth.select_dtypes(include=['float']).astype(int)
df_yr_mnth

,Year_scan_initial,Year_scan_1_repeat,Year_scan_imaging_visit,Assessment_centre_initial,Assessment_centre_1_repeat,Month_scan_initial,Month_scan_1_repeat
SubjectID,,,,,,,
1000012,2009,-1,-1,11016,-1,7,-1
1000029,2009,2013,-1,11014,-1,11,1
1000031,2009,-1,-1,11012,-1,7,-1
1000047,2008,-1,-1,11005,-1,3,-1
1000050,2009,-1,2015,11016,11025,12,-1
...,...,...,...,...,...,...,...
6025263,2008,-1,-1,11010,-1,10,-1
6025278,2010,-1,-1,11014,-1,5,-1
6025280,2006,-1,2016,10003,-1,5,-1
6025291,2006,-1,-1,10003,-1,3,-1
6025306,2006,-1,2022,10003,11025,6,-1

In [4]:
#turn basic demo into ints
df_demo = df_demo.fillna(-1)
df_demo = df_demo.select_dtypes(include=['float']).astype(int)
df_demo

           Sex  Birthyear
SubjectID
1000012      1       1946
1000029      0       1943
1000031      1       1958
1000047      1       1956
1000050      0       1944
...        ...        ...
6025263      1       1942
6025278      1       1955
6025280      1       1947
6025291      0       1963
6025306      1       1965

[502366 rows x 2 columns]

In [20]:
df_merg = pd.merge(df_yr_mnth, df_demo, on="SubjectID")
df_merg["Age_during_scan"] = df_merg["Year_scan_initial"] - df_merg["Birthyear"]
df_merg = df_merg.fillna(-1)
df_merg["Age_during_2nd_scan"] = df_merg["Year_scan_imaging_visit"] - df_merg["Birthyear"]
df_merg

,Year_scan_initial,Year_scan_1_repeat,Year_scan_imaging_visit,Assessment_centre_initial,Assessment_centre_1_repeat,Month_scan_initial,Month_scan_1_repeat,Sex,Birthyear,Age_during_scan,Age_during_2nd_scan
SubjectID,,,,,,,,,,,
1000012,2009,-1,-1,11016,-1,7,-1,1,1946,63,-1947
1000029,2009,2013,-1,11014,-1,11,1,0,1943,66,-1944
1000031,2009,-1,-1,11012,-1,7,-1,1,1958,51,-1959
1000047,2008,-1,-1,11005,-1,3,-1,1,1956,52,-1957
1000050,2009,-1,2015,11016,11025,12,-1,0,1944,65,71
...,...,...,...,...,...,...,...,...,...,...,...
6025263,2008,-1,-1,11010,-1,10,-1,1,1942,66,-1943
6025278,2010,-1,-1,11014,-1,5,-1,1,1955,55,-1956
6025280,2006,-1,2016,10003,-1,5,-1,1,1947,59,69
6025291,2006,-1,-1,10003,-1,3,-1,0,1963,43,-1964
6025306,2006,-1,2022,10003,11025,6,-1,1,1965,41,57

In [24]:
df_merg.query('SubjectID == 2420905')

,Year_scan_initial,Year_scan_1_repeat,Year_scan_imaging_visit,Assessment_centre_initial,Assessment_centre_1_repeat,Month_scan_initial,Month_scan_1_repeat,Sex,Birthyear,Age_during_scan,Age_during_2nd_scan
SubjectID,,,,,,,,,,,
2420905,2009,-1,2016,11016,11025,7,-1,0,1949,60,67

In [56]:
csv_path = "/home/preclineu/quirom/Desktop/internship/Normative-Models-and-VAE/logs/csv_files/"
df = os.path.join(csv_path, "lh_stats.csv")
df = pd.read_csv(df)

mask = ~df["SubjectID"].astype(str).str.fullmatch(r"\d+")
non_mask = ~mask
amount = mask.sum() 
print(amount)

#mask = ~df["SubjectID"].astype(str).str.fullmatch(r"\d+")
#mask_other = df["SubjectID"].astype(str).str.contains(r'\d+_(?!long$|scan2$)')

#turns out there are 4008 scans that are either _long, _scan2
df.query("SubjectID == '4299969' or SubjectID == '4299969_long' or SubjectID == '4299969_scan2'")
df.dropna(axis=1)

4008

,SubjectID,lh_G_front_inf-Opercular_thickness,lh_G_front_inf-Triangul_thickness,lh_G_front_middle_thickness,lh_G_front_sup_thickness,lh_G_oc-temp_lat-fusifor_thickness,lh_G_oc-temp_med-Lingual_thickness,lh_G_oc-temp_med-Parahip_thickness,lh_G_occipital_middle_thickness,lh_G_orbital_thickness,...,lh_S_front_middle_thickness,lh_S_front_sup_thickness,lh_S_occipital_ant_thickness,lh_S_orbital-H_Shaped_thickness,lh_S_pericallosal_thickness,lh_S_postcentral_thickness,lh_S_precentral-inf-part_thickness,lh_S_precentral-sup-part_thickness,lh_S_temporal_inf_thickness,lh_S_temporal_sup_thickness
0,1533138,2.955,2.859,2.994,3.053,3.310,2.248,2.847,2.846,3.016,...,2.565,2.774,2.719,3.068,2.288,2.521,2.617,2.518,2.518,2.803
1,1875529,3.153,3.050,2.993,3.167,3.214,2.035,3.097,2.610,3.199,...,2.575,2.740,2.315,3.130,2.512,2.341,2.988,2.921,2.653,2.749
2,4758824,2.789,2.575,2.677,3.002,3.026,1.646,2.861,2.427,2.801,...,2.426,2.691,2.417,2.788,1.654,2.334,2.728,2.652,2.406,2.483
3,5304207,2.765,2.561,2.589,3.046,3.010,1.692,2.860,2.607,2.804,...,2.408,2.599,2.523,2.974,1.794,2.347,2.630,2.828,2.489,2.556
4,2747983,2.932,2.969,2.940,3.229,3.124,2.212,3.408,2.742,2.924,...,2.484,2.924,2.548,3.221,1.768,2.493,2.956,2.789,2.703,2.615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37951,3463731,2.984,2.743,2.868,3.188,2.943,2.110,3.555,2.797,3.222,...,2.507,2.780,2.715,3.190,1.574,2.510,3.044,2.823,2.658,2.616
37952,3814047,2.773,2.620,2.807,2.965,3.055,2.270,3.299,2.677,2.676,...,2.290,2.524,2.269,2.693,2.459,2.172,2.441,2.503,2.518,2.464
37953,4851516,2.861,2.838,2.639,2.796,2.808,2.121,3.124,2.659,2.616,...,2.309,2.516,2.511,2.831,1.827,2.149,2.524,2.486,2.118,2.644
37954,3626816,3.186,3.115,3.135,3.192,3.233,2.275,3.257,2.900,2.910,...,2.834,2.822,2.352,3.226,2.106,2.549,2.923,2.912,2.882,2.911
37955,2420905,3.169,2.951,3.025,3.244,3.234,2.130,3.051,2.834,2.884,...,2.546,3.033,2.603,2.850,2.122,2.795,2.982,2.998,3.046,2.871

# any file that is _scan2 or _long uses the column "Year_scan_imaging_visit"
still need to drop those files in the original dataset

In [50]:
df_merg["Age_during_scan"] = df_merg["Year_scan_initial"] - df_merg["Birthyear"]
df_merg["Age_during_2nd_scan"] = df_merg["Year_scan_imaging_visit"] - df_merg["Birthyear"]
df_merg["Age"] = df_merg["Age_during_scan"]
df_merg.loc[df_merg["Age_during_2nd_scan"] > 0, "Age"] = df_merg["Age_during_2nd_scan"]
second_scans = df_merg[df_merg["Age_during_2nd_scan"] > 0].copy()
second_scans["ScanType"] = "SecondScan"
df_merg = df_merg.drop(second_scans.index)
df_merg["ScanType"] = "FirstScan"
combined_df = pd.concat([df_merg, second_scans], ignore_index=False)

combined_df

,Year_scan_initial,Year_scan_1_repeat,Year_scan_imaging_visit,Assessment_centre_initial,Assessment_centre_1_repeat,Month_scan_initial,Month_scan_1_repeat,Sex,Birthyear,Age_during_scan,Age_during_2nd_scan,Age,ScanType
SubjectID,,,,,,,,,,,,,
1000012,2009,-1,-1,11016,-1,7,-1,1,1946,63,-1947,63,FirstScan
1000029,2009,2013,-1,11014,-1,11,1,0,1943,66,-1944,66,FirstScan
1000031,2009,-1,-1,11012,-1,7,-1,1,1958,51,-1959,51,FirstScan
1000047,2008,-1,-1,11005,-1,3,-1,1,1956,52,-1957,52,FirstScan
1000068,2009,-1,-1,11016,-1,3,-1,0,1959,50,-1960,50,FirstScan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6025242,2010,-1,-1,11021,-1,2,-1,0,1957,53,-1958,53,FirstScan
6025255,2009,-1,-1,11016,-1,6,-1,1,1950,59,-1951,59,FirstScan
6025263,2008,-1,-1,11010,-1,10,-1,1,1942,66,-1943,66,FirstScan
6025278,2010,-1,-1,11014,-1,5,-1,1,1955,55,-1956,55,FirstScan
6025291,2006,-1,-1,10003,-1,3,-1,0,1963,43,-1964,43,FirstScan

In [8]:
#let's create a large pandas dataframe with all the data we have up to this moment (we still need to figure out how to calculate the age, because something is going wrong
csv_path = "/home/preclineu/quirom/Desktop/internship/Normative-Models-and-VAE/logs/csv_files/"
data_1 = os.path.join(csv_path, "aseg_normmean_stats.csv")
data_2 = os.path.join(csv_path, "lh_stats.csv")
data_3 = os.path.join(csv_path, "rh_stats.csv")
data_4 = os.path.join(csv_path, "Yr_mnth_site_scan.csv")
data_5 = os.path.join(csv_path, "Sex_birthyear.csv")

df_1 = pd.read_csv(data_1)
df_2 = pd.read_csv(data_2)
df_3 = pd.read_csv(data_3)
df_4 = pd.read_csv(data_4)
df_5 = pd.read_csv(data_5)

df_1 = df_1.dropna(axis=1)
df_2 = df_2.dropna(axis=1)
df_3 = df_3.dropna(axis=1)
df_4 = df_4.dropna(axis=1)
df_5 = df_5.dropna(axis=1)

df_1 = df_1.reset_index()
df_2 = df_2.reset_index()
df_3 = df_3.reset_index()
df_4 = df_4.reset_index()
df_5 = df_5.reset_index()

#this now merges correctly!

combined_df = df_1.merge(df_2, on="SubjectID", how="left")
combined_df = combined_df.merge(df_3, on="SubjectID", how="left")

#still need to see how to combine the other dataframes --> maybe i need to ask where the correct files are if i cannot locate them myself
#also i should delete the _long and _scan2 files

#combined_df = combined_df.merge(df_4, on="SubjectID", how="left")
#combined_df = combined_df.merge(df_5, on="SubjectID", how="left")
#combined_df = combined_df.set_index("SubjectID")

drop_scans = combined_df[combined_df['SubjectID'].str.endswith('_scan2')].index
combined_df = combined_df.drop(drop_scans)

drop_scans = combined_df[combined_df['SubjectID'].str.endswith('_long')].index
combined_df = combined_df.drop(drop_scans)

combined_df.head(50)
# print(df_1.shape)
# print(df_2.shape)
# print(df_3.shape)

,index_x,SubjectID,3rd-Ventricle,4th-Ventricle,5th-Ventricle,Brain-Stem,CC_Anterior,CC_Central,CC_Mid_Anterior,CC_Mid_Posterior,...,rh_S_front_sup_thickness,rh_S_interm_prim-Jensen_thickness,rh_S_oc-temp_lat_thickness,rh_S_occipital_ant_thickness,rh_S_parieto_occipital_thickness,rh_S_pericallosal_thickness,rh_S_postcentral_thickness,rh_S_precentral-inf-part_thickness,rh_S_precentral-sup-part_thickness,rh_S_temporal_sup_thickness
0,0,1533138,36.8674,31.3818,0.0,81.5837,100.2311,94.2112,93.9213,89.7624,...,2.753,2.170,2.914,2.665,2.533,1.965,2.227,2.672,2.561,2.735
1,1,1875529,31.3638,30.1527,0.0,83.1511,95.3329,89.9717,90.3416,85.7553,...,2.481,2.309,2.913,2.403,2.287,2.407,2.016,2.794,2.706,2.676
2,2,4758824,35.0732,36.2819,0.0,84.1654,99.6201,95.3489,95.4416,93.4878,...,2.631,2.253,2.494,2.663,2.461,1.793,2.397,2.537,2.547,2.684
3,3,5304207,41.5897,33.3825,0.0,84.4920,104.1299,93.2735,95.2359,95.4301,...,2.644,2.580,2.840,2.850,2.390,1.782,2.377,2.501,2.696,2.746
4,4,2747983,42.9063,33.2600,0.0,83.8396,103.1391,92.3403,90.9298,94.4794,...,2.774,2.511,2.972,2.727,2.504,1.927,2.579,2.863,2.843,2.829
5,5,5279838,57.7897,34.9515,0.0,82.4166,104.4810,97.8531,95.3256,96.0647,...,2.692,2.350,2.537,2.767,2.407,1.578,2.278,2.646,2.671,2.743
6,6,4959500,34.7429,32.5413,0.0,83.6770,103.8699,94.1685,94.9715,93.6816,...,2.863,2.901,2.820,2.670,2.890,2.017,2.509,2.761,2.893,3.027
7,7,1206189,35.4566,34.7022,0.0,83.7808,98.1308,93.2479,93.6054,85.1335,...,2.652,2.863,2.667,2.492,2.270,1.669,2.288,2.825,2.376,2.610
9,9,1038650,30.4305,32.9715,0.0,82.6067,95.7199,91.7314,92.5541,86.4249,...,2.553,1.968,2.822,2.460,2.325,2.309,2.210,2.721,2.543,2.484
10,10,1070217,30.3028,26.1140,0.0,83.1401,101.9138,93.4935,95.9066,88.3465,...,2.872,2.789,3.281,2.442,2.776,2.210,2.408,2.919,2.579,2.915
11,11,1003456,34.1004,33.8778,0.0,85.3135,101.0510,91.9035,94.0698,83.1559,...,2.515,2.103,2.875,2.003,2.149,1.945,2.085,2.556,2.342,2.580
12,12,5570385,38.3321,30.9931,0.0,84.2504,97.9293,90.5205,94.6497,84.2050,...,2.879,2.625,2.530,3.018,2.647,2.237,2.371,2.839,2.683,2.846
13,13,4576628,41.4172,32.1934,0.0,82.5865,101.2040,93.4371,94.2675,92.4707,...,2.803,2.941,2.614,2.662,2.566,2.203,2.662,2.694,3.090,2.894
14,14,3552662,31.2566,33.0429,0.0,83.9282,96.6977,90.0772,92.0896,89.3097,...,2.775,2.570,2.572,2.511,2.460,1.687,2.416,2.648,2.793,2.809
15,15,3773341,34.7418,29.3923,0.0,84.7373,99.8975,92.3810,95.2606,87.0489,...,2.741,2.444,2.553,2.576,2.375,1.609,2.442,2.956,2.654,2.815
16,16,4030312,34.3777,32.9698,0.0,81.3029,99.2645,91.5178,91.8339,91.1169,...,2.471,2.343,2.367,2.297,2.357,2.261,2.056,2.360,2.214,2.445
17,17,5915039,42.4888,29.7805,0.0,82.7300,97.1783,92.8075,97.1579,91.6423,...,2.421,2.641,2.597,2.328,2.157,2.698,2.203,2.407,2.265,2.533
19,19,5482855,30.3869,19.4881,0.0,84.2137,98.8826,94.6863,95.6377,89.7660,...,2.774,3.381,2.492,2.645,2.382,2.562,2.418,2.783,2.455,2.645
20,20,3091675,37.5268,33.3562,0.0,83.9581,97.8804,89.6739,91.3153,78.9552,...,2.754,2.927,2.769,2.486,2.303,2.577,2.368,2.844,2.785,2.750
21,21,5872172,38.4989,32.9331,0.0,84.5987,101.6099,93.3629,94.9341,91.7187,...,2.532,2.646,2.852,2.377,2.380,2.160,2.061,2.757,2.425,2.585
22,22,3782798,31.5173,27.6380,0.0,84.5430,96.1547,89.7639,91.4062,88.8964,...,2.538,2.629,2.513,2.153,2.165,1.631,2.198,2.585,2.442,2.528
23,23,2816926,39.0120,30.4267,0.0,86.2644,99.0681,92.9681,92.0182,91.1727,...,2.695,2.805,2.781,2.444,2.538,2.722,2.465,2.896,2.800,2.792
24,24,1237146,33.1739,31.2642,0.0,82.3197,94.6897,90.2224,97.3153,88.4340,...,3.007,3.006,2.792,2.666,2.588,2.616,2.200,2.945,2.641,2.885
25,25,1706010,37.2204,30.8542,0.0,84.6230,97.0648,90.2259,93.6145,92.3386,...,2.576,2.975,2.526,2.485,2.241,2.309,2.188,2.633,2.381,2.644
26,26,1048918,32.1342,29.3912,0.0,84.8276,95.4258,92.5402,90.0482,91.4689,...,2.658,2.445,2.864,2.672,2.317,2.621,2.352,2.653,2.651,2.671
27,27,5848965,42.7598,28.1996,0.0,83.4548,97.5989,88.9518,96.3505,89.8406,...,2.548,1.778,2.381,2.343,2.020,1.940,1.969,2.465,2.499,2.380
28,28,1140362,44.9008,30.2028,0.0,82.5220,100.6502,94.8454,96.9551,90.1478,...,2.953,2.532,2.667,2.109,2.295,2.224,2.192,2.675,2.653,2.903
29,29,1693867,42.0262,34.8946,0.0,82.7704,102.6932,95.2636,96.5295,97.2512,...,2.567,2.521,2.629,2.282,2.386,2.420,2.439,2.569,2.385,2.692
30,30,1013160,35.0311,32.7177,0.0,83.8804,97.3728,91.6265,93.6016,83.7770,...,2.792,3.000,2.500,2.586,2.541,1.536,2.314,2.667,2.600,2.661
31,31,4317811,40.6764,33.9480,0.0,84.1831,97.4000,92.0437,98.0525,90.4790,...,2.429,2.325,2.547,2.503,2.318,2.597,2.204,2.573,2.499,2.689
32,32,1040088,46.2997,35.4576,0.0,85.4906,102.3649,92.5561,93.1667,90.8549,...,2.782,2.921,2.525,2.317,2.350,2.359,2.162,2.828,2.867,2.733
34,34,5214130,35.4102,30.8073,0.0,83.2954,99.6749,85.3328,95.0446,70.5408,...,2.574,2.323,2.700,2.519,2.478,1.406,2.157,2.814,2.428,2.651
35,35,1082134,38.6746,35.3623,0.0,82.2953,102.4040,95.1841,95.1541,84.2360,...,2.690,2.669,2.782,2.110,2.398,2.221,1.997,2.802,1.945,2.779
36,36,5243615,33.5266,34.5051,0.0,84.0193,81.6882,77.6147,75.2120,77.6488,...,2.584,2.736,2.845,2.260,2.353,1.528,2.552,2.696,2.711,2.573
37,37,4762523,41.4505,30.7418,0.0,85.0224,100.3002,95.2031,96.3981,91.2877,...,2.808,2.357,2.603,2.406,2.441,1.787,2.408,2.661,2.611,2.719
38,38,4032907,44.2773,32.4204,0.0,84.7316,104.3670,93.8630,93.1991,95.3425,...,2.644,2.757,2.802,2.455,2.545,2.368,2.541,2.877,2.642,2.804
39,39,4040804,37.8531,33.2342,0.0,83.1448,101.4093,92.2628,92.7997,94.0224,...,2.849,2.339,2.923,2.468,2.590,1.644,2.505,2.746,2.568,2.790
40,40,5929871,33.6529,27.7998,0.0,84.1721,98.6896,92.9568,91.6708,88.5132,...,2.830,2.358,2.563,2.537,2.648,2.483,2.431,2.768,2.677,2.887
41,41,4807628,27.7038,36.2084,0.0,81.6476,101.4524,95.6205,98.4799,93.4043,...,2.516,2.494,2.780,2.242,2.365,2.211,2.094,2.558,2.289,2.634
42,42,2992999,35.2126,29.1961,0.0,82.0518,102.6563,95.0437,96.3367,90.5749,...,2.536,2.425,2.842,2.523,2.367,2.322,2.177,2.415,2.450,2.660
43,43,3601900,28.2581,27.0940,0.0,82.3222,93.8074,92.3776,92.2857,84.7991,...,2.584,2.391,2.679,2.547,2.303,1.694,2.142,2.440,2.019,2.542
44,44,5673008,36.2800,30.2442,0.0,82.9308,103.9640,92.4073,90.9316,95.1431,...,2.727,2.495,2.979,2.813,2.605,2.163,2.662,2.737,2.724,2.842
45,45,5637534,34.5293,34.5285,0.0,82.6641,100.7249,94.5830,95.4781,91.2115,...,2.694,2.182,2.684,2.422,2.464,1.756,2.394,2.802,2.473,2.719
46,46,5076248,33.2572,28.7937,0.0,83.5983,99.4675,94.5568,94.6086,90.5721,...,2.696,2.470,3.135,2.640,2.496,2.644,2.486,2.646,2.761,2.871
47,47,4820569,41.0995,25.3148,0.0,82.2507,96.5032,90.9719,94.0571,87.6632,...,2.477,2.564,2.636,2.393,2.375,2.647,2.279,2.696,2.519,2.834
48,48,2699003,30.2110,28.6355,0.0,83.8315,103.5833,96.7693,95.0380,86.6791,...,2.789,2.853,2.640,2.897,2.457,1.915,2.468,2.960,2.780,2.968
49,49,4291640,36.1321,30.9568,0.0,82.9227,95.0713,91.3187,92.6189,85.7634,...,2.568,2.171,2.525,2.440,2.505,2.547,2.265,2.625,2.613,2.787
50,50,4180040,34.6546,23.9692,0.0,83.3262,96.7925,92.0697,94.1221,83.9547,...,2.946,2.679,3.045,2.627,2.520,1.733,2.515,2.858,2.803,2.870
51,51,5461081,52.9004,34.1458,0.0,84.8077,100.0617,88.1660,93.4386,90.5761,...,2.612,2.803,2.752,2.469,2.346,2.612,2.404,2.784,2.509,2.827
52,52,1881004,31.8810,26.7163,0.0,85.5537,96.4837,92.7623,94.0900,92.0506,...,2.914,2.970,2.857,2.781,2.656,1.653,2.546,2.913,2.875,2.890

In [32]:
#for df4
df_4["SubjectID"] = df_4["SubjectID"].astype(int)
combined_df["SubjectID"] = combined_df["SubjectID"].astype(int)

combined_df = combined_df.loc[:, ~combined_df.columns.str.contains("^index", case=False)]
df_4 = df_4.loc[:, ~df_4.columns.str.contains("^index", case=False)]

combined_df = combined_df.merge(df_4, on="SubjectID", how="left")



#for df5
df_5["SubjectID"] = df_5["SubjectID"].astype(int)
combined_df["SubjectID"] = combined_df["SubjectID"].astype(int)

combined_df = combined_df.loc[:, ~combined_df.columns.str.contains("^index", case=False)]
df_5 = df_5.loc[:, ~df_5.columns.str.contains("^index", case=False)]

combined_df_5 = combined_df.merge(df_5, on="SubjectID", how="left")
#combined_df_5.head(50)


pd.set_option('display.max_columns', None)
combined_df_5

,SubjectID,3rd-Ventricle,4th-Ventricle,5th-Ventricle,Brain-Stem,CC_Anterior,CC_Central,CC_Mid_Anterior,CC_Mid_Posterior,CC_Posterior,CSF,Left-Accumbens-area,Left-Amygdala,Left-Caudate,Left-Cerebellum-Cortex,Left-Cerebellum-White-Matter,Left-Hippocampus,Left-Inf-Lat-Vent,Left-Lateral-Ventricle,Left-Pallidum,Left-Putamen,Left-VentralDC,Left-WM-hypointensities,Left-choroid-plexus,Left-non-WM-hypointensities,Left-vessel,Optic-Chiasm,Right-Accumbens-area,Right-Amygdala,Right-Caudate,Right-Cerebellum-Cortex,Right-Cerebellum-White-Matter,Right-Hippocampus,Right-Inf-Lat-Vent,Right-Lateral-Ventricle,Right-Pallidum,Right-Putamen,Right-VentralDC,Right-WM-hypointensities,Right-choroid-plexus,Right-non-WM-hypointensities,Right-vessel,WM-hypointensities,non-WM-hypointensities,lh_G_front_inf-Opercular_thickness,lh_G_front_inf-Triangul_thickness,lh_G_front_middle_thickness,lh_G_front_sup_thickness,lh_G_oc-temp_lat-fusifor_thickness,lh_G_oc-temp_med-Lingual_thickness,lh_G_oc-temp_med-Parahip_thickness,lh_G_occipital_middle_thickness,lh_G_orbital_thickness,lh_G_pariet_inf-Angular_thickness,lh_G_pariet_inf-Supramar_thickness,lh_G_parietal_sup_thickness,lh_G_postcentral_thickness,lh_G_precentral_thickness,lh_G_rectus_thickness,lh_G_temp_sup-Lateral_thickness,lh_G_temp_sup-Plan_tempo_thickness,lh_G_temporal_inf_thickness,lh_G_temporal_middle_thickness,lh_Pole_occipital_thickness,lh_Pole_temporal_thickness,lh_S_calcarine_thickness,lh_S_central_thickness,lh_S_collat_transv_ant_thickness,lh_S_front_inf_thickness,lh_S_front_middle_thickness,lh_S_front_sup_thickness,lh_S_occipital_ant_thickness,lh_S_orbital-H_Shaped_thickness,lh_S_pericallosal_thickness,lh_S_postcentral_thickness,lh_S_precentral-inf-part_thickness,lh_S_precentral-sup-part_thickness,lh_S_temporal_inf_thickness,lh_S_temporal_sup_thickness,rh_G_cuneus_thickness,rh_G_front_middle_thickness,rh_G_front_sup_thickness,rh_G_oc-temp_lat-fusifor_thickness,rh_G_occipital_middle_thickness,rh_G_occipital_sup_thickness,rh_G_orbital_thickness,rh_G_pariet_inf-Angular_thickness,rh_G_pariet_inf-Supramar_thickness,rh_G_parietal_sup_thickness,rh_G_postcentral_thickness,rh_G_precentral_thickness,rh_G_precuneus_thickness,rh_G_temp_sup-Lateral_thickness,rh_G_temp_sup-Plan_tempo_thickness,rh_G_temporal_inf_thickness,rh_G_temporal_middle_thickness,rh_Pole_occipital_thickness,rh_S_calcarine_thickness,rh_S_central_thickness,rh_S_cingul-Marginalis_thickness,rh_S_front_inf_thickness,rh_S_front_middle_thickness,rh_S_front_sup_thickness,rh_S_interm_prim-Jensen_thickness,rh_S_oc-temp_lat_thickness,rh_S_occipital_ant_thickness,rh_S_parieto_occipital_thickness,rh_S_pericallosal_thickness,rh_S_postcentral_thickness,rh_S_precentral-inf-part_thickness,rh_S_precentral-sup-part_thickness,rh_S_temporal_sup_thickness,Year_scan_initial,Assessment_centre_initial,Month_scan_initial,Sex,Birthyear
0,1533138,36.8674,31.3818,0.0,81.5837,100.2311,94.2112,93.9213,89.7624,101.8197,50.2793,78.4219,71.2338,80.8676,59.8507,84.6188,68.5732,46.7229,33.9679,101.8322,86.8691,91.6590,0.0,51.1266,0.0,57.8200,73.7333,78.6486,67.9744,81.4864,60.6036,85.0926,68.6901,47.5164,34.8871,98.3383,83.9349,88.3665,0.0,52.4355,0.0,60.0000,72.3171,0.0,2.955,2.859,2.994,3.053,3.310,2.248,2.847,2.846,3.016,2.873,3.261,2.815,2.368,2.955,3.441,3.265,2.718,3.326,3.215,2.260,3.297,2.075,2.159,3.082,2.661,2.565,2.774,2.719,3.068,2.288,2.521,2.617,2.518,2.518,2.803,2.051,2.741,2.932,3.033,2.811,2.532,3.070,2.830,2.593,2.522,2.183,2.853,2.670,3.282,2.650,3.318,3.051,2.059,2.016,1.869,2.466,2.446,2.393,2.753,2.170,2.914,2.665,2.533,1.965,2.227,2.672,2.561,2.735,2010.180822,11016.0,3.0,0.0,1950.0
1,1875529,31.3638,30.1527,0.0,83.1511,95.3329,89.9717,90.3416,85.7553,100.0998,47.6822,75.2107,67.8566,79.1048,61.6535,86.0415,70.1340,41.7886,28.0750,101.7199,84.5846,92.3921,0.0,50.0821,0.0,56.6591,76.4964,78.8506,69.8590,81.3028,61.3760,85.2568,70.4684,42.9726,31.5494,101.0202,83.6074,90.9502,0.0,52.0951,0.0,60.4118,70.6537,0.0,3.153,3.050,2.993,3.167,3.214,2.035,3.097,2.610,3.199,2.890,2.850,2.438,2.402,3.158,3.121,3.200,2.955,3.230,3.144,2.084,3.536,2.271,2.179,2.845,2.477,2.575,2.740,2.315,3.130,2.512,2.341,2.988,2.921,2.653,2.749,1.708,2.636,2.849,2.571,2.601,1.949,2.683,2.521,2.693,2.091,1.851,2.715,2.438,2.772,2.341,2.882,2.920,1.803,1.938,1.751,2.149,2.395,2.318,2.481,2.309,2.913,2.403,2.287,2.407,2.016,2.794,2.706,2.676,2008.136612,11008.0,2.0,0.0,1948.0
2,4758824,35.0732,36.2819,0.0,84.1654,99.6201,95.3489,95.4416,93.4878,101.0905,48.8590,76.7654,71.2572,78.5079,60.7033,84.9658,70.6351,51.0307,28.1455,102.2308,86.6816,92.2975,0.0,49.2968,0.0,55.8605,71.9425,76.1308,69.2969,78.7839,61.0996,84.4101,69.3428,44.0435,29.0822,100.8871,84.2609,90.8455,0.0,49.6715,0.0,52.0556,70.2288,0.0,2.789,2.575,2.677,3.002,3.026,1.646,2.861,2.427,2.801,2.714,2.690,2.413,2.417,2.714,3.094,3.407,2.641,3.045,2.815,1.720,3.630,1.797,2.054,2.869,2.533,2.426,2.691,2.417,2.788,1.654,2.334,2.728,2.652,2.406,2.483,1.783,2.876,3.247,3.404,2.820,2.442,3.032,2.761,2.790,2.552,2.109,2.785,2.880,3.645,2.914,3.305,3.205,1.982,2.115,2.104,2.437,2.509,2.570,2.631,2.253,2.494,2.663,2.461,1.793,2.397,2.537,2.547,2.684,2008.956284,11008.0,12.0,0.0,1946.0
3,5304207,41.5897,33.3825,0.0,84.4920,104.1299,93.2735,95.2359,95.4301,102.7365,53.8017,78.1245,70.9524,82.5537,63.1334,86.3404,68.9738,51.7717,32.2936,104.3411,89.2883,93.7916,0.0,53.8017,0.0,64.2000,73.3524,78.1762,69.9047,80.9259,63.4958,85.2491,70.9028,40.0443,36.6406,102.1452,86.8340,91.7445,0.0,56.5519,0.0,55.2727,70.2672,0.0,2.765,2.561,2.589,3.046,3.010,1.692,2.860,2.607,2.804,2.684,2.942,2.416,2.199,2.868,2.957,3.086,2.832,3.024,2.968,1.525,3.473,1.825,1.908,2.550,2.438,2.408,2.599,2.523,2.974,1.794,2.347,2.630,2.828,2.489,2.556,1.645,2.728,3.025,2.785,2.752,2.135,3.001,2.714,2.928,2.475,2.273,3.064,2.580,3.260,2.948,3.263,3.248,1.745,1.964,2.031,2.355,2.452,2.424,2.644,2.580,2.840,2.850,2.390,1.782,2.377,2.501,2.696,2.746,2010.153425,11014.0,2.0,0.0,1963.0
4,2747983,42.9063,33.2600,0.0,83.8396,103.1391,92.3403,90.9298,94.4794,99.5247,50.2683,75.4781,68.6247,79.5408,60.2699,84.4131,68.9053,45.0140,32.9522,99.9368,86.3524,90.6638,0.0,50.8713,0.0,53.4231,75.1081,76.3592,67.9926,79.0233,60.5281,84.1571,68.8623,43.2576,33.1050,98.3585,83.8898,88.6090,0.0,50.2586,0.0,51.1228,69.7002,0.0,2.932,2.969,2.940,3.229,3.124,2.212,3.408,2.742,2.924,2.904,3.024,2.618,2.415,3.072,3.012,3.519,3.272,3.212,3.048,2.120,3.517,2.194,2.189,2.410,2.545,2.484,2.924,2.548,3.221,1.768,2.493,2.956,2.789,2.703,2.615,1.941,2.994,3.273,3.154,2.863,2.361,3.173,3.089,3.175,2.624,2.523,3.298,2.846,3.533,3.129,3.452,3.257,2.056,2.197,2.179,2.784,2.651,2.580,2.774,2.511,2.972,2.727,2.504,1.927,2.579,2.863,2.843,2.829,2008.803279,11013.0,10.0,0.0,1963.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33937,3463731,35.1942,33.5758,0.0,84.6992,102.1988,93.7001,92.8186,93.6035,101.7283,47.4765,77.5299,70.7721,79.9726,57.9711,84.6008,69.5808,55.1456,33.5273,98.9759,87.0792,90.7752,0.0,50.8571,0.0,62.2778,69.3613,76.4724,70.1705,79.3960,58.8386,84.7316,70.0082,45.3381,35.5986,98.0405,85.5630,90.3360,0.0,50.4104,0.0,0.0000,71.0821,0.0,2.984,2.743,2.868,3.188,2.943,2.110,3.555,2.797,3.222,2.769,2.906,2.640,2.353,3.131,3.296,3.397,2.566,3.142,3.166,2.171,3.407,2.089,2.331,2.827,2.521,2.507,2.780,2.715,3.190,1.574,2.510,3.044,2.823,2.658,2.616,2.035,2.790,3.109,3.161,2.911,2.330,3.026,2.949,3.087,2.684,2.369,3.151,2.844,3.451,2.885,3.390,3.256,1.972,2.233,2.139,2.739,2.502,2.538,2.770,2.529,2.691,2.462,2.643,1.648,2.351,2.870,2.696,2.851,2008.333333,11009.0,5.0,0.0,1957.0
33938,3814047,36.9796,33.8569,0.0,82.1534,100.7485,96.7414,94.8558,92.6987,101.3991,47.5722,76.0068,69.6167,79.5325,59.2628,84.8136,69.9803,44.9810,33.5404,100.1067,85.9463,91.4478,0.0,51.6883,0.0,60.4348,74.2416,74.3795,67.0537,77.0860,60.5909,84.6264,67.8628,48.8344,33.9095,99.5642,84.6471,88.8383,0.0,52.2224,0.0,60.7857,71.5663,0.0,2.773,2.620,2.807,2.965,3.055,2.270,3.299,2.677,2.676,2.654,2.676,2.252,2.307,3.124,2.628,3.195,2.800,3.260,3.154,2.154,3.160,2.124,2.113,2.992,2.359,2.290,2.524,2.269,2.693,2.459,2.172,2.441,2.503,2.518,2.464,2.021,2.567,2.969,3.053,3.009,2.358,2.519,2.695,2.847,2.251,2.222,2.947,2.645,3.180,2.760,3.185,3.106,2.156,1.963,2.019,2.358,2.262,2.249,2.531,2.380,2.611,2.452,2.193,1.963,2.245,2.408,2.523,2.536,2007.808219,11001.0,10.0,1.0,1960.0
33939,4851516,31.9402,32.7079,0.0,84.1758,98.3044,92.3463,91.8287,87.2853,99.0109,45.4243,81.5066,73.8461,83.6059,59.0279,83.8707,71.9244,44.2461,28.8728,99.7905,90.2832,94.2881,0.0,49.0997,0.0,56.0400,78.8897,81.4038,71.2930,83.2491,57.0376,84.2298,69.1474,41.3478,28.9637,99.1153,88.9539,92.5305,0.0,48.8675,0.0,55.7647,72.3020,0.0,2.861,2.838,2.639,2.796,2.808,2.121,3.124,2.659,2.616,2.545,2.881,2.317,2.183,2.529,2.565,2.985,2.763,3.056,3.055,2.062,3.396,2.078,1.976,2.878,2.452,2.309,2.516,2.511,2.831,1.827,2.149,2.524,2.486,2.118,2.644,1.889,2.628,2.890,2.969,2.723,2.378,2.732,2.804,2.930,2.169,2.367,2.625,2.537,3.286,2.971,2.983,3.393,2.150,2.198,2.052,2.359,2.381,2.367,2.500,2.720,2.362,2.649,2.299,2.461,2.173,2.552,2.408,2.845,2009.402740,11013.0,5.0,1.0,1940.0
33940,3626816,42.8421,34.9272,0.0,84.0678,105.3313,94.4410,91.4660,91.4544,100.9750,56.3155,76.7598,70.5181,81.3750,63.4049,85.0943,69.8450,56.3830,34.9633,102.8980,88.7691,92.7254,0.0,52.4293,0.0,50.2013,79.3373,76.4222,67.2506,80.2725,62.7900,84.2833,68.2166,44.5671,36.7531,100.3700,86.0995,90.4809,0.0,52.9211,0.0,54.9286,70.7325,0.0,3.186,3.115,3.135,3.192,3.233,2.275,3.257,2.900,2.910,3.113,3.277,2.645,2.541,3.204,2.806,3.624,3.119,3.564,3.445,2.102,3.450,2.117,2.410,2.971,2.827,2.834,2.822,2.352,3.226,2.106,2.549,2.923,2.912,2.882,2.911,1.787,2.816,3.220,3.445,2.992,2.566,3.062,3.142,3.232,2.916,2.435,2.779,3.090,3.562,3.259,3.350,3.597,2.312,2.224,2.175,2.621,2.630,2.499,2.722,3.248,2.844,2.475,2.448,2.071,2.475,2.698,2.665,3.171,2008.704918,11013.0,9.0,1.0,1961.0
33941,2420905,29.5598,29.2897,0.0,83.6442,96.4966,76.8742,79.7448,77.8902,89.2514,38.9677,76.4373,69.4825,78.9635,61.2061,84.5935,70.5222,37.8343,25.6185,103.2140,87.2632,93.7798,0.0,47.0564,0.0,63.8667,76.9137,76.4718,68.6332,78.5726,61.1504,84.3204,69.3256,38.1960,26.0398,100.6085,85.8876,91.7349,0.0,46.7486,0.0,57.7600,68.6712,0.0,3.169,2.951,3.025,3.244,3.234,2.130,3.051,2.834,2.884,3.021,2.952,2.659,2.610,3.027,3.217,3.416,2.959,3.376,3.444,2.087,3.824,2.044,2.461,3.062,2.662,2.546,3.033,2.603,2.850,2.122,2.795,2.982,2.998,3.046,2.871,1.783,2.755,2.896,2.856,2.540,2.161,2.635,2.706,2.772,2.498,2.119,2.531,2.488,3.201,2.470,3.001,3.237,1.969,1.947,2.355,2.972,2.641,2.612,2.923,2.766,2.420,2.654,2.396,1.608,2.645,2.755,2.845,2.866,2009.498630,11016.0,7.0,0.0,1949.0

In [34]:
combined_df_5["Year_scan_initial"] = combined_df_5["Year_scan_initial"].fillna(-1)
combined_df_5["Year_scan_initial"] = combined_df_5["Year_scan_initial"].astype(int)

combined_df_5["Birthyear"] = combined_df_5["Birthyear"].fillna(-1)
combined_df_5["Birthyear"] = combined_df_5["Birthyear"].astype(int)


combined_df_5["Age"]  = combined_df_5["Year_scan_initial"] - combined_df_5["Birthyear"]
combined_df_5

,SubjectID,3rd-Ventricle,4th-Ventricle,5th-Ventricle,Brain-Stem,CC_Anterior,CC_Central,CC_Mid_Anterior,CC_Mid_Posterior,CC_Posterior,CSF,Left-Accumbens-area,Left-Amygdala,Left-Caudate,Left-Cerebellum-Cortex,Left-Cerebellum-White-Matter,Left-Hippocampus,Left-Inf-Lat-Vent,Left-Lateral-Ventricle,Left-Pallidum,Left-Putamen,Left-VentralDC,Left-WM-hypointensities,Left-choroid-plexus,Left-non-WM-hypointensities,Left-vessel,Optic-Chiasm,Right-Accumbens-area,Right-Amygdala,Right-Caudate,Right-Cerebellum-Cortex,Right-Cerebellum-White-Matter,Right-Hippocampus,Right-Inf-Lat-Vent,Right-Lateral-Ventricle,Right-Pallidum,Right-Putamen,Right-VentralDC,Right-WM-hypointensities,Right-choroid-plexus,Right-non-WM-hypointensities,Right-vessel,WM-hypointensities,non-WM-hypointensities,lh_G_front_inf-Opercular_thickness,lh_G_front_inf-Triangul_thickness,lh_G_front_middle_thickness,lh_G_front_sup_thickness,lh_G_oc-temp_lat-fusifor_thickness,lh_G_oc-temp_med-Lingual_thickness,lh_G_oc-temp_med-Parahip_thickness,lh_G_occipital_middle_thickness,lh_G_orbital_thickness,lh_G_pariet_inf-Angular_thickness,lh_G_pariet_inf-Supramar_thickness,lh_G_parietal_sup_thickness,lh_G_postcentral_thickness,lh_G_precentral_thickness,lh_G_rectus_thickness,lh_G_temp_sup-Lateral_thickness,lh_G_temp_sup-Plan_tempo_thickness,lh_G_temporal_inf_thickness,lh_G_temporal_middle_thickness,lh_Pole_occipital_thickness,lh_Pole_temporal_thickness,lh_S_calcarine_thickness,lh_S_central_thickness,lh_S_collat_transv_ant_thickness,lh_S_front_inf_thickness,lh_S_front_middle_thickness,lh_S_front_sup_thickness,lh_S_occipital_ant_thickness,lh_S_orbital-H_Shaped_thickness,lh_S_pericallosal_thickness,lh_S_postcentral_thickness,lh_S_precentral-inf-part_thickness,lh_S_precentral-sup-part_thickness,lh_S_temporal_inf_thickness,lh_S_temporal_sup_thickness,rh_G_cuneus_thickness,rh_G_front_middle_thickness,rh_G_front_sup_thickness,rh_G_oc-temp_lat-fusifor_thickness,rh_G_occipital_middle_thickness,rh_G_occipital_sup_thickness,rh_G_orbital_thickness,rh_G_pariet_inf-Angular_thickness,rh_G_pariet_inf-Supramar_thickness,rh_G_parietal_sup_thickness,rh_G_postcentral_thickness,rh_G_precentral_thickness,rh_G_precuneus_thickness,rh_G_temp_sup-Lateral_thickness,rh_G_temp_sup-Plan_tempo_thickness,rh_G_temporal_inf_thickness,rh_G_temporal_middle_thickness,rh_Pole_occipital_thickness,rh_S_calcarine_thickness,rh_S_central_thickness,rh_S_cingul-Marginalis_thickness,rh_S_front_inf_thickness,rh_S_front_middle_thickness,rh_S_front_sup_thickness,rh_S_interm_prim-Jensen_thickness,rh_S_oc-temp_lat_thickness,rh_S_occipital_ant_thickness,rh_S_parieto_occipital_thickness,rh_S_pericallosal_thickness,rh_S_postcentral_thickness,rh_S_precentral-inf-part_thickness,rh_S_precentral-sup-part_thickness,rh_S_temporal_sup_thickness,Year_scan_initial,Assessment_centre_initial,Month_scan_initial,Sex,Birthyear,Age
0,1533138,36.8674,31.3818,0.0,81.5837,100.2311,94.2112,93.9213,89.7624,101.8197,50.2793,78.4219,71.2338,80.8676,59.8507,84.6188,68.5732,46.7229,33.9679,101.8322,86.8691,91.6590,0.0,51.1266,0.0,57.8200,73.7333,78.6486,67.9744,81.4864,60.6036,85.0926,68.6901,47.5164,34.8871,98.3383,83.9349,88.3665,0.0,52.4355,0.0,60.0000,72.3171,0.0,2.955,2.859,2.994,3.053,3.310,2.248,2.847,2.846,3.016,2.873,3.261,2.815,2.368,2.955,3.441,3.265,2.718,3.326,3.215,2.260,3.297,2.075,2.159,3.082,2.661,2.565,2.774,2.719,3.068,2.288,2.521,2.617,2.518,2.518,2.803,2.051,2.741,2.932,3.033,2.811,2.532,3.070,2.830,2.593,2.522,2.183,2.853,2.670,3.282,2.650,3.318,3.051,2.059,2.016,1.869,2.466,2.446,2.393,2.753,2.170,2.914,2.665,2.533,1.965,2.227,2.672,2.561,2.735,2010,11016.0,3.0,0.0,1950,60
1,1875529,31.3638,30.1527,0.0,83.1511,95.3329,89.9717,90.3416,85.7553,100.0998,47.6822,75.2107,67.8566,79.1048,61.6535,86.0415,70.1340,41.7886,28.0750,101.7199,84.5846,92.3921,0.0,50.0821,0.0,56.6591,76.4964,78.8506,69.8590,81.3028,61.3760,85.2568,70.4684,42.9726,31.5494,101.0202,83.6074,90.9502,0.0,52.0951,0.0,60.4118,70.6537,0.0,3.153,3.050,2.993,3.167,3.214,2.035,3.097,2.610,3.199,2.890,2.850,2.438,2.402,3.158,3.121,3.200,2.955,3.230,3.144,2.084,3.536,2.271,2.179,2.845,2.477,2.575,2.740,2.315,3.130,2.512,2.341,2.988,2.921,2.653,2.749,1.708,2.636,2.849,2.571,2.601,1.949,2.683,2.521,2.693,2.091,1.851,2.715,2.438,2.772,2.341,2.882,2.920,1.803,1.938,1.751,2.149,2.395,2.318,2.481,2.309,2.913,2.403,2.287,2.407,2.016,2.794,2.706,2.676,2008,11008.0,2.0,0.0,1948,60
2,4758824,35.0732,36.2819,0.0,84.1654,99.6201,95.3489,95.4416,93.4878,101.0905,48.8590,76.7654,71.2572,78.5079,60.7033,84.9658,70.6351,51.0307,28.1455,102.2308,86.6816,92.2975,0.0,49.2968,0.0,55.8605,71.9425,76.1308,69.2969,78.7839,61.0996,84.4101,69.3428,44.0435,29.0822,100.8871,84.2609,90.8455,0.0,49.6715,0.0,52.0556,70.2288,0.0,2.789,2.575,2.677,3.002,3.026,1.646,2.861,2.427,2.801,2.714,2.690,2.413,2.417,2.714,3.094,3.407,2.641,3.045,2.815,1.720,3.630,1.797,2.054,2.869,2.533,2.426,2.691,2.417,2.788,1.654,2.334,2.728,2.652,2.406,2.483,1.783,2.876,3.247,3.404,2.820,2.442,3.032,2.761,2.790,2.552,2.109,2.785,2.880,3.645,2.914,3.305,3.205,1.982,2.115,2.104,2.437,2.509,2.570,2.631,2.253,2.494,2.663,2.461,1.793,2.397,2.537,2.547,2.684,2008,11008.0,12.0,0.0,1946,62
3,5304207,41.5897,33.3825,0.0,84.4920,104.1299,93.2735,95.2359,95.4301,102.7365,53.8017,78.1245,70.9524,82.5537,63.1334,86.3404,68.9738,51.7717,32.2936,104.3411,89.2883,93.7916,0.0,53.8017,0.0,64.2000,73.3524,78.1762,69.9047,80.9259,63.4958,85.2491,70.9028,40.0443,36.6406,102.1452,86.8340,91.7445,0.0,56.5519,0.0,55.2727,70.2672,0.0,2.765,2.561,2.589,3.046,3.010,1.692,2.860,2.607,2.804,2.684,2.942,2.416,2.199,2.868,2.957,3.086,2.832,3.024,2.968,1.525,3.473,1.825,1.908,2.550,2.438,2.408,2.599,2.523,2.974,1.794,2.347,2.630,2.828,2.489,2.556,1.645,2.728,3.025,2.785,2.752,2.135,3.001,2.714,2.928,2.475,2.273,3.064,2.580,3.260,2.948,3.263,3.248,1.745,1.964,2.031,2.355,2.452,2.424,2.644,2.580,2.840,2.850,2.390,1.782,2.377,2.501,2.696,2.746,2010,11014.0,2.0,0.0,1963,47
4,2747983,42.9063,33.2600,0.0,83.8396,103.1391,92.3403,90.9298,94.4794,99.5247,50.2683,75.4781,68.6247,79.5408,60.2699,84.4131,68.9053,45.0140,32.9522,99.9368,86.3524,90.6638,0.0,50.8713,0.0,53.4231,75.1081,76.3592,67.9926,79.0233,60.5281,84.1571,68.8623,43.2576,33.1050,98.3585,83.8898,88.6090,0.0,50.2586,0.0,51.1228,69.7002,0.0,2.932,2.969,2.940,3.229,3.124,2.212,3.408,2.742,2.924,2.904,3.024,2.618,2.415,3.072,3.012,3.519,3.272,3.212,3.048,2.120,3.517,2.194,2.189,2.410,2.545,2.484,2.924,2.548,3.221,1.768,2.493,2.956,2.789,2.703,2.615,1.941,2.994,3.273,3.154,2.863,2.361,3.173,3.089,3.175,2.624,2.523,3.298,2.846,3.533,3.129,3.452,3.257,2.056,2.197,2.179,2.784,2.651,2.580,2.774,2.511,2.972,2.727,2.504,1.927,2.579,2.863,2.843,2.829,2008,11013.0,10.0,0.0,1963,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33937,3463731,35.1942,33.5758,0.0,84.6992,102.1988,93.7001,92.8186,93.6035,101.7283,47.4765,77.5299,70.7721,79.9726,57.9711,84.6008,69.5808,55.1456,33.5273,98.9759,87.0792,90.7752,0.0,50.8571,0.0,62.2778,69.3613,76.4724,70.1705,79.3960,58.8386,84.7316,70.0082,45.3381,35.5986,98.0405,85.5630,90.3360,0.0,50.4104,0.0,0.0000,71.0821,0.0,2.984,2.743,2.868,3.188,2.943,2.110,3.555,2.797,3.222,2.769,2.906,2.640,2.353,3.131,3.296,3.397,2.566,3.142,3.166,2.171,3.407,2.089,2.331,2.827,2.521,2.507,2.780,2.715,3.190,1.574,2.510,3.044,2.823,2.658,2.616,2.035,2.790,3.109,3.161,2.911,2.330,3.026,2.949,3.087,2.684,2.369,3.151,2.844,3.451,2.885,3.390,3.256,1.972,2.233,2.139,2.739,2.502,2.538,2.770,2.529,2.691,2.462,2.643,1.648,2.351,2.870,2.696,2.851,2008,11009.0,5.0,0.0,1957,51
33938,3814047,36.9796,33.8569,0.0,82.1534,100.7485,96.7414,94.8558,92.6987,101.3991,47.5722,76.0068,69.6167,79.5325,59.2628,84.8136,69.9803,44.9810,33.5404,100.1067,85.9463,91.4478,0.0,51.6883,0.0,60.4348,74.2416,74.3795,67.0537,77.0860,60.5909,84.6264,67.8628,48.8344,33.9095,99.5642,84.6471,88.8383,0.0,52.2224,0.0,60.7857,71.5663,0.0,2.773,2.620,2.807,2.965,3.055,2.270,3.299,2.677,2.676,2.654,2.676,2.252,2.307,3.124,2.628,3.195,2.800,3.260,3.154,2.154,3.160,2.124,2.113,2.992,2.359,2.290,2.524,2.269,2.693,2.459,2.172,2.441,2.503,2.518,2.464,2.021,2.567,2.969,3.053,3.009,2.358,2.519,2.695,2.847,2.251,2.222,2.947,2.645,3.180,2.760,3.185,3.106,2.156,1.963,2.019,2.358,2.262,2.249,2.531,2.380,2.611,2.452,2.193,1.963,2.245,2.408,2.523,2.536,2007,11001.0,10.0,1.0,1960,47
33939,4851516,31.9402,32.7079,0.0,84.1758,98.3044,92.3463,91.8287,87.2853,99.0109,45.4243,81.5066,73.8461,83.6059,59.0279,83.8707,71.9244,44.2461,28.8728,99.7905,90.2832,94.2881,0.0,49.0997,0.0,56.0400,78.8897,81.4038,71.2930,83.2491,57.0376,84.2298,69.1474,41.3478,28.9637,99.1153,88.9539,92.5305,0.0,48.8675,0.0,55.7647,72.3020,0.0,2.861,2.838,2.639,2.796,2.808,2.121,3.124,2.659,2.616,2.545,2.881,2.317,2.183,2.529,2.565,2.985,2.763,3.056,3.055,2.062,3.396,2.078,1.976,2.878,2.452,2.309,2.516,2.511,2.831,1.827,2.149,2.524,2.486,2.118,2.644,1.889,2.628,2.890,2.969,2.723,2.378,2.732,2.804,2.930,2.169,2.367,2.625,2.537,3.286,2.971,2.983,3.393,2.150,2.198,2.052,2.359,2.381,2.367,2.500,2.720,2.362,2.649,2.299,2.461,2.173,2.552,2.408,2.845,2009,11013.0,5.0,1.0,1940,69
33940,3626816,42.8421,34.9272,0.0,84.0678,105.3313,94.4410,91.4660,91.4544,100.9750,56.3155,76.7598,70.5181,81.3750,63.4049,85.0943,69.8450,56.3830,34.9633,102.8980,88.7691,92.7254,0.0,52.4293,0.0,50.2013,79.3373,76.4222,67.2506,80.2725,62.7900,84.2833,68.2166,44.5671,36.7531,100.3700,86.0995,90.4809,0.0,52.9211,0.0,54.9286,70.7325,0.0,3.186,3.115,3.135,3.192,3.233,2.275,3.257,2.900,2.910,3.113,3.277,2.645,2.541,3.204,2.806,3.624,3.119,3.564,3.445,2.102,3.450,2.117,2.410,2.971,2.827,2.834,2.822,2.352,3.226,2.106,2.549,2.923,2.912,2.882,2.911,1.787,2.816,3.220,3.445,2.992,2.566,3.062,3.142,3.232,2.916,2.435,2.779,3.090,3.562,3.259,3.350,3.597,2.312,2.224,2.175,2.621,2.630,2.499,2.722,3.248,2.844,2.475,2.448,2.071,2.475,2.698,2.665,3.171,2008,11013.0,9.0,1.0,1961,47
33941,2420905,29.5598,29.2897,0.0,83.6442,96.4966,76.8742,79.7448,77.8902,89.2514,38.9677,76.4373,69.4825,78.9635,61.2061,84.5935,70.5222,37.8343,25.6185,103.2140,87.2632,93.7798,0.0,47.0564,0.0,63.8667,76.9137,76.4718,68.6332,78.5726,61.1504,84.3204,69.3256,38.1960,26.0398,100.6085,85.8876,91.7349,0.0,46.7486,0.0,57.7600,68.6712,0.0,3.169,2.951,3.025,3.244,3.234,2.130,3.051,2.834,2.884,3.021,2.952,2.659,2.610,3.027,3.217,3.416,2.959,3.376,3.444,2.087,3.824,2.044,2.461,3.062,2.662,2.546,3.033,2.603,2.850,2.122,2.795,2.982,2.998,3.046,2.871,1.783,2.755,2.896,2.856,2.540,2.161,2.635,2.706,2.772,2.498,2.119,2.531,2.488,3.201,2.470,3.001,3.237,1.969,1.947,2.355,2.972,2.641,2.612,2.923,2.766,2.420,2.654,2.396,1.608,2.645,2.755,2.845,2.866,2009,11016.0,7.0,0.0,1949,60

In [35]:
combined_df_5.to_csv("final_datatabel.csv")

In [41]:
#final clean up of the resulting dataset
df = pd.read_csv("final_datatabel.csv")
df.drop(columns=["Month_scan_initial","Unnamed: 0"],inplace=True)

df.rename(columns={'Year_scan_initial': 'Year_initial_scan', 'Assessment_centre_initial': 'Site'}, inplace=True)
df.set_index("SubjectID")

,3rd-Ventricle,4th-Ventricle,5th-Ventricle,Brain-Stem,CC_Anterior,CC_Central,CC_Mid_Anterior,CC_Mid_Posterior,CC_Posterior,CSF,Left-Accumbens-area,Left-Amygdala,Left-Caudate,Left-Cerebellum-Cortex,Left-Cerebellum-White-Matter,Left-Hippocampus,Left-Inf-Lat-Vent,Left-Lateral-Ventricle,Left-Pallidum,Left-Putamen,Left-VentralDC,Left-WM-hypointensities,Left-choroid-plexus,Left-non-WM-hypointensities,Left-vessel,Optic-Chiasm,Right-Accumbens-area,Right-Amygdala,Right-Caudate,Right-Cerebellum-Cortex,Right-Cerebellum-White-Matter,Right-Hippocampus,Right-Inf-Lat-Vent,Right-Lateral-Ventricle,Right-Pallidum,Right-Putamen,Right-VentralDC,Right-WM-hypointensities,Right-choroid-plexus,Right-non-WM-hypointensities,Right-vessel,WM-hypointensities,non-WM-hypointensities,lh_G_front_inf-Opercular_thickness,lh_G_front_inf-Triangul_thickness,lh_G_front_middle_thickness,lh_G_front_sup_thickness,lh_G_oc-temp_lat-fusifor_thickness,lh_G_oc-temp_med-Lingual_thickness,lh_G_oc-temp_med-Parahip_thickness,lh_G_occipital_middle_thickness,lh_G_orbital_thickness,lh_G_pariet_inf-Angular_thickness,lh_G_pariet_inf-Supramar_thickness,lh_G_parietal_sup_thickness,lh_G_postcentral_thickness,lh_G_precentral_thickness,lh_G_rectus_thickness,lh_G_temp_sup-Lateral_thickness,lh_G_temp_sup-Plan_tempo_thickness,lh_G_temporal_inf_thickness,lh_G_temporal_middle_thickness,lh_Pole_occipital_thickness,lh_Pole_temporal_thickness,lh_S_calcarine_thickness,lh_S_central_thickness,lh_S_collat_transv_ant_thickness,lh_S_front_inf_thickness,lh_S_front_middle_thickness,lh_S_front_sup_thickness,lh_S_occipital_ant_thickness,lh_S_orbital-H_Shaped_thickness,lh_S_pericallosal_thickness,lh_S_postcentral_thickness,lh_S_precentral-inf-part_thickness,lh_S_precentral-sup-part_thickness,lh_S_temporal_inf_thickness,lh_S_temporal_sup_thickness,rh_G_cuneus_thickness,rh_G_front_middle_thickness,rh_G_front_sup_thickness,rh_G_oc-temp_lat-fusifor_thickness,rh_G_occipital_middle_thickness,rh_G_occipital_sup_thickness,rh_G_orbital_thickness,rh_G_pariet_inf-Angular_thickness,rh_G_pariet_inf-Supramar_thickness,rh_G_parietal_sup_thickness,rh_G_postcentral_thickness,rh_G_precentral_thickness,rh_G_precuneus_thickness,rh_G_temp_sup-Lateral_thickness,rh_G_temp_sup-Plan_tempo_thickness,rh_G_temporal_inf_thickness,rh_G_temporal_middle_thickness,rh_Pole_occipital_thickness,rh_S_calcarine_thickness,rh_S_central_thickness,rh_S_cingul-Marginalis_thickness,rh_S_front_inf_thickness,rh_S_front_middle_thickness,rh_S_front_sup_thickness,rh_S_interm_prim-Jensen_thickness,rh_S_oc-temp_lat_thickness,rh_S_occipital_ant_thickness,rh_S_parieto_occipital_thickness,rh_S_pericallosal_thickness,rh_S_postcentral_thickness,rh_S_precentral-inf-part_thickness,rh_S_precentral-sup-part_thickness,rh_S_temporal_sup_thickness,Year_initial_scan,Site,Sex,Birthyear,Age
SubjectID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1533138,36.8674,31.3818,0.0,81.5837,100.2311,94.2112,93.9213,89.7624,101.8197,50.2793,78.4219,71.2338,80.8676,59.8507,84.6188,68.5732,46.7229,33.9679,101.8322,86.8691,91.6590,0.0,51.1266,0.0,57.8200,73.7333,78.6486,67.9744,81.4864,60.6036,85.0926,68.6901,47.5164,34.8871,98.3383,83.9349,88.3665,0.0,52.4355,0.0,60.0000,72.3171,0.0,2.955,2.859,2.994,3.053,3.310,2.248,2.847,2.846,3.016,2.873,3.261,2.815,2.368,2.955,3.441,3.265,2.718,3.326,3.215,2.260,3.297,2.075,2.159,3.082,2.661,2.565,2.774,2.719,3.068,2.288,2.521,2.617,2.518,2.518,2.803,2.051,2.741,2.932,3.033,2.811,2.532,3.070,2.830,2.593,2.522,2.183,2.853,2.670,3.282,2.650,3.318,3.051,2.059,2.016,1.869,2.466,2.446,2.393,2.753,2.170,2.914,2.665,2.533,1.965,2.227,2.672,2.561,2.735,2010,11016.0,0.0,1950,60
1875529,31.3638,30.1527,0.0,83.1511,95.3329,89.9717,90.3416,85.7553,100.0998,47.6822,75.2107,67.8566,79.1048,61.6535,86.0415,70.1340,41.7886,28.0750,101.7199,84.5846,92.3921,0.0,50.0821,0.0,56.6591,76.4964,78.8506,69.8590,81.3028,61.3760,85.2568,70.4684,42.9726,31.5494,101.0202,83.6074,90.9502,0.0,52.0951,0.0,60.4118,70.6537,0.0,3.153,3.050,2.993,3.167,3.214,2.035,3.097,2.610,3.199,2.890,2.850,2.438,2.402,3.158,3.121,3.200,2.955,3.230,3.144,2.084,3.536,2.271,2.179,2.845,2.477,2.575,2.740,2.315,3.130,2.512,2.341,2.988,2.921,2.653,2.749,1.708,2.636,2.849,2.571,2.601,1.949,2.683,2.521,2.693,2.091,1.851,2.715,2.438,2.772,2.341,2.882,2.920,1.803,1.938,1.751,2.149,2.395,2.318,2.481,2.309,2.913,2.403,2.287,2.407,2.016,2.794,2.706,2.676,2008,11008.0,0.0,1948,60
4758824,35.0732,36.2819,0.0,84.1654,99.6201,95.3489,95.4416,93.4878,101.0905,48.8590,76.7654,71.2572,78.5079,60.7033,84.9658,70.6351,51.0307,28.1455,102.2308,86.6816,92.2975,0.0,49.2968,0.0,55.8605,71.9425,76.1308,69.2969,78.7839,61.0996,84.4101,69.3428,44.0435,29.0822,100.8871,84.2609,90.8455,0.0,49.6715,0.0,52.0556,70.2288,0.0,2.789,2.575,2.677,3.002,3.026,1.646,2.861,2.427,2.801,2.714,2.690,2.413,2.417,2.714,3.094,3.407,2.641,3.045,2.815,1.720,3.630,1.797,2.054,2.869,2.533,2.426,2.691,2.417,2.788,1.654,2.334,2.728,2.652,2.406,2.483,1.783,2.876,3.247,3.404,2.820,2.442,3.032,2.761,2.790,2.552,2.109,2.785,2.880,3.645,2.914,3.305,3.205,1.982,2.115,2.104,2.437,2.509,2.570,2.631,2.253,2.494,2.663,2.461,1.793,2.397,2.537,2.547,2.684,2008,11008.0,0.0,1946,62
5304207,41.5897,33.3825,0.0,84.4920,104.1299,93.2735,95.2359,95.4301,102.7365,53.8017,78.1245,70.9524,82.5537,63.1334,86.3404,68.9738,51.7717,32.2936,104.3411,89.2883,93.7916,0.0,53.8017,0.0,64.2000,73.3524,78.1762,69.9047,80.9259,63.4958,85.2491,70.9028,40.0443,36.6406,102.1452,86.8340,91.7445,0.0,56.5519,0.0,55.2727,70.2672,0.0,2.765,2.561,2.589,3.046,3.010,1.692,2.860,2.607,2.804,2.684,2.942,2.416,2.199,2.868,2.957,3.086,2.832,3.024,2.968,1.525,3.473,1.825,1.908,2.550,2.438,2.408,2.599,2.523,2.974,1.794,2.347,2.630,2.828,2.489,2.556,1.645,2.728,3.025,2.785,2.752,2.135,3.001,2.714,2.928,2.475,2.273,3.064,2.580,3.260,2.948,3.263,3.248,1.745,1.964,2.031,2.355,2.452,2.424,2.644,2.580,2.840,2.850,2.390,1.782,2.377,2.501,2.696,2.746,2010,11014.0,0.0,1963,47
2747983,42.9063,33.2600,0.0,83.8396,103.1391,92.3403,90.9298,94.4794,99.5247,50.2683,75.4781,68.6247,79.5408,60.2699,84.4131,68.9053,45.0140,32.9522,99.9368,86.3524,90.6638,0.0,50.8713,0.0,53.4231,75.1081,76.3592,67.9926,79.0233,60.5281,84.1571,68.8623,43.2576,33.1050,98.3585,83.8898,88.6090,0.0,50.2586,0.0,51.1228,69.7002,0.0,2.932,2.969,2.940,3.229,3.124,2.212,3.408,2.742,2.924,2.904,3.024,2.618,2.415,3.072,3.012,3.519,3.272,3.212,3.048,2.120,3.517,2.194,2.189,2.410,2.545,2.484,2.924,2.548,3.221,1.768,2.493,2.956,2.789,2.703,2.615,1.941,2.994,3.273,3.154,2.863,2.361,3.173,3.089,3.175,2.624,2.523,3.298,2.846,3.533,3.129,3.452,3.257,2.056,2.197,2.179,2.784,2.651,2.580,2.774,2.511,2.972,2.727,2.504,1.927,2.579,2.863,2.843,2.829,2008,11013.0,0.0,1963,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3463731,35.1942,33.5758,0.0,84.6992,102.1988,93.7001,92.8186,93.6035,101.7283,47.4765,77.5299,70.7721,79.9726,57.9711,84.6008,69.5808,55.1456,33.5273,98.9759,87.0792,90.7752,0.0,50.8571,0.0,62.2778,69.3613,76.4724,70.1705,79.3960,58.8386,84.7316,70.0082,45.3381,35.5986,98.0405,85.5630,90.3360,0.0,50.4104,0.0,0.0000,71.0821,0.0,2.984,2.743,2.868,3.188,2.943,2.110,3.555,2.797,3.222,2.769,2.906,2.640,2.353,3.131,3.296,3.397,2.566,3.142,3.166,2.171,3.407,2.089,2.331,2.827,2.521,2.507,2.780,2.715,3.190,1.574,2.510,3.044,2.823,2.658,2.616,2.035,2.790,3.109,3.161,2.911,2.330,3.026,2.949,3.087,2.684,2.369,3.151,2.844,3.451,2.885,3.390,3.256,1.972,2.233,2.139,2.739,2.502,2.538,2.770,2.529,2.691,2.462,2.643,1.648,2.351,2.870,2.696,2.851,2008,11009.0,0.0,1957,51
3814047,36.9796,33.8569,0.0,82.1534,100.7485,96.7414,94.8558,92.6987,101.3991,47.5722,76.0068,69.6167,79.5325,59.2628,84.8136,69.9803,44.9810,33.5404,100.1067,85.9463,91.4478,0.0,51.6883,0.0,60.4348,74.2416,74.3795,67.0537,77.0860,60.5909,84.6264,67.8628,48.8344,33.9095,99.5642,84.6471,88.8383,0.0,52.2224,0.0,60.7857,71.5663,0.0,2.773,2.620,2.807,2.965,3.055,2.270,3.299,2.677,2.676,2.654,2.676,2.252,2.307,3.124,2.628,3.195,2.800,3.260,3.154,2.154,3.160,2.124,2.113,2.992,2.359,2.290,2.524,2.269,2.693,2.459,2.172,2.441,2.503,2.518,2.464,2.021,2.567,2.969,3.053,3.009,2.358,2.519,2.695,2.847,2.251,2.222,2.947,2.645,3.180,2.760,3.185,3.106,2.156,1.963,2.019,2.358,2.262,2.249,2.531,2.380,2.611,2.452,2.193,1.963,2.245,2.408,2.523,2.536,2007,11001.0,1.0,1960,47
4851516,31.9402,32.7079,0.0,84.1758,98.3044,92.3463,91.8287,87.2853,99.0109,45.4243,81.5066,73.8461,83.6059,59.0279,83.8707,71.9244,44.2461,28.8728,99.7905,90.2832,94.2881,0.0,49.0997,0.0,56.0400,78.8897,81.4038,71.2930,83.2491,57.0376,84.2298,69.1474,41.3478,28.9637,99.1153,88.9539,92.5305,0.0,48.8675,0.0,55.7647,72.3020,0.0,2.861,2.838,2.639,2.796,2.808,2.121,3.124,2.659,2.616,2.545,2.881,2.317,2.183,2.529,2.565,2.985,2.763,3.056,3.055,2.062,3.396,2.078,1.976,2.878,2.452,2.309,2.516,2.511,2.831,1.827,2.149,2.524,2.486,2.118,2.644,1.889,2.628,2.890,2.969,2.723,2.378,2.732,2.804,2.930,2.169,2.367,2.625,2.537,3.286,2.971,2.983,3.393,2.150,2.198,2.052,2.359,2.381,2.367,2.500,2.720,2.362,2.649,2.299,2.461,2.173,2.552,2.408,2.845,2009,11013.0,1.0,1940,69
3626816,42.8421,34.9272,0.0,84.0678,105.3313,94.4410,91.4660,91.4544,100.9750,56.3155,76.7598,70.5181,81.3750,63.4049,85.0943,69.8450,56.3830,34.9633,102.8980,88.7691,92.7254,0.0,52.4293,0.0,50.2013,79.3373,76.4222,67.2506,80.2725,62.7900,84.2833,68.2166,44.5671,36.7531,100.3700,86.0995,90.4809,0.0,52.9211,0.0,54.9286,70.7325,0.0,3.186,3.115,3.135,3.192,3.233,2.275,3.257,2.900,2.910,3.113,3.277,2.645,2.541,3.204,2.806,3.624,3.119,3.564,3.445,2.102,3.450,2.117,2.410,2.971,2.827,2.834,2.822,2.352,3.226,2.106,2.549,2.923,2.912,2.882,2.911,1.787,2.816,3.220,3.445,2.992,2.566,3.062,3.142,3.232,2.916,2.435,2.779,3.090,3.562,3.259,3.350,3.597,2.312,2.224,2.175,2.621,2.630,2.499,2.722,3.248,2.844,2.475,2.448,2.071,2.475,2.698,2.665,3.171,2008,11013.0,1.0,1961,47
2420905,29.5598,29.2897,0.0,83.6442,96.4966,76.8742,79.7448,77.8902,89.2514,38.9677,76.4373,69.4825,78.9635,61.2061,84.5935,70.5222,37.8343,25.6185,103.2140,87.2632,93.7798,0.0,47.0564,0.0,63.8667,76.9137,76.4718,68.6332,78.5726,61.1504,84.3204,69.3256,38.1960,26.0398,100.6085,85.8876,91.7349,0.0,46.7486,0.0,57.7600,68.6712,0.0,3.169,2.951,3.025,3.244,3.234,2.130,3.051,2.834,2.884,3.021,2.952,2.659,2.610,3.027,3.217,3.416,2.959,3.376,3.444,2.087,3.824,2.044,2.461,3.062,2.662,2.546,3.033,2.603,2.850,2.122,2.795,2.982,2.998,3.046,2.871,1.783,2.755,2.896,2.856,2.540,2.161,2.635,2.706,2.772,2.498,2.119,2.531,2.488,3.201,2.470,3.001,3.237,1.969,1.947,2.355,2.972,2.641,2.612,2.923,2.766,2.420,2.654,2.396,1.608,2.645,2.755,2.845,2.866,2009,11016.0,0.0,1949,60

In [42]:
df.to_csv("Final_Data.csv")

In [16]:
csv_path = "/home/preclineu/quirom/Desktop/internship/Normative-Models-and-VAE/logs/csv_files/"

data_4 = os.path.join(csv_path, "Yr_mnth_site_scan.csv")
df_4 = pd.read_csv(data_4)
df_4 = df_4.rename(columns={"Assessment_centre_1_repeat" : "Site_imaging"})
df_5 = df_4[["SubjectID", "Site_imaging"]].copy()
df_5


#let's see if this merges with the other data

        SubjectID  Site_imaging
0         1000012           NaN
1         1000029           NaN
2         1000031           NaN
3         1000047           NaN
4         1000050       11025.0
...           ...           ...
502361    6025263           NaN
502362    6025278           NaN
502363    6025280           NaN
502364    6025291           NaN
502365    6025306       11025.0

[502366 rows x 2 columns]

In [22]:
df = pd.read_csv("/home/preclineu/quirom/Desktop/internship/Normative-Models-and-VAE/logs/final_data/Final_Data.csv")
df_check = df.merge(df_5, how="left")
df_check = df_check.drop(columns=["Site"])
df_check = df_check.rename(columns={"Site_imaging":"Site"})
#df_check.to_csv("Final_data_corrected_site.csv")
df_check

,Unnamed: 0,SubjectID,3rd-Ventricle,4th-Ventricle,5th-Ventricle,Brain-Stem,CC_Anterior,CC_Central,CC_Mid_Anterior,CC_Mid_Posterior,...,rh_S_pericallosal_thickness,rh_S_postcentral_thickness,rh_S_precentral-inf-part_thickness,rh_S_precentral-sup-part_thickness,rh_S_temporal_sup_thickness,Year_initial_scan,Sex,Birthyear,Age,Site
0,0,1533138,36.8674,31.3818,0.0,81.5837,100.2311,94.2112,93.9213,89.7624,...,1.965,2.227,2.672,2.561,2.735,2010,0.0,1950,60,11025.0
1,1,1875529,31.3638,30.1527,0.0,83.1511,95.3329,89.9717,90.3416,85.7553,...,2.407,2.016,2.794,2.706,2.676,2008,0.0,1948,60,11025.0
2,2,4758824,35.0732,36.2819,0.0,84.1654,99.6201,95.3489,95.4416,93.4878,...,1.793,2.397,2.537,2.547,2.684,2008,0.0,1946,62,11025.0
3,3,5304207,41.5897,33.3825,0.0,84.4920,104.1299,93.2735,95.2359,95.4301,...,1.782,2.377,2.501,2.696,2.746,2010,0.0,1963,47,11025.0
4,4,2747983,42.9063,33.2600,0.0,83.8396,103.1391,92.3403,90.9298,94.4794,...,1.927,2.579,2.863,2.843,2.829,2008,0.0,1963,45,11025.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33937,33937,3463731,35.1942,33.5758,0.0,84.6992,102.1988,93.7001,92.8186,93.6035,...,1.648,2.351,2.870,2.696,2.851,2008,0.0,1957,51,11027.0
33938,33938,3814047,36.9796,33.8569,0.0,82.1534,100.7485,96.7414,94.8558,92.6987,...,1.963,2.245,2.408,2.523,2.536,2007,1.0,1960,47,11025.0
33939,33939,4851516,31.9402,32.7079,0.0,84.1758,98.3044,92.3463,91.8287,87.2853,...,2.461,2.173,2.552,2.408,2.845,2009,1.0,1940,69,11027.0
33940,33940,3626816,42.8421,34.9272,0.0,84.0678,105.3313,94.4410,91.4660,91.4544,...,2.071,2.475,2.698,2.665,3.171,2008,1.0,1961,47,11025.0
33941,33941,2420905,29.5598,29.2897,0.0,83.6442,96.4966,76.8742,79.7448,77.8902,...,1.608,2.645,2.755,2.845,2.866,2009,0.0,1949,60,11025.0

In [ ]:
health_outcomes = pd.read_csv("/project_cephfs/3022017.06/UKB/phenotypes/current/50_health_outcomes.csv")
health_outcomes.head()